snowflakedb/terraform-provider-snowflake

- pkg/resources/database.go
- pkg/resources/role.go
- pkg/resources/user.go
- pkg/resources/warehouse.go
Per the terraform docs, we need to set Id to "" to mark that the resource has been deleted.
> [fix] properly delete resouces

- README.md
- main.go
Was causing markdown tables to be broken.
> turn off autowrap for generated docs

- Makefile
- README.md
- pkg/resources/helpers_test.go
- pkg/resources/role_grants.go
- pkg/resources/role_grants_acceptance_test.go
- pkg/resources/role_grants_test.go
This enables import of this resource (tested here and manually).
Side effect is that this resource assumes it exclusively manages all role grants for this role.
> [breaking] make snowflake_role_grants exclusive, remove `name`

- pkg/resources/user.go
- pkg/resources/user_test.go
Without this it will just try to read a user and in the case where a user has been deleted, but is in the state file we will get an error. There may be a graceful way to handle that in the Read function, but this seems like a cleaner way to do it.
> add Exists function to user object

- .travis.yml
This should enable forks to build successfully on travis-ci.
See https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/39
> set go_import_path

- pkg/resources/grant_helpers.go
- pkg/resources/user_acceptance_test.go
It seems that fmt.Printf does not make it through from the plugin to terraform's output.
> switch from fmt to log for DEBUG

- .travis.yml
- go.mod
- go.sum
- pkg/resources/schema_grant.go
- pkg/resources/schema_grant_test.go
Define correct list of valid schema grant privileges and actually use it.  Also update unit tests to ensure something other than USAGE works correctly.
Addresses #68.
> schema_grant to support more than just USAGE

- pkg/db/db.go
This causes logging from the gosnowflake driver to actually successfully
bubble up to the master terraform process console log.
As a major side benefit, this was the fix for large terraform plans
hanging forever after refreshing a couple dozen schema_grant resources.
For more information see #69.
Fixes #69.
> db.go: use log.Println instead of fmt.Println

- pkg/resources/managed_account.go
- pkg/resources/resource_monitor.go
- pkg/resources/schema.go
- pkg/resources/share.go
- pkg/resources/user.go
- pkg/resources/view.go
We were failing to close rows objects, leading to leaks and possibly lock-ups.
Fixes #73, #25
> [fix] close rows objects

- pkg/resources/view.go
- pkg/resources/view_test.go
Because we scan like this and don't scan into a struct, anytime that snowflake adds a column we need to do the same.
> [fix] fix scan of "show view"

- README.md
- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_test.go
- pkg/snowflake/generic.go
- pkg/snowflake/resource_monitor.go
- pkg/snowflake/resource_monitor_test.go
Issue: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/109
Note that if a float has more than 6 trailing numbers after the decimal point, `%f` rounds it up to have exactly 6. If fewer than 6 trailing numbers are provided, it appends zeros, for example, `66.00` becomes `66.000000`, which I think is fine?
> [fix] resource_monitor credit quota as float64, not int

- pkg/resources/schema.go
- pkg/resources/schema_test.go
Terraform state refresh was always setting the managed access option to the default, false.
> [fix] schema managed access option

- README.md
- pkg/resources/database_acceptance_test.go
- pkg/resources/stage.go
- pkg/resources/stage_acceptance_test.go
- pkg/resources/stage_test.go
- pkg/resources/warehouse_acceptance_test.go
When I try to create an internal stage, Terraform breaks with an error
trying to convert a NULL value to a string, which is not possible in Go.
When you run SHOW STAGES in internal stages, the "region" and "cloud"
fields are NULL. This pull request fixes that by using *string pointers
in the SHOW STAGE struct.
> [fix] Fix cannot convert NULL to string when creating stage (#129)

- pkg/resources/pipe.go
Is this an acceptable fix for comparing multi-line `copy_statement`s in the pipe resource. Tested it locally in our dev snowflake environment, it seems to not detect changes anymore.
* Potential fix for #180 
[Travis build](https://travis-ci.com/github/henriblancke/terraform-provider-snowflake/builds/162804020)
> [fix] pipe copy statement diff

- pkg/resources/resource.go
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
- pkg/resources/view_test.go
Fix bug where we were breaking queries with '%' in them.
This would make it impossible to have a view query with a '%' and have
the query round-trip back from snowflake. The workaround was to escape
with '%%', but then you have a constant diff in your terraform plan.
Fixes #143
* #143
> [fix] bug with percent signs in queries

- pkg/resources/database.go
- pkg/resources/grant_helpers.go
- pkg/resources/managed_account.go
- pkg/resources/pipe.go
- pkg/resources/resource.go
- pkg/resources/resource_monitor.go
- pkg/resources/role.go
- pkg/resources/role_grants.go
- pkg/resources/schema.go
- pkg/resources/share.go
- pkg/resources/stage.go
- pkg/resources/storage_integration.go
- pkg/resources/user.go
- pkg/resources/view.go
- pkg/resources/warehouse.go
- pkg/snowflake/database.go
- pkg/snowflake/exec.go
- pkg/snowflake/managed_account.go
- pkg/snowflake/pipe.go
- pkg/snowflake/resource_monitor.go
- pkg/snowflake/role.go
- pkg/snowflake/schema.go
- pkg/snowflake/share.go
- pkg/snowflake/stage.go
- pkg/snowflake/storage_integration.go
- pkg/snowflake/user.go
- pkg/snowflake/view.go
- pkg/snowflake/warehouse.go
Scan all queries with sqlx.StructScan in unsafe mode so that we are resilient to snowflake adding new columns.
Because we have been using sql.Row.Scan, which requires that you list variables for each column you want to pull out (in order), if snowflake added a new column to any of our queries, code would break.
* Fixes #161
> [fix] refactor db scanning code to be more resilient

- download.sh
The godownloader generated script wasn't working with the new release structure of this project -adding a _${TAG} to ensure it works with downloading the latest version.
> Fix download.sh to work with new GitHub release tags

- pkg/snowflake/escaping.go
- pkg/snowflake/task.go
- pkg/snowflake/task_test.go
Snowflake doesn't like the sql string returned by terraform because when it contains quotes. It escapes the quotes by default. This PR removes `\` and unescapes the sql.
> [fix] task sql quoting

- pkg/provider/provider.go
- pkg/provider/provider_test.go
Refactor to make it easier to have consistent test results when testing
our DSN generation.
Previously the approach we were using would implicitly read environment
variables, which means that if you had any relevant ones set (like
`SNOWFLAKE_USER`) the test code would use that.
*
> [fix] DSN generation in tests

- .goreleaser.prerelease.yml
- .goreleaser.yml
- Makefile
- README.md
Publish this provider to the terraform registry.
In terraform 0.13 third party providers can be published to the terraform registry. This PR implements the necessary pieces, including signing all releases.
* https://docs.google.com/document/d/1J4p5KFH129wZbSF0XUioDbHSB7uZA-l2o1psLa-3YS4/edit
> publish to terraform registry

- pkg/resources/stage.go
The contents of the credentials field on snowflake_stage resources appear on the command line when running `terraform plan` and `terraform apply`.  terraform cloud or Gitflow based tools such as atlantis will subsequently expose these credentials when threading into github.   This change follows terraform best-practices guide to hide sensitive data.
* https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#using-the-sensitive-flag
> [feature] sensitive flag on stage credentials

- README.md
A step-by-step guide. Hopefully this will improve the frequency of contributions
> README development improvements

- pkg/resources/task_acceptance_test.go
Snowflake appears to have changed something which is now causing this
test to fail. Skipping it for now while I find someone who can address
the problem.
cc @henriblancke  and @chriskuchin  who worked on this originally. Any chance one of you could look at this?
* https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/196
> [fix] skip test broken by snowflake

- pkg/resources/pipe.go
- pkg/resources/pipe_internal_test.go
Fixes issue whereby line `\r\n` endings and trailing `;` are not returned in the same format as originally declared in the result of a `SHOW PIPE` statement.
* Fixes #246
> [fix] issues with \r\n and ; line endings

- pkg/resources/privileges.go
- pkg/resources/schema_grant.go
This PR adds a missing schema grant of "CREATE MASKING POLICY".  
This Snowflake documentation shows this is a valid privilege in the schemaPrivileges section:
https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html#syntax
I've ran the `make test` locally. This privilege is no different than any other schema privileges. 
This should resolve this issue, which I opened: 
https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/256
> [feature] masking policy schema grant

- docs/index.md
Based on https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/master/pkg/provider/provider.go#L29
It seems like accidentally the env var was mentioned as `SNOWFLAKE_PASSWORD` instead of `SNOWFLAKE_USER` for the username
> [docs] correct username env var

- pkg/snowflake/stage.go
- pkg/snowflake/stage_test.go
* [ x] …
* This fix should avoid getting an SQL error when a stage has defined a NULL_IF = [] file format property. The provider now does not run `NULL_IF = []` but it executes `NULL_IF = ()`
> [fix] If NULL_IF list is empty fix it with brackets

- docs/resources/resource_monitor.md
- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_acceptance_test.go
- pkg/resources/resource_monitor_test.go
- pkg/snowflake/resource_monitor.go
- pkg/snowflake/resource_monitor_test.go
Snowflake only accepts credit_quota as an int.  However, the `show resource monitors` command returns it as a float.  This PR converts the float read from Snowflake into an int.  
Fixes https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/145 and https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/109
> [fix] credit quota as float on read, int on write

- pkg/resources/stream_acceptance_test.go
- pkg/resources/table.go
- pkg/resources/table_acceptance_test.go
- pkg/resources/table_test.go
- pkg/snowflake/table.go
- pkg/snowflake/table_test.go
The table.Read functionality wasn't correctly importing all state. For example, we wouldn't set the columns of an imported table. This patch augments the Read function to more fully refresh table state (and therefore the ability to properly import a table).
Note that Snowflake doesn't properly "reflect back" some values. For example, if you create a table with `STRING` as a type Snowflake will silently convert it to a VARCHAR(...) type when you query back the col type.
* [x ] acceptance tests
* [ x] ran in an internal repo to test importing a table (make sure it failed without this patch and then succeed with this patch)
*
> fix:table: Properly read and import table state

- .goreleaser.yml
Trimpath Go flag to builds. This way my local machine paths won't get baked into the binary.
Copy/pasted from https://github.com/goreleaser/goreleaser/blob/master/.goreleaser.yml#L21
* https://github.com/goreleaser/goreleaser/blob/master/.goreleaser.yml
> fix:build: Add trimpath Go flag to build

- .github/workflows/integration.yml
- .github/workflows/ok-to-test.yml
- .github/workflows/unit.yml
- Makefile
**References:**
https://github.com/imjohnbo/ok-to-test
**Method:**
Copied over the `.github/workflows` files and modified to use the preferred method of authentication: 
`Preferred: GitHub App installation access token with contents: write and metadata: read permissions`
We had to follow [these instructions](https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-a-github-app) to create a new Github App for the `chanzuckerberg` organization, not a personal account app. We were able to create and use the `app id` in the app settings and a private key after creating the app. Both are stored in Github secrets now. We changed the githash condition to be [more strict](https://github.com/chanzuckerberg/terraform-provider-snowflake/compare/adoami/ok-to-test?expand=1#diff-82454b2f …
> [feature] ok-to-test allows testing on forked branches with secrets

- .github/workflows/integration.yml
- .github/workflows/unit.yml
`lint-ci` requires a reviewdog token, moving to the workflow with secrets in context
*
> [fix]: CI: Move lint target to integration.yml

- .github/workflows/ok-to-test.yml
See https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs. The slash command dispatch is nicely instrumented with core.debug statements I am hoping to see by enabling this variable.
*
> Temporarily enable GitHub action debug statements for slash command dispatch

- go.sum
- pkg/snowflake/grant.go
- pkg/snowflake/grant_test.go
As discussed in this issue (https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/304), since 10/2020 Snowflake dropped support for OWNERSHIP revoking.
The proposed solution will use CURRENT_ROLE() to return Terraform's role and grant the OWNERSHIP to it. This way we are still able to grant OWNERSHIP from the resource to any other role via Terraform.
> [fix] Change revoke code for OWNERSHIP privilege since it was dropped from Snowflake

- Makefile
These had been disabled due to flakiness. They appear to be fine now, so
re-enabling.
> [fix] run warehouse grant tests

- docs/resources/integration_grant.md
- examples/resources/snowflake_integration_grant/resource.tf
Fix typo of resource name in code example
* https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/integration_grant
* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/375
> [fix] typo snowflake_integration_grant in doc

- .github/workflows/integration.yml
Defaults to head sha which we guarantee is the one being used in the slash command before this.
> Remove checkout for integration to act the same as trusted PR

- README.md
- docs/resources/role_grants.md
- docs/resources/user.md
- examples/resources/snowflake_user/resource.tf
I noticed these minor doc-related issues while configuring our Snowflake with this provider. Thanks for building this out — very much appreciated.
Also noticed that name was included in the `snowflake_role_grants` example, which isn't an attribute of the resource.
> Update version in README and fix typos in docs.

- .github/workflows/integration.yml
forked PRs are building tests off of main exhibit A: https://github.com/chanzuckerberg/terraform-provider-snowflake/runs/1665216382?check_suite_focus=true
Trying to put this back to see what it uses instead.
> Use merge ref for checkout for repository_dispatch

- .github/workflows/integration.yml
This errored https://github.com/chanzuckerberg/terraform-provider-snowflake/runs/1666377496?check_suite_focus=true bc the pull request number didn't exist.
> Need to provide other PR number for forked PRs

- .github/workflows/integration.yml
ok to test would not report job status on failed jobs. change status check conditional to always run (even after failed tests)
*
> [fix] ok-to-test: Report status checks on failed jobs

- docs/resources/view.md
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
- pkg/resources/view_test.go
- pkg/snowflake/view.go
- pkg/snowflake/view_test.go
If I had a view `foo.bar.view` and another view `foo.baz.view`, the provider was not able to distinguish between them. This caused all sort of issues such as modifying the wrong view, reassigning grants, etc.
NOTE: It seems to me that we should require a DB and a SCHEMA to be specified in the resource. The lack of one or the other makes it so that the queries are "context dependent", under-specified, and somewhat dangerous. I decided to make both db and schema required fields and simplify the code accordingly. LMK what your thoughts are.
* https://docs.snowflake.com/en/sql-reference/sql/alter-view.html
* https://docs.snowflake.com/en/sql-reference/sql/show-views.html
> [breaking] Fix to properly distinguish between similarly named views in other databases and schemas

- pkg/resources/account_grant.go
- pkg/resources/privileges.go
These privileges allow non-ACCOUNTADMIN roles to manage shares.
This is a non-functional change, and privileges are not exhaustively tested, so none needed(?)
https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#global-privileges
> [feature] CREATE SHARE, IMPORT SHARE privileges for account grants

- pkg/resources/external_stage_acceptance_test.go
- pkg/resources/internal_stage_acceptance_test.go
- pkg/resources/stage_test.go
When working on this PR: https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/426
I found that external stage and internal stage are slightly different, and should be tested.
Tests fail until the referenced PR is merged.
> Differentiating between external and internal stage in testing

- docs/resources/external_table.md
- examples/resources/snowflake_external_table/import.sh
- examples/resources/snowflake_external_table/resource.tf
document for external table resource is missing in the main branch.
*
> [docs] import and example for external table

- docs/resources/network_policy.md
- examples/resources/snowflake_network_policy/resource.tf
Fix #431 which is the typo in network policy doc.
*
> [doc] Fix typo in network policy document

- pkg/resources/grant_helpers.go
- pkg/resources/share.go
- pkg/resources/share_test.go
- pkg/snowflake/exec.go
- pkg/snowflake/future_grant.go
- pkg/snowflake/future_grant_test.go
- pkg/snowflake/grant.go
- pkg/snowflake/grant_test.go
Snowflake SQL driver does not accept multiple statements like we used to have -- made some tweaks to revoke so that it is a multi statement.
*
> [fix] Generic Grant revoke OWNERSHIP multiple statements not allowed

- go.mod
- go.sum
- pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go
* AWS IAM User ARN is different for each Snowflake account but IAM user ARN is hardcoded in an acceptance test.
* This PR makes the AWS IAM User ARN configurable by environment variable.
* Fix #439
*
> [fix] Verify IAM policy in TestAccSystemGetAWSSNSIAMPolicy_basic

- docs/resources/database_grant.md
- docs/resources/schema_grant.md
- docs/resources/stage_grant.md
- docs/resources/table_grant.md
- docs/resources/warehouse_grant.md
- examples/resources/snowflake_database_grant/import.sh
- examples/resources/snowflake_schema_grant/import.sh
- examples/resources/snowflake_stage_grant/import.sh
- examples/resources/snowflake_table_grant/import.sh
- examples/resources/snowflake_warehouse_grant/import.sh
According to the following code, we must pass 4 or 5 pipe-delimited values in order to use `terraform import`, but the documentation says that you should pass 3 values.
Indeed, `terraform import snowflake_database_grant.xxx 'xxx|||USAGE|false' works correctly, so I fixed the documentation.
https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/a4240bb6bd399141f3614b3a5e1ff54476de70b4/pkg/resources/grant_helpers.go#L114-L116
```
$ terraform import snowflake_database_grant.xxx 'xxx|||USAGE|false'
...
snowflake_database_grant.xxx: Refreshing state... [id=xxx|USAGE|false]
Error: 4 or 5 fields allowed
```
> Fix import format for snowflake_database_grant

- pkg/resources/task.go
*  Hi I am trying to fix the issue documented in https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/474. by filtering out account level params. My first attempt was using env variables, https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/486
`terraform plan`
Output:
```
~ resource "snowflake_task" "retention_task" {
comment            = "deletes tables"
database           = "IDB"
enabled            = false
id                 = "IDB|UTIL|RETENTION_TASK"
name               = "RETENTION_TASK"
schedule           = "USING CRON 0 23 * * * Europe/London"
schema             = "UTIL"
~ session_parameters = {
- "QUOTED_IDENTIFIERS_IGNORE_CASE" = "true" -> null
}
sql_statement      = "CALL retention(false)"
warehouse          = "DEMO_XS_WH"
}
Plan: 0 to add, 1 to …
```
> Filter out account level params

- Makefile
- README.md
Was getting this problem:
```
latestVersionTag "0.23.2"
fileversion "0.23.3"
Error: tag does not match VERSION file
Usage:
bff bump [flags]
Flags:
-h, --help   help for bump
tag does not match VERSION file
```
Running `make setup` fixed it, so adding it as substep to release.
> Add make setup step to release instructions

- pkg/resources/role_grants.go
- pkg/resources/role_grants_acceptance_test.go
The current behavior is to query Snowflake for all grants to the specified role when a role grant is read, updated, or deleted. This means the update or delete to applies to _all_ grants to the specified role rather than just the grants that are part of the terraform resource. This causes issues when there are multiple resources handling grants to the same role, as well as when there is a role hierarchy (see issues linked below for more info).
These changes modify the role grant read to look at only the grants that are part of the specified terraform resource. This allows for more flexible use of terraform modules and eliminates issues with role hierarchies.
[189](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/189) …
> role_grants: update read to only use grants specific to the tf resource

- pkg/resources/warehouse.go
The warehouse auto-suspend setting can actually be an arbitrary integer (you can test this with `alter warehouse reporting set auto_suspend = <x>`). The current check for 60 seconds imposes an arbitrary restriction on the provider that's not present in the service.
Negative values are just interpreted as "never". Based on the intent of the provider surface it looks like the "never" case should be handled by removing the auto-suspend setting, so a 1-second minimum seemed reasonable.
> Lower limit on warehouse auto-suspend setting

- docs/data-sources/system_get_privatelink_config.md
- examples/data-sources/snowflake_system_get_privatelink_config/data-source.tf
The current example has mistakes, whereby the `snowflake_` prefix was missed in the documentation.
* N/A
* N/A
> Corrected mistakes within the snowflake_system_get_privatelink_config documentation example

- docs/resources/role_grants.md
- examples/resources/snowflake_role_grants/resource.tf
`name` is not a field on the snowflake_role_grants resource making the example invalid if copied exactly.
This is just an example change and does not not currently have any tests other than manually checking the terraform.
> Remove snowflake_role_grants name example

- pkg/resources/privileges.go
- pkg/resources/schema_grant.go
Addresses: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/579
Not adding `CREATE DIRECTORY TABLE` as it is not listed here: https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html and not well documented.
*
> feat: Add CREATE ROW ACCESS POLICY to schema grant priv list

- docs/resources/table.md
- examples/resources/snowflake_table/resource.tf
The resource documentation for [snowflake_table](https://registry.terraform.io/providers/rxrevu/snowflake/latest/docs/resources/table) includes the `owner` attribute in its example code in a way that makes it seem like the attribute is writable. However, the `owner` attribute is read-only, and its value is assigned at resource creation.
This pull request removes the `owner` attribute from the example code.
> DOCFIX: Remove misleading attribute from table doc

- docs/resources/account_grant.md
- examples/resources/snowflake_account_grant/import.sh
Same problem as #429.
The argument of `grantIDFromString` named `stringID` expects 4 or 5 fields delimitered by "|".
> docs: fix import format for snowflake_account_grant

- docs/resources/notification_integration.md
- go.sum
- pkg/resources/notification_integration.go
- pkg/resources/notification_integration_acceptance_test.go
- pkg/resources/notification_integration_test.go
Allow Notification Integration to work with GCP Pubsub
> feat: Add support for GCP notification integration

- pkg/resources/external_table.go
- pkg/snowflake/external_table.go
This PR does the following:
- Fixed partition_by from set to interface.
- Renamed from partiion to partition.
- Changed the length condition of the partition from >1 to >0.
Adresses: #448
> fix: partition_by error in external table

- examples/data-sources/snowflake_materialized_views/data-source.tf
- examples/data-sources/snowflake_schemas/data-source.tf
- examples/data-sources/snowflake_tables/data-source.tf
- examples/data-sources/snowflake_views/data-source.tf
- pkg/datasources/materialized_views.go
- pkg/datasources/materialized_views_acceptance_test.go
- pkg/datasources/schemas.go
- pkg/datasources/schemas_acceptance_test.go
- pkg/datasources/tables.go
- pkg/datasources/tables_acceptance_test.go
- pkg/datasources/views.go
- pkg/datasources/views_acceptance_test.go
- pkg/provider/provider.go
- pkg/snowflake/materialized_view.go
- pkg/snowflake/schema.go
- pkg/snowflake/table.go
- pkg/snowflake/view.go
Implemented following DataSources (which can be later on used to iterate over other resources):
- Schemas
- Tables
- Views
- Materialized Views
> feat: Implemented Schemas, Tables and Views Datasources

- docs/resources/warehouse.md
- pkg/resources/warehouse.go
Snowflake on AWS supports X5Large and X6Large warehouses, this modifies the validation func to allow these and the synonyms to be supplied
* https://docs.snowflake.com/en/sql-reference/sql/create-warehouse.html#optional-properties-objectproperties
> feat: Added support for X5LARGE and X6LARGE warehouses

- pkg/resources/share.go
"Error renaming this does not seem to be used USAGE to foobar"
looks like shares can't be renamed
> fix: snowflake_share can't be renamed, ForceNew on name changes

- docs/data-sources/system_get_privatelink_config.md
- examples/data-sources/snowflake_system_get_privatelink_config/data-source.tf
- pkg/datasources/system_get_privatelink_config.go
- pkg/datasources/system_get_privatelink_config_acceptance_test.go
- pkg/snowflake/system_get_privatelink_config.go
- pkg/snowflake/system_get_privatelink_config_test.go
Fix typo of `OSCP` and `oscp` references to `OCSP` and `ocsp` respectively.
> fix: OSCP -> OCSP misspelling

- pkg/resources/privileges.go
- pkg/resources/schema_grant.go
- pkg/resources/schema_grant_test.go
This PR addresses #734 and adds CREATE TAG as a valid privilege to schema grants.
Added CREATE TAG to the schema grant test
#734
> feat: adding support for create tag to schema grants

- pkg/resources/user.go
- pkg/resources/user_public_keys.go
- pkg/resources/user_public_keys_test.go
- pkg/resources/user_test.go
- pkg/snowflake/user.go
- pkg/snowflake/user_test.go
This PR is supposed to solve #677 by using `DESCRIBE USER ...` instead of `SHOW USERS LIKE ...` in the `ReadUser` and `UserExists` functions.
While `SHOW USERS ...` requires the `MANAGE_GRANTS` global privilege, which usually requires the `SECURITYADMIN` role, the `DESCRIBE USER ...` does not.
* https://docs.snowflake.com/en/sql-reference/sql/show-users.html#usage-notes
* https://docs.snowflake.com/en/sql-reference/sql/desc-user.html#usage-notes
> fix: use "DESCRIBE USER" in ReadUser, UserExists

- docs/resources/notification_integration.md
- examples/resources/snowflake_notification_integration/resource.tf
- pkg/resources/notification_integration.go
- pkg/resources/notification_integration_test.go
- pkg/snowflake/notification_integration_test.go
I am adding AWS SNS notification_provider support for error notifications for Snowpipe. The current Snowflake provider version supports this feature; however, it supports an outdated version of it that was using SQS. My goal is to adapt the current provider to support SNS instead of SQS and thus stay up to date with the Snowflake feature. The documentation link for the new Snowflake feature could be found [here](https://docs.snowflake.com/en/LIMITEDACCESS/data-load-snowpipe-notifications.html) 
Please keep some things in mind:
- This feature is currently in private preview and must be enabled on the account level
- I am not very experienced in Go and I would appreciate some guidance
I took reference of PR [[595](https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/595)] …
> fix: Add AWS_SNS notification_provider support for error notifications for Snowpipe.

- docs/resources/notification_integration.md
- pkg/resources/notification_integration.go
Edge case when changing the type of notification integration (e.g. from `AWS_SQS` to `AWS_SNS`) with the same name, Terraform attempts to `ALTER` it, which results in an error because required fields are different depending on the type.
This change forces recreation when any of the integration types change.
* [ALTER NOTIFICATION INTEGRATION](https://docs.snowflake.com/en/sql-reference/sql/alter-notification-integration.html)
> fix: Recreate notification integration when type changes

- pkg/resources/database.go
- pkg/resources/external_table.go
- pkg/resources/resource.go
- pkg/resources/tag.go
- pkg/snowflake/external_table.go
- pkg/snowflake/external_table_test.go
- pkg/snowflake/generic.go
tagging for database, external_table and schema were not working. this is caused by two separate problems 1) the command for updating tags never runs and 2) the command itself was incorrect. This PR aims to fix both of these issues. In addition, tags were previously marked as force new, when they really shouldn't be. It would be very bad to accidentally delete a database just because the tags are getting changed, for example. A consequence of removing force new means that we now have to implement update command for external_table, which uses tags, but does not have its own update command. 
*
> fix: tagging for db, external_table, schema

- pkg/resources/pipe.go
Fixes #816 
As far as I can see `ALTER PIPE` doesn't allow to change the SNS topic for an existing snowpipe.
Thus I added `ForceNew` parameter in case someone changes the SNS topic for a snowpipe via TF.
Really small change... unfortunately don't have a test setup for this provider available and thus it is untested. Would love if someone can have a short look there and verify it's working...
* https://docs.snowflake.com/en/sql-reference/sql/alter-pipe.html - can't find any details that the SNS topic can be changed
> fix: changing sns topic for pipe resource

- pkg/resources/materialized_view_grant.go
Per Snowflake Access Control Privileges documentation, Materialized view grant should support `REFERENCES`  privilege. 
* [view-privileges](https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#view-privileges)
* #738
> fix: Enable REFERENCES privilege for materialized view grants

- pkg/resources/saml_integration.go
I encountered the following crash with the latest provider version:
```
panic: interface conversion: interface {} is bool, not string
goroutine 99 [running]:
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateSAMLIntegration(0x0, {0x10d01e0, 0xc0004b69c0})
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/saml_integration.go:180 +0xbf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xf98540, {0x12d9918, 0xc00002c1c0}, 0x2, {0x10d01e0, 0xc0004b69c0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:318 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000522ee0, {0x12d9918, 0xc00002c1c0}, 0xc00035fc70, 0xc0001f8f00, {0x10d01e0, 0xc0004b69c0}) …
```
> fix: make saml2_enable_sp_initiated bool throughout

- pkg/resources/pipe.go
- pkg/resources/pipe_test.go
- pkg/resources/task.go
- pkg/resources/task_test.go
- pkg/snowflake/pipe.go
- pkg/snowflake/task.go
Fixes problem introduced in #830.
Tested the latest release v0.25.35 and discovered that `DESCRIBE TASK` returns a string "null", rather than an actual NULL. Frustrating, but there seems to be a similar issue with `DESCRIBE USER` handled in a similar way.
Those with task error notifications preview enabled and any tasks without `error_notification` set will see this:
```
~ resource "snowflake_task" "task" {
- error_integration  = "null" -> null
id                 = "DB|SCHEMA|TASK"
name               = "TASK"
}
```
Worse still, when it tries to update the `error_notification` to empty, it produced the following invalid SQL:
```sql
ALTER TASK "DB"."SCHEMA"."TASK" SET ERROR_INTEGRATION = 
```
To fix this, I implemented proper unsetting of that parameter.
Both problems have been around in …
> fix: Handling of task error_integration nulls

- .goreleaser.yml
Fixing: `   ⨯ release failed after 0.07s error=template: tmpl:1:181: executing "tmpl" at <.Env.DIRTY>: map has no entry for key "DIRTY"`
> fix: Update goreleaser env Dirty to false

- .goreleaser.yml
- Makefile
Fixing: 
```
⨯ release failed after 651.76s error=sign failed: terraform-provider-snowflake_0.26.2_SHA256SUMS: template: tmpl:1:6: executing "tmpl" at <.Env.KEYBASE_KEY_ID>: map has no entry for key "KEYBASE_KEY_ID"
```
> fix: Remove keybase since moving to github actions

- docs/resources/notification_integration.md
- pkg/resources/notification_integration.go
This updates the "notification integration" resource to expose the GCP_PUBSUB_SERVICE_ACCOUNT generated when using GCP_PUBSUB provider as described in https://docs.snowflake.com/en/user-guide/data-load-snowpipe-auto-gcs.html#step-2-grant-snowflake-access-to-the-pub-sub-subscription.
The field is exposed as "gcp_pubsub_service_account".
This hasn't been tested yet using the acceptance framework.
> feat: Expose GCP_PUBSUB_SERVICE_ACCOUNT attribute in notification integration

- docs/resources/stage.md
- pkg/resources/stage.go
- pkg/resources/stage_test.go
- pkg/snowflake/stage.go
- pkg/snowflake/stage_test.go
This adds passing the `DIRECTORY` option of `CREATE STAGE` (as `directory`) in the stage resource.
This is only supported on create as the ALTER capabilities don't really align. As a result this PR suggests to ForceNew on `directory` change.
This is currently not tested using acceptance tests
> feat: Support DIRECTORY option on stage create

- go.mod
- go.sum
This PR fixes an issue with the current version of go-ieproxy. We updated all dependencies in the latest release, but go-ieproxy seems to have an issue (https://github.com/mattn/go-ieproxy/issues/30). Until they resolve that, we have excluded those versions from our mod file.
* Run tests
* Locally, I ran `goreleaser build` to make sure the errors were resolved.
* https://github.com/mattn/go-ieproxy/issues/30
* https://github.com/chanzuckerberg/terraform-provider-snowflake/runs/5486463096?check_suite_focus=true
> fix: issue with ie-proxy

- .goreleaser.yml
adding: https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.goreleaser.yml#L53-L58
> fix: Add release step in goreleaser

- Makefile
- pkg/resources/grant_helpers.go
- pkg/resources/grant_helpers_internal_test.go
Allowing for legacy length/structure of GrantIDs to be used with the new multiple grants functionality. Role names in GrantIDs are not used for anything but uniqueness of the IDs. 
IDs will be created with the new structure whenever resources are dropped and recreated, and it will be invisible to the end user.
* https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/824
> fix: Allow legacy version of GrantIDs to be used with new grant functionality

- pkg/resources/warehouse_test.go
- pkg/snowflake/warehouse.go
* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/862
* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/844
* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/791
* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/774
> fix: Make ReadWarehouse compatible with quoted resource identifiers

- pkg/snowflake/validation.go
- pkg/snowflake/validation_test.go
Has been blocked by the same issues as others reported: 
[issue-846](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/846)
[issue-862](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/862)
For context, Snowflake object identifier can use special characters like `-` as long as it's [double quoted](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#double-quoted-identifiers). However currently the validation rule only allow characters used in [unquoted Snowflake object identifier](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#unquoted-identifiers).
As mentioned in the issue tickets, currently creating a role with `-` is allowed by the provider, but granting role with `-` to user or other roles is blocked by …
> fix: update snowflake identifier validation condition

- docs/resources/stage_grant.md
- pkg/resources/stage_grant.go
- pkg/resources/stage_grant_test.go
Stages cannot be shared outside the account. So remove this feature.
* https://docs.snowflake.com/en/user-guide/data-sharing-intro.html
> fix: remove share feature from stage because it isn't supported

- pkg/resources/external_oauth_integration.go
Fixed Any Role Values External OAUTH Integration. There were spaces in the allowed values
See #879 
*
> fix: Fixed Any Role Values External OAUTH Integration

- pkg/resources/table.go
- pkg/resources/table_acceptance_test.go
- pkg/snowflake/table.go
- pkg/snowflake/table_test.go
Allow changing the name of Snowflake tables without destroying then recreating the table.
- Feature Request: #891 
- [Snowflake Documentation for Renaming a Table](https://docs.snowflake.com/en/sql-reference/sql/alter-table.html#syntax)
> feat: Allow in-place renaming of Snowflake tables

- docs/index.md
- examples/provider/provider.tf
- pkg/datasources/procedures_acceptance_test.go
- pkg/provider/provider.go
- templates/index.md.tmpl
Added missing `host` provider documentation. But then realized that the provider.go schema was missing descriptions that `terraform-plugin-docs` is capable of auto generating for us. So I went ahead and fixed that too.
* #959
> docs: Update host provider docs

- pkg/resources/schema.go
- pkg/resources/schema_acceptance_test.go
- pkg/snowflake/schema.go
Similar to PR https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/904, allow changing the name of Snowflake schemas without destroying then recreating the schema.
<details>
<summary>Acceptance tests logs</summary>
```
❯ make test-acceptance
goimports -w -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./dist/*")
go mod tidy -compat=1.17
SKIP_MANAGED_ACCOUNT_TEST=1 TF_ACC=1 go test -v -coverprofile=coverage.txt -covermode=atomic  ./...
?   	github.com/chanzuckerberg/terraform-provider-snowflake	[no test files]
=== RUN   TestAccCurrentAccount
=== PAUSE TestAccCurrentAccount
=== RUN   TestDatabase
=== PAUSE TestDatabase
=== RUN   TestDatabases
=== PAUSE TestDatabases
=== RUN   TestAccExternalFunctions
=== PAUSE TestAccExternalFunctions
=== RUN …
```
> feat: allow in-place renaming of Snowflake schemas

- .gitignore
- go.mod
- go.sum
getting error message with mattn during release
```
⨯ release failed after 14.48s error=failed to build for darwin_arm64: exit status 2: # github.com/mattn/go-ieproxy
../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.4/ieproxy.go:36:9: undefined: getConf
../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.4/ieproxy.go:41:9: undefined: reloadConf
../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.4/ieproxy.go:48:2: undefined: overrideEnvWithStaticProxy
../../../../pkg/mod/github.com/mattn/go-ieproxy@v0.0.4/ieproxy.go:53:12: psc.findProxyForURL undefined (type *ProxyScriptConf has no field or method findProxyForURL, but does have FindProxyForURL)
```
downgrading to version 0.1 which seems to work as per: https://github.com/google/go-cloud/issues/3114
*
> fix: downgrade mattn/go-ieproxy

- Makefile
- pkg/datasources/procedures_acceptance_test.go
- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
makefile failing due to "VERSION" file not found. This wasn't really being used for much anyways so just remove reference to "VERSION"
Also updating goimport install to:
```
go install golang.org/x/tools/cmd/goimports@latest
```
Since the `go get` method has been deprecated. 
*
> fix: makefile remove outdated version reference

- docs/resources/stream.md
- examples/resources/snowflake_stream/resource.tf
- pkg/resources/external_table_acceptance_test.go
- pkg/resources/stream.go
- pkg/resources/stream_acceptance_test.go
- pkg/resources/stream_test.go
- pkg/snowflake/stream.go
- pkg/snowflake/stream_test.go
Allow the creation of `STREAMS` on `EXTERNAL TABLE`s.
* Initial version of this PR taken as-is from #661
* [docs.snowflake.com/en/sql-reference/sql/create-stream.html#creating-an-insert-only-stream-on-an-external-table](https://docs.snowflake.com/en/sql-reference/sql/create-stream.html#creating-an-insert-only-stream-on-an-external-table)
> feat: Add support for creation of streams on external tables

- pkg/resources/stream.go
- pkg/resources/stream_acceptance_test.go
- pkg/resources/stream_test.go
- pkg/snowflake/stream.go
This change removes the `append_only`/`insert_only` fields from the Stream row struct, as they are not returned neither by `SHOW STREAMS` nor `DESCRIBE STREAM`.
To find if an existing stream is `INSERT_ONLY`, it now checks the `mode` field, as it has been already done for the `APPEND_ONLY` mode.
> fix: Correctly read INSERT_ONLY mode for streams

- pkg/resources/function.go
As found in Snowflake-Labs/terraform-provider-snowflake#1048, defining a SQL UDF explicitly with `language = "SQL"` is disallowed. When omitted, it works.
I would propose allowing to explicitly set language = "SQL", too (when executing in Snowflake, it works by omitting or defining `LANGUAGE SQL` either way).
* executing `CREATE OR REPLACE FUNCTION ... LANGUAGE SQL` works
* fixes #1048
> fix: snowflake_function - Allow defining language = SQL

- pkg/resources/warehouse.go
Supports custom warehouse sizes as Snowflake customers are now able to submit support tickets to raise their limit beyond `10`.
```terraform
resource "snowflake_warehouse" "old" {
name              = "test_old"
comment           = "foo"
warehouse_size    = "small"
max_cluster_count = 10
}
resource "snowflake_warehouse" "new" {
name              = "test_new"
comment           = "foo"
warehouse_size    = "small"
max_cluster_count = 20
}
```
* Nothing to link to, unfortunately. Informed by our Snowflake representative that this is now a _soft_ limit.
> feat: Support custom warehouse sizes

- pkg/resources/role_grants.go
- pkg/resources/role_ownership_grant.go
- pkg/resources/user_ownership_grant.go
- pkg/snowflake/validation.go
- pkg/snowflake/validation_test.go
Adding fix for issue: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1054
Created a new struct parameter for adding characters to exclude from the validation check.
role_ownership_grants is now able to take in periods or "." in the role_name parameter
tested locally and was able to resolve the error for ` Error: '.' is not a valid identifier character.`
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1054
*
> fix: allow custom characters to be ignored from validation

- pkg/datasources/file_formats_acceptance_test.go
- pkg/resources/file_format_acceptance_test.go
- pkg/resources/share.go
- pkg/resources/share_test.go
- pkg/resources/task.go
- pkg/snowflake/task.go
2022_03 bundle (enabled in 6.21 release) changes the following behavior:
* Share `NAME` column in accounts using the new org naming is returned as `ORG.ACCOUNT.SHARE`, instead of the old `ACCOUNT.SHARE`
* Task `PREDECESSORS` column is now always returned as a JSON array (even when it's empty)
* File format `VALIDATE_UTF8` option is obsoleted, attempting to set it to false now fails
Note that the existing task implementation only handles one task root and this change continues that. While you can only specify one `AFTER` in `CREATE TASK`, you can add more with `ALTER TASK ... ADD AFTER`. Supporting this would require a breaking change to make the `after` parameter a list and handle state for multiple roots, this should be done in a separate contribution.
* [6.21 Release …
> fix: Handling 2022_03 breaking changes

- pkg/resources/warehouse.go
- pkg/snowflake/warehouse.go
Fixes 
```
sql: Scan error on column index 8, name "auto_suspend": converting NULL to int64 is unsupported
```
by using `sql.NullInt64` instead of `int64`
> fix: warehouse import when auto_suspend is set to null

- docs/resources/share.md
- examples/resources/snowflake_share/resource.tf
- pkg/resources/share.go
- pkg/resources/share_test.go
- pkg/validation/validation.go
- pkg/validation/validation_test.go
fix: Updating shares to disallow account locators
- make docs was run
- unit tests were added for the validation function 
- unit tests successful `go test`
*
> fix: Updating shares to disallow account locators

- pkg/resources/database.go
- pkg/resources/database_test.go
- pkg/snowflake/database.go
- pkg/snowflake/database_test.go
Removing force new and adding update for data base replication configuration
*
> fix: Removing force new and adding update for data base replication config

- docs/resources/pipe_grant.md
- examples/resources/snowflake_pipe_grant/resource.tf
* https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/pipe_grant
* This PR fix https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/985
* current `pipe_grant` document contains `sequence_name = "sequence"` but it must be like `pipe_name = "pipe"
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/985
> docs: Fix pipe_grant doc

- docs/resources/stream.md
- pkg/resources/external_table_internal_test.go
- pkg/resources/stream.go
- pkg/resources/stream_acceptance_test.go
- pkg/resources/stream_internal_test.go
- pkg/resources/stream_test.go
- pkg/snowflake/stream.go
Allow streams on views (rather than tables), now that it's in public preview.
* [CREATE STREAM](https://docs.snowflake.com/en/sql-reference/sql/create-stream.html)
> feat: Streams on views

- README.md
- main.go
Fix for Snowflake-Labs#1144
Adding the `-debug` flag to enable starting the provider in debug mode according to https://www.terraform.io/plugin/debugging#debugger-based-debugging
Specifying the `ProviderAddr` was required to let the provider print the proper command to set the `TF_REATTACH_PROVIDERS` environment variable once theprovider is started in debug mode. If not specified, the output will default to provider which will print a wrong command to the user. With this wrong command the debug session will not be established between the provider and the Terraform applicaiton.
- Existing unit tests have been run.
- Manual testing has been performed with the following steps on Windows with VS Code
1. Launch the Snowflake Provider in VS Code debugger with the -debug argument. The process …
> feat: Adding support for debugger-based debugging.

- .github/workflows/team-slack-bot.yml
- docs/resources/file_format.md
- pkg/datasources/file_formats_acceptance_test.go
- pkg/resources/file_format.go
- pkg/resources/file_format_acceptance_test.go
- pkg/resources/file_format_test.go
- pkg/snowflake/file_format.go
- pkg/snowflake/file_format_test.go
Remove validate_utf8 parameter from file_format due to obsoletion from Snowflake
* #1147
> fix: Remove validate_utf8 parameter from file_format

- docs/resources/pipe.md
Fix doc #793 
N/A
#793 
* `owner` is Read-Only. So I think that `owner` should not defined in `snowflake_pipe` resource.
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/pipe.go
> fix: doc of snowflake_pipe.

- pkg/resources/role_grants.go
This is to fix #889 by checking a Snowflake SQL error code and printing a warning instead of failing in case of non-existing user.
* [ x] acceptance tests
*
> fix: Deleting a snowflake_user and their associated snowlfake_role_grant causes an error

- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/unit.yml
- Makefile
- go.mod
Bump go version from 1.17 to 1.19
Related to https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1117 .
> chore: bump go version from 1.17 to 1.19

- docs/resources/database.md
- pkg/resources/database.go
- pkg/resources/database_test.go
- pkg/resources/share.go
- pkg/snowflake/database.go
- pkg/snowflake/database_test.go
This PR adds support for transient databases (closes [#1152](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1152)). 
It was a bit tricky to add this functionality with the current database implementation so I've slightly refactored it to an iterative approach, following how it's done for the [schema resource](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/schema.go). Hopefully it will make it easier to implement other functionalities.
I only modified the code for database and database clone, so database from share and database from replication are still using the old implementation.
I've added some extra tests and ran the acceptance tests using a trial snowflake account as suggested in the readme.
Also installed the provider …
> feat: transient database

- docs/resources/database.md
- examples/resources/snowflake_database/resource.tf
- pkg/resources/database.go
- pkg/resources/file_format_test.go
- pkg/snowflake/database.go
- pkg/snowflake/database_test.go
Fix setting comment on databases `from_share` creation, it is currently only applied on subsequent updates.
Also make examples in docs more illustrative of using fully-qualified provider name.
* Raised and discussed in #1107
* Partially inspired by #1114
> fix: Database from share comment on create and docs

- pkg/resources/procedure.go
- pkg/resources/procedure_test.go
Snowflake returns `return_type` `table()` as `table ()`. The provider regex doesn't match the space and caused the create and import operations to fail. As part of this PR the space matching is fixed.
I've added the required specific test case in the test suite.
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1050
> fix: add support in procedure for return type table()

- .github/workflows/integration.yml
- Makefile
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- pkg/resources/database_acceptance_test.go
- pkg/resources/database_test.go
- pkg/resources/role_acceptance_test.go
- pkg/resources/role_grants_acceptance_test.go
- pkg/resources/role_ownership_grant_acceptance_test.go
- pkg/resources/snowflake_sweeper_test.go
- pkg/resources/user_acceptance_test.go
- pkg/resources/user_ownership_grant_acceptance_test.go
- pkg/resources/user_public_keys_acceptance_test.go
- pkg/resources/warehouse_acceptance_test.go
- pkg/resources/warehouse_test.go
- pkg/snowflake/role.go
This change adds sweepers to cleanup resources that sometimes get orphaned in test account. Including:
- warehouses
- databases
- users
- roles
every other resource will automatically be removed if these are deleted
*
> fix: add sweepers

- docs/resources/external_table.md
- examples/resources/snowflake_external_table/resource.tf
- pkg/resources/external_table_test.go
- pkg/snowflake/external_table.go
- pkg/snowflake/external_table_test.go
Common use of `FILE_FORMAT` within `CREATE EXTERNAL TABLE` includes specifying
a previously created format name (`FORMAT_NAME = 'NAME'`) or the various
type options (`TYPE=CSV FIELD_DELIMITER='|'`).
Both of these require defining string literals with the single quote
character (`'`) that should not be escaped (`\'`).
This change removes the escaping of single quotes performed for the
`file_format` values to allow them to be specified without failing
the query compilation.
Some examples have also been added to the documentation
to make it easier to understand how values for file_format
need to be passed for external tables.
* Fixes #1046
* Snowflake Docs: [CREATE EXTERNAL TABLE](https://docs.snowflake.com/en/sql-reference/sql/create-external-table.html)
> fix: Pass file_format values as-is in external table configuration

- pkg/resources/external_table.go
- pkg/resources/stage.go
Fixes issue when stage is deleted out of band. Previously error would get:
```
Error: 002003 (02000): SQL compilation error:
│ Stage '"test"."test".EXAMPLE_STAGE' does not exist or not authorized.
```
Now correctly realizes that the resources has been deleted and opts to create it again.
*
> fix: remove stage from statefile if not found

- pkg/resources/storage_integration.go
Creating storage integration using snowflake TF provider for for fedramp high aws gov account  is not supported. When creating storage integration for fedramp gov account in asw the  “STORAGE_PROVIDER“ input needs to be “S3gov”. The current version snowflake TF provider only supports [S3,AZURE,GCP]
Creating API Integration using the provider  for for fedramp high aws gov account  is not supported. When creating API  ntegration for fedramp gov account in AWS the input for “api_provider” need to be “aws_gov_api_gateway“. 
*
> fix: storage integration for S3gov

- pkg/resources/tag_masking_policy_association.go
Adding error handling to two function calls in tag_masking_policy_association.go to fix lint popping up in every PR.
*
> fix: Add error handling to tag_masking_policy_association.go to fix lint

- pkg/resources/grant_helpers.go
seeing this as of 0.44
```
15:19:20  │ Error: Provider produced inconsistent result after apply
15:19:20  │ 
15:19:20  │ When applying changes to
15:19:20  │ module.site_core_schemas["**_QA_MILESTONE-TOKENIZED_DATA"].snowflake_schema_grant.dbo_grant,
15:19:20  │ provider "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]"
15:19:20  │ produced an unexpected new value: Root resource was present, but now
15:19:20  │ absent.
15:19:20  │ 
15:19:20  │ This is a bug in the provider, which should be reported in the provider's
```
problem identified to be with merged PR #1154
reverting changes.
*
> fix: revert grant helpers change

- pkg/resources/database_grant.go
- pkg/resources/external_table_grant.go
- pkg/resources/file_format_grant.go
- pkg/resources/function_grant.go
- pkg/resources/integration_grant.go
- pkg/resources/masking_policy_grant.go
- pkg/resources/materialized_view_grant.go
- pkg/resources/pipe_grant.go
- pkg/resources/procedure_grant.go
- pkg/resources/resource_monitor_grant.go
- pkg/resources/row_access_policy_grant.go
- pkg/resources/sequence_grant.go
- pkg/resources/stage_grant.go
- pkg/resources/stream_grant.go
- pkg/resources/task_grant.go
Added missing update function on resource grants and removed ForceNew from Shares + Roles. This is added to mitigate the current side effects of ForceNew when you add a Share or Role to an existing Grant. Currently existings grants are revoked and then recreated when you add a share or role to a existing grant that has no implementation of the update function and has ForceNew set to true. This causes current queries / users sessions that uses the existing grants to fail because the existing grants where revoked to be recreated a couple of seconds later. This feature makes it possible to only apply the difference. 
This has already been done for a couple of resource grants and works properly.
> feat: Added Missing Grant Updates + Removed ForceNew

- pkg/resources/user_ownership_grant.go
Make `user_ownership_grant` resource schema validation consistent with upstream resources schemas - [user.name](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/da886d4e05f7bb9443168f0fa04b8b397a1db5c7/pkg/resources/user.go#L36) and [role.name](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/da886d4e05f7bb9443168f0fa04b8b397a1db5c7/pkg/resources/role.go#L17) 
Also per https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#double-quoted-identifiers user name could be anything. And it is double-quoted as per https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/da886d4e05f7bb9443168f0fa04b8b397a1db5c7/pkg/snowflake/user_ownership_grant.go#L36
* Fixes https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1184
> fix: Update 'user_ownership_grant' schema validation

- pkg/resources/function.go
The snowflake describe function outputs the python packages from a function as a list of strings like `['pytz','pandas']`. The resource was reading this in as one item instead of two. This would result in terraform detecting changes when there actually were no changes.
Something like:
```
-"'pytz','pandas'",
+"pytz",
+"pandas",
```
Corrected the split by removing a space and removed single quotes from the string values.
Verified this was working as expected in my fork.
> fix: function resource - python packages

- pkg/resources/database_grant_acceptance_test.go
- pkg/resources/external_table_grant_acceptance_test.go
- pkg/resources/external_table_internal_test.go
- pkg/resources/file_format_grant_acceptance_test.go
- pkg/resources/function_grant_acceptance_test.go
- pkg/resources/function_test.go
- pkg/resources/helpers_test.go
- pkg/resources/materialized_view_grant_acceptance_test.go
- pkg/resources/procedure_grant_acceptance_test.go
- pkg/resources/procedure_test.go
- pkg/resources/role_grants_acceptance_test.go
- pkg/resources/sequence_grant_acceptance_test.go
- pkg/resources/stage_grant_acceptance_test.go
- pkg/resources/stream_grant_acceptance_test.go
- pkg/resources/view_grant_acceptance_test.go
- pkg/testhelpers/fixtures.go
- pkg/testhelpers/helpers.go
This PR adds `t.Helper()` to test helper functions.
> fix: missing `t.Helper()` for thelper function

- docs/resources/table_constraint.md
- pkg/provider/provider.go
- pkg/resources/function.go
- pkg/resources/integration_grant_test.go
- pkg/resources/pipe.go
- pkg/resources/procedure.go
- pkg/resources/table_constraint.go
- pkg/resources/task_acceptance_test.go
- pkg/resources/view.go
- pkg/snowflake/resource_monitor.go
- pkg/snowflake/storage_integration.go
- pkg/snowflake/table.go
Since I found some misspell in this repo, this PR corrects them.
> fix: misspelling

- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
- pkg/resources/procedure_test.go
fixes a problem with stored procedures that prevented INTEGER from being set as a return type. Internally it was being converted to NUMBER(38,0). so now using a diffsupress function to ignore the difference for equivalents when being read.
> feat: integer return type for procedure

- pkg/resources/sequence_grant.go
- pkg/resources/stage_grant.go
- pkg/resources/stream_grant.go
- pkg/resources/task_grant.go
Fixed failing updates where on_future is true. This Fix includes forgotten future switches in the update.
*  #1228
> fix: Fixed Grants Resource Update With Futures

- .github/workflows/team-jira-issues.yml
- examples/resources/snowflake_task/resource.tf
- pkg/resources/task.go
- pkg/snowflake/task.go
- pkg/snowflake/task_test.go
Added ALLOW_OVERLAPPING_EXECUTION option to the task resource
test included
https://docs.snowflake.com/en/sql-reference/sql/create-task.html#optional-parameters
> feat: task with allow_overlapping_execution option

- .github/dependabot.yml
Signed-off-by: Kevin Neville <kevin@neville.se>
See warnings in https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/3361622276. I believe this is due to the old version of the actions. This PR makes sure we get automated PRs for these actions.
This should be merged after my other PR, https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1316, that first updates all the versions and addresses breaking changes to one of the actions.
> feat: weekly check of github action versions

- docs/resources/resource_monitor.md
- examples/resources/snowflake_resource_monitor/resource.tf
- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_acceptance_test.go
- pkg/resources/resource_monitor_test.go
- pkg/snowflake/resource_monitor.go
- pkg/snowflake/resource_monitor_test.go
This PR adds support for managing the `notify_users` attribute on resource monitors via the `snowflake_resource_monitor` Resource. It does not include any changes to the `snowflake_resource_monitors` Data Source.
All new and existing tests pass, though one new test is a bit special and worth calling out explicitly.
The new test in `pkg/resources/resource_monitor_acceptance_test.go` is particularly tricky, as the users listed must have a verified email address. As far as I know, this verification process may only be completed manually via the Snowflake interface. To circumvent this, that test depends on a new `RESOURCE_MONITOR_NOTIFY_USERS_TEST` environment variable. If the variable is unset, or set to the empty string, the test will be skipped (similar to the `SKIP_*` variable for many …
> feat: add support for `notify_users` to `snowflake_resource_monitor` resource

- .golangci.yml
- pkg/provider/provider_test.go
This PR adds a new linter called `unconvert` to remove unnecessary type conversions.
> fix(ci): remove unnecessary type conversions by adding lint `unconvert`

- pkg/datasources/helpers_test.go
- pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go
- pkg/datasources/warehouses_acceptance_test.go
This PR fixes tests in datasources.
I don't understand why the acceptance tests for creating warehouse are commented out, and I suspect there is a cause  for this issue https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1343 around here .
> fix: test modules in acceptance test for warehouse

- .golangci.yml
This PR adds new linters `goimports` and `makezero`. The current code meets the condition to pass these linters so there is no change here.
In the future, I will try to add more linters to maintain the quality of codes👍
> feat(ci): add goimports and makezero

- .golangci.yml
- pkg/resources/resource_monitor.go
- pkg/resources/table_constraint.go
- pkg/snowflake/failover_group.go
- pkg/snowflake/table.go
- pkg/snowflake/task.go
This PR fixes go slice preallocation, and adds `prealloc` lint rule.
> fix: preallocate slice

- .golangci.yml
- pkg/provider/provider_test.go
- pkg/snowflake/table_constraint.go
- pkg/snowflake/tag_association.go
This PR fixes insecure go expression.
```
pkg/snowflake/table_constraint.go:224:10: G201: SQL string formatting (gosec)
stmt := fmt.Sprintf(`SELECT * FROM SNOWFLAKE.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = '%v' AND TABLE_SCHEMA = '%v' AND TABLE_CATALOG = '%v' AND CONSTRAINT_NAME = '%v'`, tableName, tableSchema, tableDB, name)
^
pkg/snowflake/tag_association.go:99:10: G201: SQL string formatting (gosec)
stmt := fmt.Sprintf(`SELECT SYSTEM$GET_TAG('"%v"."%v"."%v"', '%v', '%v') TAG_VALUE WHERE TAG_VALUE IS NOT NULL`, tb.databaseName, tb.schemaName, tb.tagName, tb.objectIdentifier, tb.objectType)
```
Refs:
https://securego.io/docs/rules/g201-g202.html
> fix: insecure go expression

- docs/resources/warehouse.md
- pkg/resources/warehouse.go
- pkg/snowflake/warehouse.go
* Added warehouse type for snowpark optimized warehouses
* Updated Docs
* Update warehouse.go
* [snowpark-optimized-warehouses](https://docs.snowflake.com/en/user-guide/warehouses-snowpark-optimized.html#snowpark-optimized-warehouses)
> feat: Adding warehouse type for snowpark optimized warehouses

- .golangci.yml
This PR adds a new linter rule called `depguard` which checks whether the packages imported in this project are acceptable. This PR should be merged after my earlier PRs because this PR does not modify any codes.
I want not to use `github.com/pkg/error` and `io/ioutil` anymore because they are deprecated.
All of `github.com/pkg/error` will be removed in the PR: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1360 .
> feat(ci): add depguard in golangci to avoid importing unacceptable packages

- docs/index.md
While reviewing the [provider docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs) we noticed an inconsistency regarding required keys for the provider configuration.
This updated documentation consistently identifies `region` as optional, but indicates it is needed if using the legacy format for the account identifier.
* [preferred format](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-1-preferred-account-name-in-your-organization): `<org_name>-<account_name>`
* [legacy format](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#format-2-legacy-account-locator-in-a-region): `<account_locator>.<cloud_region_id>.<cloud>`
_Also includes minor edits for consistent language around sourcing values from environment …
> docs: Clarify account identifier formats

- .github/workflows/team-jira-issues.yml
- pkg/resources/file_format.go
- pkg/resources/file_format_test.go
If a file format has been created vis the provider and the is subsequently deleted manually the plan refresh fails rather than removing the resource from the plan and recreating
* [*] acceptance tests executed
* [* ] unit test added
Fixes #1395
*
> fix: stop file format failure when does not exist

- pkg/snowflake/parser.go
- pkg/snowflake/table.go
- pkg/snowflake/table_test.go
This PR fixes lines to use better Go syntax.
- increment-decrement: should replace found += 1 with found++
- removing underscore
```
pkg/snowflake/table.go:118:2: var-naming: don't use underscores in Go names; struct field masking_policy should be maskingPolicy (revive)
masking_policy string
```
> fix: go syntax

- pkg/resources/role_grants.go
- pkg/resources/role_grants_test.go
Some preview functionality to Snowflake can result in extra role grants which can break this provider, e.g. `unknown grantee type ...`. While it's not a great idea to update this provider with non-public role grants, it's very helpful to simply ignore the roles that the provider doesn't currently handle.
None
I'll see if I can get the acceptance tests working against such an account.
> fix: Don't throw an error on unhandled Role Grants

- pkg/snowflake/current_account.go
added the region us-east4.gcp to regionMapping. currently snowflake_current_acount values resolve in nulls
*
> fix: add us-east4.gcp to regionMapping

- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_acceptance_test.go
Add basic support for `UpdateResourceMonitor`
Checks `credit_quota`, `frequency`, `start_timestamp`, and `end_timestamp`
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.537s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     1.797s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources …
```
> feat: Support for UpdateResourceMonitor

- pkg/resources/saml_integration.go
* Fix `saml2_sign_request` cast type which leads to plugin crash:
```
Stack trace from the terraform-provider-snowflake_v0.54.0 plugin:
panic: interface conversion: interface {} is bool, not string
goroutine 16 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateSAMLIntegration(0x0?, {0x103bf9e00?, 0x140000b7ba0})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/saml_integration.go:187 +0x9a4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x103c23c20?, {0x103c23c20?, 0x14000495a40?}, 0xd?, {0x103bf9e00?, 0x140000b7ba0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140001f9180, …
```
> fix: saml2_sign_request and saml2_force_authn cast type

- pkg/resources/helper_expansion.go
- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_acceptance_test.go
- pkg/snowflake/resource_monitor.go
resource_monitor now can update without creation and delation for 
- notify_users
- suspend_triggers
- notify_triggers
- set_for_account
- warehouses
Also fixed a typo in a comment implents to implements
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1310
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/876
> feat: add in more functionality for UpdateResourceMonitor 

- docs/resources/pipe_grant.md
- pkg/resources/pipe_grant.go
- `schema_name` optional for future pipe grants
- Rename `futurePipes` to `onFuture` for consistency
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  3.711s  coverage: 3.7% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     2.318s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    14.246s coverage: 48.2% …
```
> fix: schema_name is optional to enable future pipe grant

- pkg/resources/failover_group.go
- pkg/snowflake/failover_group.go
This PR fixes update method on failover group. So previously when updating replication schedule would get an index out of range exception
```
Stack trace from the terraform-provider-snowflake_v0.55.0 plugin:
413panic: runtime error: index out of range [0] with length 0
414goroutine 107 [running]:[415github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateFailoverGroup](https://415github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateFailoverGroup)(0xc000532600, {0x12dc720?, 0xc00052f110?})
416 [github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/failover_group.go:566](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/failover_group.go:566) +0x16cf[417github.com/hashicorp/terraform-plugin-sdk/v2/helper/schem …
```
> fix: update on failover group

- docs/resources/task_grant.md
- pkg/resources/task_grant.go
Closes #1213 
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.484s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     1.719s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    12.543s coverage: 46.9% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflak …
```
> fix: schema name is optional for future task_grant

- docs/resources/stream_grant.md
- pkg/resources/stream_grant.go
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.258s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     3.233s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    13.633s coverage: 46.9% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake    0.350s …
```
> fix: schema name is optional for future stream_grant

- docs/resources/sequence_grant.md
- pkg/resources/sequence_grant.go
Closes #1197 
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  1.784s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     2.444s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    12.531s coverage: 46.9% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflak …
```
> fix: schema name is optional for future sequence_grant

- docs/resources/procedure_grant.md
- pkg/resources/procedure_grant.go
Closes #682 
Closes #766 
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.830s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     2.052s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    12.399s coverage: 46.9% of statements
ok …
```
> fix: schema name is optional for future procedure_grant

- docs/resources/function_grant.md
- pkg/resources/function_grant.go
Closes #658 
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.031s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     2.735s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    12.432s coverage: 46.9% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake …
```
> fix: schema name is optional for future function_grant

- docs/resources/file_format_grant.md
- pkg/resources/file_format_grant.go
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  1.780s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     2.523s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    12.532s coverage: 46.9% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake    0.426s …
```
> fix: schema name is optional for future file_format_grant

- docs/resources/external_table_grant.md
- pkg/resources/external_table_grant.go
Closes #996 
Closes #1115 
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  4.077s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     2.668s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    12.826s coverage: 46.9% of statements
ok …
```
> fix: schema name is optional for future external_table_grant

- pkg/resources/grant_helpers.go
closes #1459. cleans up some of the logic when enabling multiple grants . Previously if you had two grants that managed the same resources, then one would overwrite the other during subsequent apply.
*
> fix: multiple share grants

- CHANGELOG.md
- pkg/resources/grant_helpers.go
- pkg/resources/role_grants.go
> fix: add nill check for grant_helpers

- pkg/resources/function_grant.go
- pkg/resources/procedure_grant.go
Fixes out of bound index exception when arguments are not supplied (i.e. on_future) parsing of old procedure and function grant IDs
#1547
> fix: proc id parsing for legacy id

- pkg/resources/failover_group.go
- pkg/resources/failover_group_acceptance_test.go
- pkg/snowflake/failover_group.go
fix update for replication schedule on failover groups
> fix: add test cases for update repl schedule on failover group

- docs/resources/user.md
- pkg/resources/user.go
Extending the documentation for `default_secondary_roles`parameter about allowed values.
Fixing #1579
> docs: default_secondary_roles doc

- pkg/resources/role_grants.go
- pkg/resources/role_grants_acceptance_test.go
- pkg/resources/role_grants_test.go
- role_grants resource is now recreated if the role_name is changed
- when refreshing the resource, the code checks now first, if the grantee role still exists (in case it was manually deleted in snowflake)
Issue is described in #1590
> fix: added force_new option to role grant when the role_name has been changed

- docs/resources/api_integration.md
- examples/resources/snowflake_api_integration/resource.tf
- pkg/resources/api_integration.go
- pkg/resources/api_integration_acceptance_test.go
- pkg/snowflake/api_integration.go
Adds missing API Integration `google_api_gateway`
* https://docs.snowflake.com/en/sql-reference/sql/create-api-integration
> feat(integration): add google api integration

- docs/resources/oauth_integration.md
- pkg/resources/oauth_integration.go
- pkg/resources/oauth_integration_acceptance_test.go
- pkg/resources/task.go
Resolves #785 
When using https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/oauth_integration with a custom client we need two required arguments. [oauth_redirect_uri](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/oauth_integration#oauth_redirect_uri) and oauth_client type. Today only `oauth_redirect_uri` is supported.
This PR aims to solve that.
When I use
```
resource "snowflake_oauth_integration" "new_integration" {
provider           = snowflake.SYSADMIN
name               = "NEW_INTEGRATION"
oauth_client       = "CUSTOM"
enabled            = true
oauth_redirect_uri = "MY_URL"
}
```
I get the following error.
```
│ Error: error creating security integration: 002029 (42601): SQL compilation error:
│ Missing …
```
> fix: oauth integration

- pkg/resources/stream.go
- pkg/resources/stream_acceptance_test.go
- pkg/resources/stream_test.go
- pkg/snowflake/stream.go
- pkg/snowflake/stream_test.go
This PR adds support for Streams to work with Stages.
I've just used the `make test` command locally
^ I wasnt sure on whether those 2 functions needed to be updated or not, so left it for now.
Full disclosure: this is my first time contributing to a terraform provider project, so I'm not 100% sure if I've changed all the correct things. If I've missed anything, let me know and I'll add it in.
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1412
> feat: add ON STAGE support for Stream resource

- docs/resources/procedure.md
- pkg/resources/procedure.go
- pkg/snowflake/procedure.go
- pkg/snowflake/procedure_test.go
This PR adds support for the following optional parameters for `PROCEDURE`:
- `packages` for Python and Java stored procedures
- `imports` again for Python and Java
- `handler` the target handler function
- `runtimeVersion` required for Python procedures
- The `TestProcedureCreateWithOptionalParams` test in `procedure_test.go` has been updated to include the added optional parameters
- The `getProcedure` func includes a statement, which doesn't make a huge amount of sense given that we are using a handler, but the equivalent `getPythonFunction` in `function_test.go` does too, so I assume this is ok
- Tested that a local version of the provider with the new params successfully deploys a procedure to Snowflake 🎉
> feat: Add support for `packages`, `imports`, `handler` and `runtimeVersion` to `snowflake_procedure` resource

- docs/resources/resource_monitor.md
- examples/resources/snowflake_resource_monitor/import.sh
- examples/resources/snowflake_resource_monitor/resource.tf
- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_test.go
Fixing https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1538
Both the `suspend trigger` and `suspend immediate trigger` properties for a resource monitor are just a single number, not a set of numbers.
Also adding missing information for importing the resource monitor Terraform resource.
Also adding a note for `set_for_account` property, as it defaults to false.
NOTE: Important to notice that due to the change of the properties (removing the s) this is a breaking change
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/resource_monitor
https://docs.snowflake.com/en/sql-reference/sql/create-resource-monitor
> fix: change resource monitor suspend properties to number

- .goreleaser.prerelease.yml
- .goreleaser.yml
Recent upgrade of gosnowflake libraries causes problems building freebsd with arch 386. Since this is probably not a very popular OS anyhow, best just to remove it. Otherwise will need to file a PR with gosnowflake to get them to downgrade the arrow library.
```
$ export GOOS=freebsd
$ export GOARCH=386
$ go install
../../../../pkg/mod/github.com/apache/arrow/go/v10@v10.0.1/internal/utils/transpose_ints_def.go:76:4: undefined: TransposeInt8Int8
../../../../pkg/mod/github.com/apache/arrow/go/v10@v10.0.1/internal/utils/transpose_ints_def.go:78:4: undefined: TransposeInt8Int16
../../../../pkg/mod/github.com/apache/arrow/go/v10@v10.0.1/internal/utils/transpose_ints_def.go:80:4: undefined: TransposeInt8Int32
../../../../pkg/mod/github.com/apache/arrow/go/v10@v10.0.1/internal/utils/transpose_int …
```
> fix: openbsd build

- pkg/resources/table.go
Move the cluster_by logic when updating a table to take place *after* columns are added.
This fixes https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1507
Relying on CI here, don't think we need to update any existing tests
N/A
> feat: Support changing cluster_by on a new column

- docs/data-sources/parameters.md
- docs/resources/object_parameter.md
- docs/resources/session_parameter.md
- examples/data-sources/snowflake_parameters/data-source.tf
- examples/resources/snowflake_object_parameter/resource.tf
- examples/resources/snowflake_session_parameter/resource.tf
- pkg/datasources/parameters.go
- pkg/datasources/parameters_acceptance_test.go
- pkg/resources/account_parameter.go
- pkg/resources/object_parameter.go
- pkg/resources/object_parameter_acceptance_test.go
- pkg/resources/session_parameter.go
- pkg/resources/session_parameter_acceptance_test.go
- pkg/snowflake/parameters.go
Allows session params to be created either on account or on user. And object params to be created either on an object, or on account.
issues #1565 , #1546
> feat: add on_account to session and object params

- pkg/resources/external_oauth_integration_acceptance_test.go
Use generated issuer name in external oauth integration acceptance test to avoid collisions (each account can only have one integration for each issuer) and false negatives.
> fix: Randomize test issuer for oauth integration acceptance test.

- pkg/resources/resource_monitor.go
Fixing a bug that causes a plugin crash when attempting to set suspend immediate trigger in the special case.
closes #1732
> fix: resource monitor read SI trigger bug

- pkg/datasources/parameters_acceptance_test.go
- pkg/resources/object_parameter_acceptance_test.go
The value field can sometime be null. Recently the first parameters returned has changed and that new parameter has a null value. We'll stop relying on the value field being set for acceptance tests.
> chore: fix parameters datasource acceptance test

- pkg/resources/tag_association_acceptance_test.go
- pkg/snowflake/tag_association.go
- pkg/snowflake/tag_association_test.go
When the database and schema of the table and tags are different, the code was applying the tag's database and schema to the table name. 
Error we were getting for this type of configuration
```
resource "snowflake_tag" "test_tag" {
name           = "tag_name2"
database       = "TAG_DB"
schema         = "TAG_SCHEMA"
}
resource "snowflake_table" "test_table" {
database            = "TEST_DB"
schema              = "TEST_SCHEMA"
name                = "test_table"
comment             = "A table."
column {
name    = "column_name"
type    = "VARIANT"
}
}
resource "snowflake_tag_association" "column_association" {
object_identifier {
name                = "${snowflake_table.test_table.name}.${snowflake_table.test_table.column[0].name}"
database            = "TEST_DB"
schema              = …
```
> fix: fixing the table's database and schema name for Column tag

- pkg/resources/warehouse.go
- pkg/resources/warehouse_acceptance_test.go
- pkg/sdk/warehouse.go
Fix a bug where underscore in warehouse names would be treated as wildcards (cf. https://docs.snowflake.com/en/sql-reference/functions/like) and the read operation would return the wrong warehouse, leading to unwanted changes, etc.
* To be merged after https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1792
> fix: reading warehouse with underscore in name

- .vscode/settings.json
- pkg/resources/password_policy.go
- pkg/resources/password_policy_acceptance_test.go
- pkg/resources/warehouse.go
Fix a bug (#1762) where setting max_age_days to 0 would be ignored and default back to 90 (default value). This is fixed for other resources too.
* #1762
> fix: allow password_policy.max_age_days = 0

- pkg/sdk/data_types.go
- pkg/sdk/data_types_test.go
Updates the [DataTypeFromString](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/1037f9833131ca6d5a0e75adcafe9b99f5f86173/pkg/sdk/data_types.go#L32) function so that that TIME(<precision>) map to TIME, rather than UNKNOWN.
Thank you @ogr003 for the pattern on how to address the bug I reported.
References
My original report of the issue: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1791
Related issue for TIMESTAMP_TZ and TIMESTAMP_LTZ being incorrectly mapped to TIMESTAMP_NTZ: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1809
@ogr003's fix to the above issue, which I followed the footsteps: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1810
> Fix handling of TIME(*)

- pkg/resources/privileges.go
- pkg/resources/schema_grant.go
With Streamlit support on the horizon, adding CREATE STREAMLIT privilege to Terraform.
I added this as a configuration in privileges, I don't believe any logic was changed.
> feat: adding CREATE STREAMLIT as privilege

- .goreleaser.prerelease.yml
- .goreleaser.yml
Build FreeBSD package
This builds cleanly on FreeBSD with no modifications, using `gmake install`, as well as `goreleaser build --single-target --snapshot`. I have used the resulting binary to create snowflake resources.
```
Initializing provider plugins...
- Finding snowflake-labs/snowflake versions matching "~> 0.64"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/snowflake-labs/snowflake v0.64.0 does not have a package
│ available for your current platform, freebsd_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are
│ available for all platforms. Other versions of this provider may have different platforms
│ supported.
```
`Apply complete! Resources: 2 added, 0 changed, 0 destroyed.`
> fix: gorelease freebsd

- docs/resources/role_grants.md
- pkg/resources/role_grants.go
- pkg/resources/role_grants_test.go
Previously enable_multiple_grants parameter for the snowflake_role_grants resource did not revoke any permissions given outside of the terraform. My fix actually enables such behavior: if parameter is set to false, every role/user from `SHOW GRANTS OF ROLE "%s"` is being accounted by the resource.
Since everyone who used the resource previously had resource acting as the enable_multiple_grants were set to true, I suggest we change the default for this parameter to true as well, in order not to break existing configurations. Only the ones who set the parameter explicitly will see the change.
I added couple new unit tests around it, I don't know if any new acceptance tests are required.
> fix: fixed enable_multiple_grants behaviour for role_grants

- pkg/resources/account_parameter_acceptance_test.go
- pkg/snowflake/parameters.go
There are many missing parameters from the provider that are in the snowflake [docs](https://docs.snowflake.com/en/sql-reference/parameters). The ones I've added here are those I have an urgent need for at the moment.
Added a test for the parameter `CLIENT_METADATA_USE_SESSION_DATABASE` as it is not documented that it applies to the account as well as the session.
* [Parameters | Snowflake Documentation](https://docs.snowflake.com/en/sql-reference/parameters)
> feat: adding a subset of missing parameters

- pkg/provider/provider.go
- pkg/sdk/client_integration_test.go
- pkg/sdk/config.go
- pkg/sdk/config_test.go
If no profile is found with a given name, return nil. Then if config is nil, fall back to using credentials.
fixes:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1852
> fix: err when reading profile

- pkg/sdk/databases.go
missing 'kind' field in database struct leading to:
_Error: unable to scan row for SHOW DATABASES LIKE 'SCRATCH' err = missing destination name kind in *[]snowflake.Databas_
N/A
N/A
#1868
*
> fix: missing 'kind' field

- pkg/resources/external_oauth_integration.go
- pkg/resources/external_oauth_integration_acceptance_test.go
- pkg/snowflake/builder.go
- pkg/snowflake/external_oauth_integration_test.go
Generates security integration statements with double-quoted names to prevent issues with mis-cased objects.
> fix: Generate security integration statements using double quoted names.

- pkg/resources/external_oauth_integration.go
- pkg/resources/external_oauth_integration_acceptance_test.go
- pkg/snowflake/builder.go
- pkg/snowflake/external_oauth_integration.go
Add support for `sql.NullString` in `sqlBuilder` (pkg.snowflake) to support empty comments in resource `external_oauth_integration`.
Fixes https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1755
> fix: support empty comments in oauth integrations

- pkg/resources/warehouse.go
Do not set "query_acceleration_max_scale_factor" if Query Acceleration is not enabled on Warehouse creation.
Note: I could not run acceptance tests; my configuration has a strange problem ('two regions specified' error). I'll continue trying to fix this issue, but it would be great if anyone could run those tests.
Issues:
* [1343](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1343)
* [1628](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1628)
Related PR:
* [1474](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1474) — this PR fixed a similar problem but only for updating the existing Warehouse. The problem still occurs on a Standard Snowflake Edition on creating a new Warehouse
> fix: conditional set "query_acceleration_max_scale_factor"

- docs/resources/view.md
- pkg/resources/stream_test.go
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
- pkg/resources/view_test.go
- pkg/snowflake/view.go
Fixes a bug where a view would get dropped whenever the copy_grants attribute changes.
> fix: prevent view drop when copy_grants attribute changes

- pkg/snowflake/parameters.go
Add missing option as per https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1923
> fix: snowflake_object_parameter add missing option

- pkg/sdk/file_format.go
- pkg/sdk/file_format_integration_test.go
- pkg/sdk/file_format_test.go
Updates the ShowById sdk method to specify the schema (`IN SCHEMA "db"."schema"`) in which to search for a file format.
* Fixes #1934
> fix: reading file formats with no default schema

- pkg/sdk/warehouses.go
* Allow for another warehouse size value to suppress  terraform diff, fixes #1889
> fix: suppress warehouse size changes

- pkg/resources/grant_privileges_to_role.go
- pkg/resources/grant_privileges_to_role_acceptance_test.go
When using two `grant_privileges_to_role` resources for the same role, they conflict with each other and try to delete each other’s grants. This makes managing permissions difficult as grants for a single role have to be managed in a single place, no modularity is possible.
The following snippet will consistently drift:
```hcl
resource "snowflake_role" "r" {
name = "testrole"
}
resource "snowflake_grant_privileges_to_role" "g1" {
role_name  = snowflake_role.r.name
privileges = ["CREATE ACCOUNT", "CREATE ROLE"]
on_account = true
}
resource "snowflake_grant_privileges_to_role" "g2" {
role_name  = snowflake_role.r.name
privileges = ["IMPORT SHARE", "MANAGE GRANTS"]
on_account = true
}
```
*
> fix: support multiple grant_privilege_to_role resources on the same role

- pkg/resources/pipe_grant.go
- pkg/resources/pipe_grant_acceptance_test.go
Changes the default privilege of a snowflake_pipe_grant to be `OPERATE`
Fixes #1969
> fix: 1969  change default privilege to OPERATE

- docs/resources/grant_privileges_to_role.md
Fixes documentation for valid schema object types (singular and plural) for `snowflake_grant_privileges_to_role` resource.
> Fix valid schema object types in grant_privileges_to_role.md

- docs/resources/user.md
- pkg/resources/user.go
Marks snowflake_user.login_name as non-sensitive
- no changes
* Fixes #1907
> feat: Mark user login_name as non-sensitive.

- pkg/resources/stage.go
- pkg/resources/stage_acceptance_test.go
- pkg/resources/stage_test.go
- pkg/snowflake/stage.go
- pkg/snowflake/stage_test.go
Previously, if both `URL` and `STORAGE_INTEGRATION` had been updated the provider would generate separate ALTER STAGE commands - one for `URL`, and another for `STORAGE` integration.  This can create an invalid change because:
- When changing `URL`: the new `URL` could be invalid with the existing storage integration `STORAGE_ALLOWED_LOCATIONS`
- When changing STORAGE_INTEGRATION: existing `URL` not present in the new storage integration `STORAGE_ALLOWED_LOCATIONS`
This MR now checks if both `URL` and `STORAGE_INTEGRATION` have changed and issues a single `ALTER` statement with both changes in one go.
Before:
ALTER STAGE the_stage SET URL = 's3://the_new_url'
ALTER STAGE the_stage SET STORAGE_INTEGRATION  = "new_storage_integration"
Now:
ALTER STAGE the_stage SET STORAGE_INTEGRATION  = …
> fix: unable to alter stage if url and si have changes  (#1982)

- pkg/sdk/warehouses.go
- pkg/sdk/warehouses_test.go
max clusters of 10 is a soft limit and can be lifted via support. this removes some validation on the max clusters to allow for these soft limit elevations.
> fix: warehouse size validations

- pkg/resources/account.go
- pkg/sdk/accounts_test.go
- Previoulsy, GetOK was returning false on a falsely-set value for this, stopping it from going into the query string.  We can safely use Get instead to always get this clause into the query string (The resource param has a default of false already).
- This has the added benefit of not relying on the default behavior on the snowflake side, which has changed in the past.  So tf users shouldn't be caught off guard if it changes again.
- I wrote a test for this before I realized this issue lied in the provider code
this addresses https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1607
*
> fix: Always set MUST_CHANGE_PASSWORD on account creation

- pkg/sdk/file_format.go
- pkg/sdk/identifier_helpers.go
- pkg/sdk/identifier_helpers_test.go
Fixes the SchemaObjectIdentifier to work with procedures and functions, which also have arguments. Added test cases to ensure that parsing of all different types of IDs works as expected.
```
=== RUN   TestNewSchemaObjectIdentifierFromFullyQualifiedName
=== RUN   TestNewSchemaObjectIdentifierFromFullyQualifiedName/"MY_DB"."MY_SCHEMA"."multiply"(number,_number)
=== RUN   TestNewSchemaObjectIdentifierFromFullyQualifiedName/MY_DB.MY_SCHEMA.add(number,_number)
=== RUN   TestNewSchemaObjectIdentifierFromFullyQualifiedName/"MY_DB"."MY_SCHEMA"."MY_UDF"()
=== RUN   TestNewSchemaObjectIdentifierFromFullyQualifiedName/"MY_DB"."MY_SCHEMA"."MY_PIPE"
=== RUN   TestNewSchemaObjectIdentifierFromFullyQualifiedName/MY_DB.MY_SCHEMA.MY_STAGE
--- PASS: TestNewSchemaObjectIdentifierFromFullyQualifiedName …
```
> fix: SNOW-889027 Schema Object Id Fix for Functions / Procedures

- pkg/sdk/accounts.go
- pkg/sdk/alerts.go
- pkg/sdk/databases.go
- pkg/sdk/failover_groups.go
- pkg/sdk/file_format.go
- pkg/sdk/grants.go
- pkg/sdk/masking_policy.go
- pkg/sdk/password_policy.go
- pkg/sdk/pipes.go
- pkg/sdk/replication_functions.go
- pkg/sdk/resource_monitors.go
- pkg/sdk/schemas.go
- pkg/sdk/session_policies.go
- pkg/sdk/sessions.go
- pkg/sdk/shares.go
- pkg/sdk/users.go
- pkg/sdk/warehouses.go
We copy-paste lint ignore while doing SDK rewrite. This suppression seems to be outdated. The reason for this change is to confirm that no check triggers without aforementioned comment.
> chore: Remove lint ignore comments - test

- pkg/sdk/database_role.go
- pkg/sdk/database_role_dto.go
- pkg/sdk/database_role_dto_builders.go
- pkg/sdk/database_role_impl.go
- pkg/sdk/database_role_integration_test.go
- pkg/sdk/database_role_test.go
- pkg/sdk/database_role_validations.go
* Implement database roles in SDK:
* [grant-database-role](https://docs.snowflake.com/en/sql-reference/sql/grant-database-role)
* [revoke-database-role](https://docs.snowflake.com/en/sql-reference/sql/revoke-database-role)
* [grant-database-role-share](https://docs.snowflake.com/en/sql-reference/sql/grant-database-role-share)
* [revoke-database-role-share](https://docs.snowflake.com/en/sql-reference/sql/revoke-database-role-share)
* [GRANT DATABASE ROLE ... TO ROLE](https://docs.snowflake.com/en/sql-reference/sql/grant-database-role)
* [REVOKE DATABASE ROLE ... FROM ROLE](https://docs.snowflake.com/en/sql-reference/sql/revoke-database-role)
* [GRANT DATABASE ROLE ... TO SHARE](https://docs.snowflake.com/en/sql-reference/sql/grant-database-role-share)
* [REVOKE DATABASE ROLES ... FROM …
> feat: Add missing database role operations to SDK

- pkg/sdk/accounts.go
- pkg/sdk/alerts.go
- pkg/sdk/assertions_test.go
- pkg/sdk/comments.go
- pkg/sdk/common_types.go
- pkg/sdk/database_role_validations.go
- pkg/sdk/databases.go
- pkg/sdk/failover_groups.go
- pkg/sdk/file_format.go
- pkg/sdk/grants.go
- pkg/sdk/helpers_proposal.go
- pkg/sdk/masking_policy.go
- pkg/sdk/parameters.go
- pkg/sdk/password_policy.go
- pkg/sdk/pipes_validations.go
- pkg/sdk/replication_functions.go
- pkg/sdk/resource_monitors.go
- pkg/sdk/schemas.go
- pkg/sdk/session_policies.go
- pkg/sdk/sessions.go
- pkg/sdk/shares.go
- pkg/sdk/users.go
- pkg/sdk/warehouses.go
Reuse `validatableOpts` interface:
- rename it to `validatable`
- rename method to `validate()`
- add implementation guards for all `XxxOptions` structs
> chore: Rename and reuse validatableOpts interface

- .github/workflows/integration.yml
- Makefile
Fix make sweep.
Syntax used for make sweep was made for bash shell which we are NOT running on CI. It resulted in errors when running sweepers:
```
/bin/sh: 1: read: Illegal option -n
/bin/sh: 2: [[: not found
```
There were few fix options to consider here:
- changing shell on CI
- changing shell inside Makefile
- rewriting it to support all shells
Last one was chosen because was the easiest one to apply without affecting other jobs and Makefile recipes.
> fix: Fix make sweep

- .github/workflows/go-fmt.yml
- .github/workflows/integration.yml
- pkg/sdk/database_role_integration_test.go
* Remove unneccesary environment variable.
* Extract `make lint-ci` from integration workflow.
Step `make lint-ci integration` was wasting over 2 minutes of time of the integration workflow, delaying acceptance tests start (which is the longest part of our build). This should make our builds 2-3 minutes faster.
> chore: Extract reviewdog job from integration workflow

- pkg/resources/grant_helpers.go
Fixes:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1962
Previously would get this error message:
```
│ Error: unknown grantee type APPLICATION
│
│   with snowflake_account_grant.create_user,
│   on main.tf line 18, in resource "snowflake_account_grant" "create_user":
│   18: resource "snowflake_account_grant" "create_user" {
│
```
Simply ignoring application grantee types fixes the problem.
> fix: remove grantee error

- pkg/resources/account_grant_acceptance_test.go
- pkg/resources/grant_privileges_to_role_acceptance_test.go
- pkg/sdk/identifier_helpers.go
- pkg/sdk/identifier_helpers_test.go
- pkg/sdk/shares.go
The `show shares` API has changed, now there is an `owner_account` field. This can be used to fix some problems with external ids that were causing the CI/CD pipeline to fail when deleting shares. (it was having trouble parsing the ID for shares that had "." in the name, as it could not determine if it whether the format of the account identifier was legacy or not).
```
SHOW SHARES STARTS WITH 'SNOW' LIMIT 5 FROM 'A';
+-------------------------------+----------+------------------------+------------------------+----------------+------------------+--------------+---------+---------------------+
| created_on                    | kind     | owner_account          |  name                  | database_name  | to               | owner        | comment | listing_global_name | …
```
> fix: external id for shares

- pkg/sdk/grants.go
- pkg/sdk/grants_impl.go
- pkg/sdk/grants_integration_test.go
- pkg/sdk/grants_test.go
- pkg/sdk/grants_validations.go
- pkg/sdk/helper_test.go
* Implement granting privileges to database roles in SDK:
* Add implementation based on references
* split existing grants implementation into files
* fix returned Grant type
* add missing validations
* correct existing validations
* What was NOT changed:
* Grants interface is not using our new Requests, new methods are also not using them, to make them consistent inside this interface and not to do too much refactoring in this PR
* [GRANT \<privileges\>](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#syntax)
* [REVOKE \<privileges\>](https://docs.snowflake.com/en/sql-reference/sql/revoke-privilege#syntax)
> feat: Add grant privileges to database role to SDK

- pkg/datasources/pipes.go
- pkg/resources/pipe.go
- pkg/sdk/database_role_test.go
- pkg/sdk/external_tables.go
- pkg/sdk/external_tables_dto.go
- pkg/sdk/external_tables_impl.go
- pkg/sdk/external_tables_test.go
- pkg/sdk/external_tables_validations.go
- pkg/sdk/helper_test.go
- pkg/sdk/password_policy.go
- pkg/sdk/password_policy_integration_test.go
- pkg/sdk/password_policy_test.go
- pkg/sdk/pipes.go
- pkg/sdk/pipes_impl.go
- pkg/sdk/pipes_integration_test.go
- pkg/sdk/pipes_test.go
- pkg/sdk/pipes_validations.go
- pkg/sdk/roles_dto.go
- pkg/sdk/roles_impl.go
- pkg/sdk/session_policies.go
- pkg/sdk/shares.go
- pkg/sdk/shares_test.go
- pkg/sdk/tables.go
- pkg/sdk/tags.go
- pkg/sdk/warehouses.go
- pkg/sdk/warehouses_test.go
We want to align the naming of all options to `ActionObjectOptions`, e.g. `CreatePipeOptions`. New options are already being named accordingly. Existing options are renamed in this PR.
> chore: Make options naming consistent

- Makefile
- pkg/resources/password_policy.go
- pkg/resources/table_acceptance_test.go
- pkg/sdk/password_policy_integration_test.go
- Temporarily ignore two flaky tests which fail most often.
- Disable unsetting comments on password policies temporarily
```
=== RUN   TestAcc_TableWithSeparateDataRetentionObjectParameterWithoutLifecycle
table_acceptance_test.go:15: Skipping TestAcc_TableWithSeparateDataRetentionObjectParameterWithoutLifecycle
--- SKIP: TestAcc_TableWithSeparateDataRetentionObjectParameterWithoutLifecycle (0.00s)
=== RUN   TestAcc_TableWithSeparateDataRetentionObjectParameterWithLifecycle
table_acceptance_test.go:63: Skipping TestAcc_TableWithSeparateDataRetentionObjectParameterWithLifecycle
--- SKIP: TestAcc_TableWithSeparateDataRetentionObjectParameterWithLifecycle (0.00s)
```
* Failing tests for password policy unset comment:
```
=== RUN   TestInt_PasswordPolicyAlter/when_unsetting_multiple_values_at_ …
```
> fix: Ignore two flaky table tests and disable comment unset for password policy

- pkg/sdk/accounts.go
- pkg/sdk/alerts.go
- pkg/sdk/comments.go
- pkg/sdk/databases.go
- pkg/sdk/failover_groups.go
- pkg/sdk/file_format.go
- pkg/sdk/grants.go
- pkg/sdk/helper_test.go
- pkg/sdk/masking_policy.go
- pkg/sdk/parameters.go
- pkg/sdk/password_policy.go
- pkg/sdk/pipes.go
- pkg/sdk/replication_functions.go
- pkg/sdk/replication_functions_integration_test.go
- pkg/sdk/resource_monitors.go
- pkg/sdk/roles.go
- pkg/sdk/schemas.go
- pkg/sdk/sessions.go
- pkg/sdk/shares.go
- pkg/sdk/users.go
- pkg/sdk/warehouses.go
- Remove interface methods comments
- Add a link to Snowflake doc for every SDK Options struct
Because of the two conclusions we had about SDK:
- We will get rid of meaningless comments, e.g. comments on interface methods. We will not be adding them with new objects.
- We will keep adding documentation comments on struct level (...Options). We are adding them with new objects.
> chore: Cleanup comments

- pkg/sdk/tasks_def.go
- pkg/sdk/tasks_dto_builders_gen.go
- pkg/sdk/tasks_dto_gen.go
- pkg/sdk/tasks_gen.go
- pkg/sdk/tasks_gen_integration_test.go
- pkg/sdk/tasks_gen_test.go
- pkg/sdk/tasks_impl_gen.go
- pkg/sdk/tasks_validations_gen.go
* Add task clone to SDK:
* Add implementation based on references
* Update task definition in `tasks_def.go`
* [CREATE TASK ... CLONE](https://docs.snowflake.com/en/sql-reference/sql/create-task#variant-syntax)
> feat: Add task clone to sdk

- docs/index.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
Adds authenticator attribute to provider config, matching what is in golang connector https://github.com/snowflakedb/gosnowflake/blob/v1.6.25/dsn.go#L43.
This will allow for mfa token caching when using username + password + mfa token.
> feat: add authenticator

- pkg/sdk/external_tables.go
- pkg/sdk/external_tables_dto.go
- pkg/sdk/external_tables_dto_builders_gen.go
- pkg/sdk/external_tables_impl.go
- pkg/sdk/external_tables_test.go
- pkg/sdk/testint/external_tables_integration_test.go
Minor refactors + fixes + usage of SchemaObjectIdentifier instead of AccountObjectIdentifier
> fix: use schema object identifier in external tables

- pkg/sdk/testint/accounts_integration_test.go
- pkg/sdk/testint/alerts_integration_test.go
- pkg/sdk/testint/database_role_integration_test.go
- pkg/sdk/testint/dynamic_table_integration_test.go
- pkg/sdk/testint/external_tables_integration_test.go
- pkg/sdk/testint/failover_groups_integration_test.go
- pkg/sdk/testint/file_format_integration_test.go
- pkg/sdk/testint/grants_integration_test.go
- pkg/sdk/testint/helpers.go
- pkg/sdk/testint/masking_policy_integration_test.go
- pkg/sdk/testint/password_policy_integration_test.go
- pkg/sdk/testint/pipes_integration_test.go
- pkg/sdk/testint/roles_integration_test.go
- pkg/sdk/testint/schemas_integration_test.go
- pkg/sdk/testint/session_policies_gen_integration_test.go
- pkg/sdk/testint/sessions_integration_test.go
- pkg/sdk/testint/setup_integration_test.go
- pkg/sdk/testint/shares_integration_test.go
- pkg/sdk/testint/system_functions_integration_test.go
- pkg/sdk/testint/tasks_gen_integration_test.go
- pkg/sdk/testint/users_integration_test.go
- pkg/sdk/testint/warehouses_integration_test.go
After moving integration tests to a separate package in #2111 and #2115, it is possible now to reuse a common setup. This PR is about setting up a database only once for all integration tests and cleaning it up at the end.
* Create a database in integration tests setup; clean it up in cleanup.
* Not every test uses the created database (database tests, renames, and tests specifically needing two databases are still creating their own database).
* Database id is the same string with added UUID so that different test runs do not interfere with each other.
> chore: Integration tests setup db once

- docs/resources/file_format.md
- pkg/resources/file_format.go
- pkg/sdk/file_format.go
Modified `pkg/resources/file_format.go` to include the `parse_header` option for File Formats.
This option was already included in `pkg/sdk/file_format.go`, but it was never mapped to a Terraform configuration option.
* #2050
> feat: add parse_header option to file format resource

- pkg/sdk/accounts.go
SNOW-932299
getting the following error where running the command: SHOW ORGANIZATION ACCOUNTS LIKE ‘XXXXX’ 
```
2023-09-28T08:38:17.676-0400 [INFO] provider.terraform-provider-snowflake_v0.71.0: 2023/09/28 08:38:17 [DEBUG] sql-conn-query [query SHOW ORGANIZATION ACCOUNTS LIKE ‘XXXXX’ err <nil> duration 341.364ms args {}]: timestamp=2023-09-28T08:38:17.676-0400
2023-09-28T08:38:17.676-0400 [INFO] provider.terraform-provider-snowflake_v0.71.0: 2023/09/28 08:38:17 [DEBUG] sql-rows-next [err <nil> duration 389.375µs]: timestamp=2023-09-28T08:38:17.676-0400
2023-09-28T08:38:17.677-0400 [INFO] provider.terraform-provider-snowflake_v0.71.0: 2023/09/28 08:38:17 [DEBUG] err: sql: Scan error on column index 6, name “comment”: converting NULL to string is unsupported
```
> fix: change comment in Account struct to NullString

- pkg/resources/helpers_test.go
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
It's a fix that customer issued. It was failing, because statement attribute on view had a force new which issued terraform delete and then create actions which are not atomic and because of that view was missing grants. To fix it I've removed force new from statement attribute and then I modified terraform update method for view, so that when there's a change in the statement we'll perform create or replace (which is the only way of changing statement in views) with old settings and copy grants regardless of the copy grants attribute, because we would like to keep the grants as they were before, without them users might get the same error if copy grants wouldn't be specified. 
The only thing I'm not sure about is implicit copy grants, but I felt like copy grants attribute is only for …
> fix: view statement update

- pkg/resources/schema.go
- pkg/sdk/accounts.go
- pkg/sdk/accounts_test.go
- pkg/sdk/errors.go
- pkg/sdk/masking_policy.go
- pkg/sdk/masking_policy_test.go
- pkg/sdk/pipes.go
- pkg/sdk/pipes_test.go
- pkg/sdk/pipes_validations.go
- pkg/sdk/schemas.go
- pkg/sdk/schemas_test.go
- pkg/sdk/shares.go
- pkg/sdk/shares_test.go
- pkg/sdk/testint/accounts_integration_test.go
- pkg/sdk/testint/masking_policy_integration_test.go
- pkg/sdk/testint/pipes_integration_test.go
- pkg/sdk/testint/schemas_integration_test.go
- pkg/sdk/testint/shares_integration_test.go
- pkg/sdk/testint/system_functions_integration_test.go
- pkg/sdk/testint/warehouses_integration_test.go
- pkg/sdk/users.go
- pkg/sdk/users_test.go
- pkg/sdk/warehouses.go
- pkg/sdk/warehouses_test.go
Split existing alter operations to be more consistent with the docs.
* Extracted `SetTag` and `UnsetTag` from Set/Unset structs
* Adjusted validations and tests
* Fixed warehouse validation to check each possible param
* Removed unsetting a warehouse size; based on [docs](https://docs.snowflake.com/en/sql-reference/sql/alter-warehouse) - also our current resource implementation has been using set for warehouse size correctly already
> chore: Split existing alter operations

- pkg/sdk/network_policies_def.go
- pkg/sdk/poc/example/database_role_def.go
- pkg/sdk/poc/generator/identifier_builders.go
- pkg/sdk/poc/generator/keyword_builders.go
- pkg/sdk/poc/generator/operation.go
- pkg/sdk/poc/generator/parameter_builders.go
- pkg/sdk/poc/generator/query_struct.go
- pkg/sdk/poc/generator/static_builders.go
- pkg/sdk/session_policies_def.go
- pkg/sdk/streams_def.go
- pkg/sdk/tasks_def.go
This change contains 
- export of QueryStruct
- rename of its constructor to NewQueryStruct.
Other name proposal could be to name the type QueryStructBuilder (and other struct builders too) and leave QueryStruct constructor name. 
The change enables to create helper functions in definitions file, that are specific to given definition and shouldn't be put into generator common package.
> chore: Export QueryStruct

- pkg/resources/pipe.go
- pkg/sdk/pipes.go
- pkg/sdk/pipes_test.go
- pkg/sdk/pipes_validations.go
This PR fixes a bug where setting `error_integration` on a `snowflake_pipe` resource would cause the name of the integration to be written to the comment field on the pipe instead of the error integration. A separate bug prevented the `error_integration` diffs from being detected if an SNS topic was set.
I tested this using an existing stack where I have many pipes. I made an earnest attempt to update `pipes_integration_test.go`, but I reached the point where I needed a real SNS topic and decided that was beyond the timebox I set for this.
Using version 0.76.0:
1. Started with already deployed pipes that had a `comment` but no `error_integration`
2. Added `error_integration` to the terraform config.
3. terraform apply
4. Ran `describe pipe` on the updated pipes in Snowflake. The comments …
> fix: snowpipe error integration

- .github/workflows/reviewdog-staticcheck.yml
Disable the `staticcheck` until we configure linters appropriately or fix the reported problems (PRs are messy because it was turned on without checking).
> chore: Disable static check temporarily

- pkg/resources/schema_acceptance_test.go
- pkg/resources/testdata/TestAcc_Schema/test.tf
- pkg/resources/testdata/TestAcc_Schema/variables.tf
- pkg/resources/testdata/TestAcc_Schema_Rename/test.tf
- pkg/resources/testdata/TestAcc_Schema_Rename/variables.tf
- pkg/resources/testdata/TestAcc_Schema_TwoSchemasWithTheSameNameOnDifferentDatabases/1/test.tf
- pkg/resources/testdata/TestAcc_Schema_TwoSchemasWithTheSameNameOnDifferentDatabases/1/variables.tf
- pkg/resources/testdata/TestAcc_Schema_TwoSchemasWithTheSameNameOnDifferentDatabases/2/test.tf
- pkg/resources/testdata/TestAcc_Schema_TwoSchemasWithTheSameNameOnDifferentDatabases/2/variables.tf
- pkg/sdk/schemas.go
> fix: schemas show by id

- pkg/helpers/helpers.go
- pkg/helpers/helpers_test.go
- pkg/resources/testdata/TestAcc_ExternalTable_basic/test.tf
- pkg/resources/user_acceptance_test.go
- pkg/sdk/identifier_helpers.go
- pkg/sdk/privileges.go
Fix encoding SnowflakeIDs for SDK object identifiers.
It still needs work for other types; we will revisit this with identifiers rework.
Fix #2058
> fix: Fix encode Snowflake ID for object identifiers

- pkg/resources/dynamic_table.go
- pkg/resources/dynamic_table_acceptance_test.go
- pkg/resources/resource_monitor.go
- pkg/resources/resource_monitor_acceptance_test.go
- pkg/resources/testdata/TestAcc_DynamicTable_issue2276/1/test.tf
- pkg/resources/testdata/TestAcc_DynamicTable_issue2276/1/variables.tf
- Fix resource monitor update
- Handle dynamic table's query update
Fix #2167 
Fix #2276 
Fix #2175
> fix: Fix small issues

- Makefile
- README.md
- pkg/sdk/client.go
- pkg/sdk/client_integration_test.go
- pkg/sdk/internal/client/client_test.go
Allow setting gosnowflake logging level from `SF_TF_GOSNOWFLAKE_LOG_LEVEL` environment variable.
> chore: Allow setting gosnowflake logging level from environment variable

- pkg/scripts/issues/README.md
- pkg/scripts/issues/file/main.go
- pkg/scripts/issues/gh/main.go
- pkg/scripts/issues/gh/model.go
- pkg/scripts/issues/model.go
Add short scripts used to fetch all currently opened issues (for future reference).
> chore: Add short scripts used to fetch all currently opened issues

- pkg/resources/external_table.go
Fix for #2283
Reason: The Terraform on a ListType field returns a list of []any, so the Go assertion to []string failed because the underlying type was not known. A helper `expandStringList` function should be used instead.
> Parse External table partitions correctly

- docs/resources/email_notification_integration.md
- pkg/resources/email_notification_integration.go
- pkg/resources/email_notification_integration_acceptance_test.go
Fix email notification integration due to https://docs.snowflake.com/en/release-notes/2023/7_40#email-notification-integrations-allowed-recipients-no-longer-required.
Fix #2223
> fix: Fix email notification integration

- pkg/sdk/privileges.go
A fix for #2290 
It doesn't include any stack trace, but it seems like we were just missing a privilege in the Go enum in the SDK (resources/privileges.go already had create streamlit privilege).
> feat: Add create streamlit privilege to the SDK

- pkg/sdk/testint/databases_integration_test.go
- pkg/sdk/testint/failover_groups_integration_test.go
- pkg/sdk/testint/helpers_test.go
- pkg/sdk/testint/setup_test.go
- pkg/sdk/testint/shares_integration_test.go
The secondary account was added + tests with shares were fixed.
It turned out that the secondary has different business criticality (they probably should have the same business criticality). But for now, it only means I had to swap accounts in some places because you cannot share something from lower to higher business critically account (or vice-verse didn't remember).
> fix: Add secondary account and fix tests

- .goreleaser.yml
Fix for #2341
Goreleaser was unable to produce binaries for version 0.83.0.
We would like to release a bugfix version that will produce valid binaries which will be used in v0.83.0 and v0.83.1.
> fix: Revert goreleaser mfa token caching

- MIGRATION_GUIDE.md
- docs/index.md
- pkg/provider/provider.go
Adds setting `authenticator` to `JWT` explicitly to the docs and migration guide.
Check: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2169#issuecomment-1816167117 and https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2169#issuecomment-1878483811.
> docs: Add missing authenticator change to migration guide and the docs

- pkg/snowflake/masking_policy_application.go
Fix old masking policy implementation
Test `TestAcc_TableColumnMaskingPolicyApplication` started to fail after bundle 2023_08.
Fix #2362
> fix: Fix old masking policy implementation

- pkg/resources/grant_privileges_to_role.go
- pkg/resources/grant_privileges_to_role_acceptance_test.go
The grant read operation can cause infinite plan and grant privileges on every `terraform apply`. It can occur when role_name is defined with the quotes. The solution for it is to compare always without quotes as one of the sides already uses AccountObjectIdentifier which doesn't save information if the identifier was originally quoted or not.
> fix: grant read opeartion

- .github/workflows/release.yml
- .goreleaser.yml
Result of #2384.
The formatting in goreleaser env template was bad, therefore `CGO_ENABLED=1` was used as a default (because invalid envs are being ignored, check: https://goreleaser.com/customization/builds/#builds) for every build distro.
> fix: Fix whitespace in goreleaser envs

- .goreleaser.yml
Getting error when performing the release:
`clang: error: argument unused during compilation: '-arch x86_64' [-Werror,-Wunused-command-line-argument]
`
It seems like CGO [isn't supported with goreleaser](https://goreleaser.com/cookbooks/cgo-and-crosscompiling/) and instead it recommends using [goreleaser-cross](https://github.com/goreleaser/goreleaser-cross) instead.  example goreleaser file is shown here: https://github.com/goreleaser/goreleaser-cross-example/blob/master/.goreleaser.yaml. This may be tricky to do, as we would be having to different goreleasers running, one for cross compliatied binaries and the other for native binaries. In the meantime, rolling back change.
> fix: Update .goreleaser.yml

- pkg/sdk/application_packages_def.go
- pkg/sdk/application_packages_gen.go
- pkg/sdk/application_packages_gen_test.go
- pkg/sdk/application_packages_validations_gen.go
- pkg/sdk/testint/application_packages_integration_test.go
Follow up PR from discussion in original PR 
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2323#discussion_r1444581864
Fixing Unset to use commas, allowing multiple unsets
> fix: app-pkg unset

- pkg/sdk/file_format.go
- pkg/sdk/file_format_test.go
- pkg/sdk/testint/application_roles_gen_integration_test.go
- pkg/sdk/testint/external_tables_integration_test.go
- pkg/sdk/testint/file_format_integration_test.go
- pkg/sdk/testint/helpers_test.go
- pkg/sdk/testint/pipes_integration_test.go
- pkg/sdk/testint/stages_gen_integration_test.go
- pkg/sdk/testint/streams_gen_integration_test.go
- pkg/sdk/testint/tables_integration_test.go
Follow-up for https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2163
- Added missing tests for external resources (only s3compat was left, but created a separate ticket for later)
- Fixed set comment on the file format + tests for it
- File functions like GET, LS, COPY INTO, etc. are left for later
- Cleanup helper functions for creating stages
> feat: stages migration follow-up

- pkg/sdk/testint/pipes_integration_test.go
- pkg/sdk/testint/streams_gen_integration_test.go
Changes in tests:
- pipe test, that were intentionally documenting the incorrect behavior; they started to fail after Snowflake 8.3.1 release; they have been adjusted
- stream test was failing because of multiple objects named the same; random name added
> fix: Adjust tests after Snowflake behavior change

- pkg/resources/database.go
- pkg/resources/database_acceptance_test.go
- pkg/resources/dynamic_table.go
- pkg/resources/dynamic_table_acceptance_test.go
- pkg/resources/oauth_integration.go
- pkg/resources/oauth_integration_acceptance_test.go
- pkg/resources/testdata/TestAcc_DynamicTable_issue2329/1/test.tf
- pkg/resources/testdata/TestAcc_DynamicTable_issue2329/1/variables.tf
- pkg/sdk/client.go
- pkg/sdk/poc/main.go
- pkg/sdk/testint/streamlits_integration_test.go
Fix a few small bugs
All of them have appropriate tests showing the error before and correct behavior after.
`BLOCKED_ROLES_LIST ` was cast to wrong type which caused panic (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/oauth_integration.go#L313).
No old config for blocked roles was causing empty list access (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/e3d086eddc05e0d4963234f82e09e174a018bb08/pkg/resources/database.go#L271). Some other errors were discovered, so implementation was slightly improved.
Cutting query from returned DDL was too greedy (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/e3d086eddc05e0d4963234f82e09e174a018bb08/pkg/resources/dynamic_table.go#L204). It is not that simple to read the …
> fix: Fix some bugs

- pkg/resources/grant_privileges_to_role.go
- pkg/resources/grant_privileges_to_role_acceptance_test.go
Fix read by trimming any quotes from the specified identifier
> fix: snowflake_grant_privileges_to_role read

- pkg/datasources/parameters_acceptance_test.go
- pkg/sdk/parameters.go
- pkg/sdk/parameters_impl.go
Fix for https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2353.
Issue 1 - TRANSACTION_ABORT_ON_ERROR couldn't be set
- I added TRANSACTION_ABORT_ON_ERROR to the available set of parameters and added a test that shows it can be set now
Issue 2 - QUOTED_IDENTIFIERS_IGNORE_CASE couldn't be set because of the invalid syntax produced by our SDK
- I removed the single_quotes that were causing the invalid syntax error and added a test to prove it works now
> fix: parameter issues

- pkg/sdk/testint/application_packages_integration_test.go
- pkg/sdk/testint/applications_integration_test.go
- pkg/sdk/testint/helpers_test.go
- pkg/sdk/testint/tables_integration_test.go
There were some tests failing on the CI since Thursday/Friday (2 in application packages, multiple in application and one for table cloning). The same tests were passing "locally". The reason for all of them was the assumption that the account level parameter `DATA_RETENTION_TIME_IN_DAYS` is set to `1` (default). For some reason, on our CI account, it was changed to `0` (either by some test in which cleanup failed or manually by someone). I did two things so that our tests pass again:
- reverted the param to `1` default
- prepared a fix for the tests, as to not make assumptions about this param (or for table cloning setting it temporarily to `1` and reverting to the previous value after the test)
> fix: Fix tests that base on default data retention

- docs/resources/user_password_policy_attachment.md
- examples/resources/snowflake_user_password_policy_attachment/resource.tf
- pkg/resources/task.go
- pkg/resources/task_acceptance_test.go
- pkg/resources/testdata/TestAcc_Task_issue2036/1/test.tf
- pkg/resources/testdata/TestAcc_Task_issue2036/1/variables.tf
- pkg/resources/testdata/TestAcc_Task_issue2036/2/test.tf
- pkg/resources/testdata/TestAcc_Task_issue2036/2/variables.tf
- pkg/resources/testdata/TestAcc_Task_issue2207/1/test.tf
- pkg/resources/testdata/TestAcc_Task_issue2207/1/variables.tf
- pkg/sdk/tasks_impl_gen.go
- pkg/sdk/tasks_test.go
Related issues: #2036 #2207 #2346.
- (#2207) The reason was the change in parsing the `SHOW TASKS` response for `after` parameter. In earlier versions, the parsing was incorrect for the identifiers containing dot characters. The new one fixed the dot case but Snowflake identifiers surprised us one more time, and the basic case, without any `"` was not supported correctly.
- (#2036) There is no way to unset `when` currently in Snowflake. We don't want to always `ForceNew` for when change. For that reason we run forceNew conditionally using `customdiff.ForceNewIfChange`.
- (#2346) Waiting for answers but maybe this fix will also solve this issues.
> fix: Fix task related issues

- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- pkg/resources/grant_privileges_to_role_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/OnAllPipes/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/OnAllPipes/variables.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToDatabaseRole/OnAllPipes/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToDatabaseRole/OnAllPipes/variables.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToRole/OnAllPipes/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToRole/OnAllPipes/variables.tf
- pkg/sdk/grants_impl.go
- pkg/sdk/testint/grants_integration_test.go
`granting privileges on all pipes to role/database role` is not allowed in Snowflake. As it was just one case, we decided to create an internal workaround that would make `on_all pipes` work as it was supported by Snowflake. The workaround works as follows:
- check if on_all pipes are called
- fetch pipes (in database or in schema; depending on what was in the original request)
- loop through the pipes and grant/revoke privileges on them
- created integration tests for the SDK and acceptance tests for `snowflake_grant_privileges_to_role`, `snowflake_grant_privileges_to_account_role`, and `snowflake_grant_privileges_to_database_role`
> Note: grant on_future pipes works as intended
[Reference](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters) (check the …
> feat: create a workaround for granting privileges on all pipes

- docs/resources/table.md
- pkg/resources/external_function.go
- pkg/resources/external_function_acceptance_test.go
- pkg/resources/external_function_state_upgraders.go
- pkg/resources/function_acceptance_test.go
- pkg/resources/function_state_upgraders.go
- pkg/resources/notification_integration.go
- pkg/resources/notification_integration_acceptance_test.go
- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
- pkg/resources/procedure_state_upgraders.go
- pkg/resources/table.go
- pkg/sdk/testint/views_gen_integration_test.go
- pkg/sdk/views_impl_gen.go
- Removed incorrect validation on procedure resources that were causing failure of the following tests:
- `TestAcc_Procedure_Java`
- `TestAcc_Procedure_Scala`
- Removed incorrect deprecation from table resource (#2488)
- Fixed ShowByID for views (#2506)
- Fixed notification_integration resource warnings for deprecated parameters (#2501)
- Fixed external functions and procedure - state migrations similar to functions (#2490)
References: #2501 #2506 #2488 #2490
> fix: Fix few smaller issues

- pkg/resources/grant_database_role_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantDatabaseRole/share/test.tf
- pkg/sdk/grants.go
Fixes: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2410
The root cause of the issue was that in SHOW GRANTS conversion from row representation to SDK object representation, we had a special case for shares that would split it on dot. Share may have only one part and this change adds support for such a situation. Additionally, it was covered by an existing test that was commented out and was waiting for the `snowflake_grant_privileges_to_share` resource.
> fix: SHOW GRANTS mapping for share data type

- pkg/resources/unsafe_execute.go
- pkg/resources/unsafe_execute_acceptance_test.go
Add custom diff to query_results.
References #2491
> fix: Fix query_results in unsafe_execute resource

- pkg/resources/grant_database_role.go
- pkg/resources/grant_database_role_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantDatabaseRole/issue2402/test.tf
- pkg/resources/testdata/TestAcc_GrantDatabaseRole/issue2402/variables.tf
> fix: Granting database roles

- docs/index.md
- examples/provider/provider.tf
- pkg/resources/grant_database_role_acceptance_test.go
- pkg/resources/resource_monitor_acceptance_test.go
- pkg/resources/stage.go
- pkg/resources/task.go
- pkg/resources/task_acceptance_test.go
- Introduce the requested change inside the docs #2509 
- Attempt to fix `TestAcc_ResourceMonitor` flaky test
- Set random name in test from #2511
- Add error log to task suspension (in the place it fails on CI mostly)
> fix: Fix few tests

- pkg/resources/grant_privileges_to_account_role.go
- pkg/resources/grant_privileges_to_database_role.go
- pkg/resources/grant_privileges_to_share.go
To prevent warning spam for new grant resources, I replaced the warning diag with an info log stating that with the chosen option no Snowflake changes will be reflected by the Terraform config. (maybe the log message could be changed a little to make if more obvious to the users?)
> chore: replace warning in new grant resources with info log

- MIGRATION_GUIDE.md
- pkg/datasources/failover_groups_acceptance_test.go
- pkg/resources/failover_group_acceptance_test.go
- pkg/sdk/failover_groups.go
- `SHOW FAILOVER GROUPS` return `PARAMETERS` instead of `ACCOUNT PARAMETERS`
- acceptance tests were unskipped by adding environment variable
- SDK integration tests still stay skipped
References: #2517
> fix: Fix ACCOUNT PARAMETERS option failover group resource

- docs/resources/view.md
- pkg/resources/table_acceptance_test.go
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
- pkg/sdk/tables.go
- pkg/sdk/tables_test.go
- Fixed clustering for table_resource (clustering with nested functions are parsed correctly now)
- Adjusted view resource (`copy_grants` require `or_replace`) and corrected the documentation
References: #2110 #2495 #2519
> fix: Fix various small problems

- pkg/acceptance/testenvs/testing_environment_variables.go
- pkg/resources/failover_group.go
- pkg/resources/failover_group_acceptance_test.go
- pkg/resources/pipe.go
- pkg/resources/pipe_acceptance_test.go
- pkg/sdk/failover_groups.go
- pkg/sdk/testint/failover_groups_integration_test.go
- pkg/sdk/testint/helpers_test.go
- Run two separate alters in failover group resource
- Handle `.` in failover ids
- Trim leading and trailing space for pipe statement diff suppression
- Unskip part of the integration tests for failover groups
References: #2544 #2560
> fix: Fix failover group alter syntax and suppression for pipe statement

- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_role_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantPrivilegesToRole/OnAccount/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToRole/OnAccount/variables.tf
- pkg/resources/validators.go
- pkg/resources/validators_test.go
Fixes: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2548
Fails because identifier validation doesn't work well for account object identifiers (that may contain dots).
> fix: loosen identifier field validation for account object identifiers

- pkg/resources/function.go
- pkg/resources/function_acceptance_test.go
- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
- Demote warning to info for procedures and functions
- use returned volatility
- fix import tests
References: #2536
> fix: Demote warning to info and set volatility for procedures and functions

- docs/resources/task_grant.md
`task_grant` terraform import doco isn't correct, not able to get the example working.
Looks like the doco is missing the `on_all` field
*
> fixing task grant import doco to make it work

- docs/resources/grant_privileges_to_account_role.md
- docs/resources/task_grant.md
- examples/resources/snowflake_grant_privileges_to_account_role/resource.tf
- examples/resources/snowflake_task_grant/import.sh
- pkg/resources/grant_privileges_to_account_role.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/ImportedPrivilegesOnSnowflakeDatabase/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/ImportedPrivilegesOnSnowflakeDatabase/variables.tf
- templates/resources/grant_privileges_to_account_role.md.tmpl
Fix for: #1998 and #2366
Changes
- Because it's the default database it fulfills our `if` checks for futures, so added a check for `name != SNOWFLAKE`
- The second check was added to make it possible to grant privileges on applications by setting object_type to DATABASE
- Those cases were added to the documentation for the `snowflake_grant_privilege_to_account_role` resource
- Added acceptance test that would check if SNOWFLAKE database could be made with `object_type = DATABASE`
- I also added a follow-up ticket to add additional tests for applications when they are available.
> fix: support snowflake application as database

- docs/index.md
- docs/resources/role_grants.md
- examples/additional/deprecated_resources.MD
- pkg/resources/role_grants.go
Fix the wrong resource being referenced for deprecated snowflake_role_grants
Ref: #2599 #2600
> fix: Fix the deprecation message for snowflake_role_grants

- .github/workflows/tests.yml
- pkg/acceptance/testenvs/testenvs_test.go
- pkg/acceptance/testenvs/testing_environment_variables.go
- pkg/acceptance/testing.go
- pkg/datasources/failover_groups_acceptance_test.go
- pkg/provider/provider.go
- pkg/provider/provider_acceptance_test.go
- pkg/resources/failover_group_acceptance_test.go
- pkg/resources/failover_group_grant_acceptance_test.go
- pkg/sdk/client_integration_test.go
- pkg/sdk/testint/failover_groups_integration_test.go
- pkg/sdk/testint/setup_test.go
- Introduce acceptance test context
- Expose default config in integration tests
- Remove not needed test envs
- Expose envs to test jobs (because of [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv) and [that](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow))
- Skip the tests requiring business critical account
> chore: Fix env variables for tests

- pkg/resources/table.go
- pkg/resources/table_acceptance_test.go
Fix for #2588
In the alter column call collate was always added which caused the error non-text (and probably text too) data types
* [ALTER TABLE](https://docs.snowflake.com/en/sql-reference/sql/alter-table)
> fix: alter table column data type

- CONTRIBUTING.md
Fixing the link to `.github/workflows/title-lint.yml` file from CONTRIBUTING.md in regular expression text.
**Broken link**
[regular expression](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/.github/workflows/titleLint.yml#L17)
**Fixed link**
[regular expression](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/.github/workflows/title-lint.yml#L17)
> docs: fix the link to .title-lint.yml file in CONTRIBUTING.md file

- docs/resources/database.md
- pkg/resources/database.go
Added information in the `name` and `comment` fields of the snowflake_database resource. As well as improved display of options in the `from_replica` and `data_retention_time_in_days` fields.
https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/database
> docs: improving the documentation of the snowflake_database resource (new PR)

- MIGRATION_GUIDE.md
Adjusting migration guide to mention that in the `snowflake_database.from_share.provider` we were/are expecting an account locator format. Previously it was possible to use orgname+accountname format, but now (from version 0.87.0) it won't be, and now only the account locator should be used.
> fix: migration guide for databases created from share

- pkg/resources/user_password_policy_attachment.go
- pkg/resources/user_password_policy_attachment_acceptance_test.go
- pkg/sdk/policy_references.go
Our test for the user password policy attachment resource started failing. It detected two issues with current implementation that were changed:
- POLICY_STATUS should be a nullable field (this is something new because the test started failing just recently)
- policyReferences returned by GetForEntity should be filtered by `PASSWORD_POLICY` PolicyKind to resolve clashes with other policy types
> feat: user password policy attachment

- docs/resources/view.md
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
- pkg/snowflake/parser_test.go
To import the secure view the role owning the view is needed. As https://docs.snowflake.com/en/sql-reference/sql/create-view#usage-notes state:
> By design, the [SHOW VIEWS](https://docs.snowflake.com/en/sql-reference/sql/show-views) command does not provide information about secure views. To view information about a secure view, you must use the [VIEWS](https://docs.snowflake.com/en/sql-reference/info-schema/views) view in the Information Schema and you must use the role that owns the view.
This change:
- tests and proves #2640 
- checks the parser for view using union statement (that was the first idea for the source of error)
- handles the empty `text` from `SHOW VIEWS` command gracefully (no panic like before)
- adds a proper description with documentation link to the `snowflake_view` …
> fix: Fix handling secure views read and import

- MIGRATION_GUIDE.md
- docs/resources/procedure.md
- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
- pkg/resources/schema.go
- pkg/resources/schema_acceptance_test.go
- pkg/resources/testdata/TestAcc_Procedure/complex/test.tf
- pkg/resources/testdata/TestAcc_Procedure/complex/variables.tf
- pkg/resources/testdata/TestAcc_Procedure/java/test.tf
- pkg/resources/testdata/TestAcc_Procedure/java/variables.tf
- pkg/resources/testdata/TestAcc_Procedure/javascript/test.tf
- pkg/resources/testdata/TestAcc_Procedure/javascript/variables.tf
- pkg/resources/testdata/TestAcc_Procedure/python/test.tf
- pkg/resources/testdata/TestAcc_Procedure/python/variables.tf
- pkg/resources/testdata/TestAcc_Procedure/scala/test.tf
- pkg/resources/testdata/TestAcc_Procedure/scala/variables.tf
- pkg/resources/testdata/TestAcc_Procedure/sql/test.tf
- pkg/resources/testdata/TestAcc_Procedure/sql/variables.tf
- pkg/resources/warehouse_acceptance_test.go
- pkg/sdk/parameters.go
- pkg/sdk/parameters_impl.go
- pkg/sdk/parameters_impl_test.go
- pkg/sdk/warehouses.go
- pkg/sdk/warehouses_test.go
- Fix unsetting comment on schema (references #2606)
- Fix changing the execute as on procedure (references #2642)
- Fix setting only min cluster count on warehouse (references #2652)
- Add missing S3_STAGE_VPCE_DNS_NAME session parameter (references #2653)
> fix: Fix issues 2606 2642 2652 2653

- pkg/resources/dynamic_table.go
- pkg/sdk/dynamic_table.go
- pkg/sdk/testint/dynamic_table_integration_test.go
[BCR-1543](https://docs.snowflake.com/en/release-notes/bcr-bundles/2024_02/bcr-1543#return-value-behavior-for-the-show-dynamic-table-function) introduced changes to the dynamic table output for `scheduling_state` column.
> fix: Adjust dynamic tables after BCR-1543

- pkg/resources/task.go
- pkg/sdk/tasks_gen.go
- pkg/sdk/tasks_impl_gen.go
- pkg/sdk/testint/tasks_gen_integration_test.go
Refactor previously planned function for task suspension, which is also necessary to push the grant ownership resource forward.
[CREATE TASK](https://docs.snowflake.com/en/sql-reference/sql/create-task)
> feat: Introduce shared function to suspend task roots

- pkg/resources/grant_privileges_to_account_role.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
Fixes: #2459
The issue was related to the fact that the Read operation is only concerned about privileges (with_grant_option is also taken into consideration, but it's never set). Given this configuration:
```terraform
resource "snowflake_grant_privileges_to_account_role" "test" {
account_role_name = "TEST_ROLE"
privileges = ["TRUNCATE"]
on_schema_object {
object_type = "TABLE"
object_name = "TEST_DATABASE.TEST_SCHEMA.TEST_TABLE"
}
with_grant_option = true
}
```
after apply we run the following commands by hand
```sql
revoke truncate on table test_table from role test_role;
grant truncate on table test_table to role test_role; -- notice we don't add "with grant option" which our resource should detect
```
Now, when we run `plan` or `apply` our resource is seeing a drift (the "TRUNCATE" …
> fix: with_grant_option diff drift

- pkg/resources/masking_policy.go
- pkg/resources/masking_policy_acceptance_test.go
ReadMaskingPolicy function increased signature by the number of columns when there were multiple columns in the Masking Policy.
Therefore, a masking policy with multiple columns was always in a state where differences occurred.
* fixes #2054
> fix: diffs always occurring when multiple columns exist

- pkg/acceptance/testing.go
- pkg/resources/object_parameter_acceptance_test.go
- pkg/sdk/parameters.go
When issuing `object_type = "USER"` via the `snowflake_object_parameter` resource  the `ShowObjectParameter` function did not handle the `ObjectTypeUser` which led to invalid ObjectType errors.
* ~~Fixes #2669~~ Actually, I re-reading this issue I don't think it fixes this error.
> fix: Adds case statement for ObjectTypeUser in ShowObjectParameter.

- pkg/acceptance/testing.go
- pkg/datasources/grants_acceptance_test.go
- pkg/resources/database_acceptance_test.go
- pkg/resources/dynamic_table_acceptance_test.go
- pkg/resources/external_table_acceptance_test.go
- pkg/resources/function_acceptance_test.go
- pkg/resources/grant_ownership_acceptance_test.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- pkg/resources/grant_privileges_to_share_acceptance_test.go
- pkg/resources/materialized_view_acceptance_test.go
- pkg/resources/schema_acceptance_test.go
- pkg/resources/table_acceptance_test.go
- pkg/resources/tag_masking_policy_association_acceptance_test.go
- pkg/resources/unsafe_execute_acceptance_test.go
- pkg/resources/user_acceptance_test.go
- pkg/resources/view_acceptance_test.go
- pkg/resources/warehouse_acceptance_test.go
- pkg/sdk/helper_test.go
Result of SNOW-935947.
- the SDK default client was already setup earlier in the acceptance tests context; used in all valid places
- added secondary client setup to acceptance tests context and used in valid places
> chore: Initialize the SDK client in fewer places

- docs/resources/database.md
- examples/resources/snowflake_database/resource.tf
- pkg/resources/database.go
- pkg/resources/testdata/TestAcc_GrantOwnership/OnObject_DatabaseRole_ToAccountRole/test.tf
The documentation for the `snowflake_database` resource's `from_share` property has been updated to reflect the necessary changes described in the migration guide v0.86.0 to v0.87.0. This update addresses the modification in the configuration format from `<org_name>.<account_name>` to `<account_locator>`, ensuring consistency with identifier types across the platform.
* issue: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2708
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/resources/database.md
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v0860--v0870
> docs: update  documentation in snowflake_database resource (#2708)

- MIGRATION_GUIDE.md
- pkg/resources/file_format.go
- pkg/resources/file_format_acceptance_test.go
- pkg/resources/function.go
- pkg/resources/function_acceptance_test.go
- pkg/resources/masking_policy.go
- pkg/resources/masking_policy_acceptance_test.go
- pkg/resources/materialized_view.go
- pkg/resources/password_policy.go
- pkg/resources/password_policy_acceptance_test.go
- pkg/resources/pipe.go
- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
- pkg/resources/schema.go
- pkg/resources/schema_acceptance_test.go
- pkg/resources/table.go
- pkg/resources/table_acceptance_test.go
- pkg/resources/table_constraint.go
- pkg/resources/table_constraint_acceptance_test.go
- pkg/resources/user.go
- pkg/resources/user_acceptance_test.go
- pkg/resources/view.go
- pkg/resources/view_acceptance_test.go
- pkg/resources/warehouse.go
- pkg/resources/warehouse_acceptance_test.go
This change fixes all of the Updates that were performing re-names to always setId at the end of the rename operation as well as updating id that was used in the later operations. Also, the `ForceNew`s were removed in cases where rename was also handled in the Update. Test cases were added to show that rename is going through Update and not DeleteAndCreate operation + additional param is always changed to see if other operations are affected by the previous rename operation. The table constraint was adjusted and cannot support the rename for now (until the Read operation is working #2683). Migration guide updated for behavioral changes.
> fix: renames in update operations

- MIGRATION_GUIDE.md
- pkg/resources/common.go
- pkg/resources/stage.go
- pkg/resources/stage_acceptance_test.go
- pkg/resources/testdata/TestAcc_Stage_CreateAndAlter/test.tf
- pkg/resources/testdata/TestAcc_Stage_CreateAndAlter/variables.tf
- pkg/sdk/tags_test.go
- pkg/sdk/tags_validations.go
- Fix number of allowed values in tags
- Suppress diff for stages `on_error`
> fix: Fix issues #2679 #2721

- pkg/acceptance/helpers/database_client.go
- pkg/acceptance/helpers/test_client.go
- pkg/acceptance/testing.go
- pkg/resources/database_acceptance_test.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- pkg/resources/schema_acceptance_test.go
- pkg/sdk/testint/client_unsafe_extensions_integration_test.go
- pkg/sdk/testint/context_functions_integration_test.go
- pkg/sdk/testint/database_role_integration_test.go
- pkg/sdk/testint/databases_integration_test.go
- pkg/sdk/testint/external_functions_integration_test.go
- pkg/sdk/testint/failover_groups_integration_test.go
- pkg/sdk/testint/file_format_integration_test.go
- pkg/sdk/testint/helpers_test.go
- pkg/sdk/testint/replication_functions_integration_test.go
- pkg/sdk/testint/sessions_integration_test.go
- pkg/sdk/testint/setup_test.go
- pkg/sdk/testint/shares_integration_test.go
- pkg/sdk/testint/tags_integration_test.go
- Extract helpers in a separate package, where acceptance (both resource and datasource ones) and integration tests have access
- Prepare a file structure for different helpers to reduce the clutter
- Move database related helper methods and remove some from acceptance tests
> chore: Cleanup helpers poc

- pkg/resources/account.go
- pkg/resources/account_password_policy_attachment.go
- pkg/resources/failover_group.go
- pkg/resources/object_parameter.go
- pkg/resources/resource_monitor.go
- pkg/resources/role.go
- pkg/resources/table_column_masking_policy_application.go
SNOW-1003311 
Fixes: Not invoking Read after Create/Update (e.g. [#2252](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2252/files#diff-840246f685e775bcf2dee809f30f112848676899dd47e5ef076598dd9e8536b3L220))
> fix: read after create

- pkg/resources/testdata/TestAcc_GrantDatabaseRole/share/test.tf
- pkg/resources/user_password_policy_attachment_acceptance_test.go
- pkg/sdk/testint/masking_policy_integration_test.go
Added missing depends on and set warehouse in failing test.
> fix: Fix setup for two tests

- MIGRATION_GUIDE.md
- pkg/resources/procedure.go
- pkg/resources/procedure_acceptance_test.go
Introduce a fix for arguments but not for the return_type
> fix: Prove problems with procedure resource data types

- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- Snowflake behavior was fixed for ML class permissions (References: #2651)
> fix: Update the tests after snowflake bugfix

- pkg/sdk/testint/grants_integration_test.go
- pkg/sdk/testint/row_access_policies_gen_integration_test.go
Some tests failed in
https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/9187815690/job/25266290438?pr=2830.
This probably happened because more resources were returned by Show. Slice length asserts are corrected.
`TestInt_EventTables/alter_event_table:_add_and_drop_row_access_policies` was not fixed for now.
> fix: Fix failing integration tests

- pkg/datasources/external_tables.go
- pkg/resources/external_table.go
- pkg/sdk/dto-builder-generator/main.go
- pkg/sdk/external_tables_dto_builders_gen.go
- pkg/sdk/external_tables_impl.go
- pkg/sdk/poc/README.md
- pkg/sdk/testint/external_tables_integration_test.go
- pkg/sdk/testint/streams_gen_integration_test.go
Accept non-pointer values in the generated builder methods. Now the nested requests have to be explicitly unreferenced, but two additional cases could be added to resolve this "issue". There's only a special case for strings which shouldn't be set whenever they're optional and the input value is equal to an empty string, because: 
1. that would be a rare case to have an empty string in Snowflake.
2. empty strings are treated as non-set values in Terraform.
The improved generator was tested and used as an example on the external table.
> chore: accept non-pointer values in the generated builder methods

- pkg/acceptance/helpers/common.go
- pkg/acceptance/testing.go
- pkg/datasources/parameters_acceptance_test.go
- pkg/sdk/testint/setup_test.go
Setting `QUOTED_IDENTIFIERS_IGNORE_CASE` in `TestAcc_Parameters_QuotedIdentifiersIgnoreCaseCanBeSet` was interfering with the tests being run on other branches. It resulted in seemingly random `Database 'XYZ' does not exist or not authorized` errors for database that exists, works moments before and moments after. Sequence of example statements:
```
-- 2024-05-28 11:28:34.634 +0000
-- CREATE MATERIALIZED VIEW "int_test_db_IT_C0E0DFE82EF6223390C3723866862A273A406F10"."int_test_sc_IT_C0E0DFE82EF6223390C3723866862A273A406F10"."AFKRZIIT_C0E0DFE82EF6223390C3723866862A273A406F10" CLUSTER BY ("ID") AS SELECT id FROM "int_test_db_IT_C0E0DFE82EF6223390C3723866862A273A406F10"."int_test_sc_IT_C0E0DFE82EF6223390C3723866862A273A406F10"."VYODPJIT_C0E0DFE82EF6223390C3723866862A273A406F10"
...
-- …
```
> fix: Fix QUOTED_IDENTIFIERS_IGNORE_CASE parameter test

- docs/technical-documentation/restoring_lost_data.md
- v1-preparations/CHANGES_BEFORE_V1.md
Done as part of SNOW-1325226
Create documentation about data recovery (calling unset)
Add a disclaimer about the new "policy" on default values in the upcoming refactored resources.
> chore: Add documentation on unset and defaults

- pkg/resources/common.go
- pkg/resources/stage.go
- pkg/resources/stage_acceptance_test.go
We are getting permadiff on stage `file_format` parameter when it contains quotes, as it used to be the case with `copy_options` (see https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2679)
To fix it, re-using the same `DiffSuppressFunc` seems to do the trick.
> fix: use suppressQuoting to fix stage file_format permadiff

- Makefile
- pkg/helpers/helpers.go
- pkg/internal/util/retry.go
- pkg/resources/account.go
- pkg/resources/alert.go
- pkg/resources/managed_account.go
- pkg/resources/task.go
- pkg/resources/warehouse.go
- pkg/resources/warehouse_acceptance_test.go
- pkg/sdk/warehouses.go
Warehouses redesign part4 (continuation of https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2890):
- handle snowflake parameters using computed values
- handle waiting for suspension
Common:
- move retry to utils (to avoid dependencies cycle)
Still missing (next PRs):
- encapsulate 3-value boolean logic
- extract and generalize part of read logic
- Move GetPropertyAsPointerWithPossibleZeroValues and use for database parameters too
> feat: Warehouse redesign part4

- docs/technical-documentation/resource_migration.md
docs/technical-documentation/resource_migration.md contained the following false statement:
> for_each cannot be used when generating with import blocks
Since terraform 1.7 that isn't true so this commit updates that document accordingly.
Tests not required, its just a change to some documentation.
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2928
> docs:Remove false statement about import blocks

- pkg/resources/cortex_search_service.go
- pkg/resources/cortex_search_service_acceptance_test.go
- pkg/resources/testdata/TestAcc_CortexSearchService_basic/2/variables.tf
Fixes the issue pointed out in https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2860#issuecomment-2243785375
Verified in my local deployment
PTAL @sfc-gh-asawicki @sfc-gh-mloring
> fix: ATTRIBUTE set(string) parsing for cortex search service

- MIGRATION_GUIDE.md
- pkg/resources/cortex_search_service_acceptance_test.go
- pkg/resources/testdata/TestAcc_CortexSearchService_basic/1/test.tf
- pkg/resources/testdata/TestAcc_CortexSearchService_basic/2/test.tf
- pkg/resources/testdata/TestAcc_CortexSearchService_basic/3/test.tf
- pkg/resources/testdata/TestAcc_CortexSearchService_basic/3/variables.tf
- pkg/resources/warehouse.go
- pkg/resources/warehouse_acceptance_test.go
- pkg/sdk/testint/application_packages_integration_test.go
- pkg/sdk/testint/grants_integration_test.go
- pkg/sdk/testint/users_integration_test.go
- v1-preparations/CHANGES_BEFORE_V1.md
- Unskip cortex acceptance test
- Fix application package tests after recent SF release
- Relax warehouse parameter validations upper bounds
- Fix user tests after validation change for one of the params
- Fix cortex grant tests (they started to work)
References: #2948
> fix: Fix tests and relax warehouse validations

- pkg/resources/secondary_database.go
- pkg/resources/shared_database.go
- pkg/resources/storage_integration.go
- pkg/resources/storage_integration_acceptance_test.go
- pkg/resources/table.go
- pkg/resources/table_acceptance_test.go
- pkg/resources/validators.go
Apply fixes for:
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2985
- https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2644
> fix: identifier issues

- MIGRATION_GUIDE.md
- pkg/acceptance/helpers/stage_client.go
- pkg/internal/util/strings.go
- pkg/internal/util/strings_test.go
- pkg/resources/helpers.go
- pkg/resources/helpers_test.go
- pkg/resources/stage.go
- pkg/resources/stage_acceptance_test.go
- pkg/resources/table.go
- pkg/resources/table_acceptance_test.go
- pkg/sdk/data_types.go
- pkg/sdk/data_types_test.go
Address two issues: #2972 and #3007:
- Correctly handle renamed/deleted stage
- Handle data type diff suppression better for text and number in the table resource
References: #2972 #3007
> fix: Fix issues 2972 and 3007

- pkg/acceptance/helpers/user_client.go
- pkg/manual_tests/README.md
- pkg/manual_tests/user_default_database_and_role/test.md
- pkg/resources/user_acceptance_test.go
- Address https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3034#discussion_r1742132935
- Add a manual test that shows the behavior of the default namespace and default role for a user when logging in with different conditions.
> chore: Improve user test and add manual test for user default database and role

- pkg/sdk/sweepers_test.go
- Transfer ownership if the current role does not have it
> fix: Fix sweepers for warehouse and database

- pkg/acceptance/helpers/database_role_client.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- pkg/sdk/grants.go
- Address the issue: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3050 about granting usage on future models (I couldn't provide the test on non-future model because the only way of creating such model is with python snowpark and it's not that easy, I tried).
- Fix other failing test in grants.
> fix: Add fix for model grants

- pkg/sdk/poc/README.md
- pkg/sdk/secrets_def.go
- pkg/sdk/secrets_dto_builders_gen.go
- pkg/sdk/secrets_dto_gen.go
- pkg/sdk/secrets_gen.go
- pkg/sdk/secrets_gen_test.go
- pkg/sdk/secrets_impl_gen.go
- pkg/sdk/secrets_validations_gen.go
- pkg/sdk/testint/secrets_gen_integration_test.go
- changed secret validation to use generated validation without manual adjustments
- changed parsing StringArrays to use `ParseCommaSeparatedStringArray()`
- removed known issue with ConflictingFields from sdk generator README
- removed comments and replaced them with jira issues
> chore: Secret Validation change

- Makefile
- main.go
- pkg/sdk/views_gen_test.go
To be able to run successfully with go 1.23.2.
> chore: Bump golang-ci lint to 1.61

- pkg/datasources/current_account_acceptance_test.go
- pkg/datasources/current_role_acceptance_test.go
- pkg/datasources/database_acceptance_test.go
- pkg/datasources/database_role_acceptance_test.go
- pkg/datasources/database_roles_acceptance_test.go
- pkg/datasources/databases_acceptance_test.go
- pkg/datasources/external_tables_acceptance_test.go
- pkg/datasources/file_formats_acceptance_test.go
- pkg/datasources/network_policies_acceptance_test.go
- pkg/datasources/parameters_acceptance_test.go
- pkg/datasources/pipes_acceptance_test.go
- pkg/datasources/schemas_acceptance_test.go
- pkg/datasources/security_integrations_acceptance_test.go
- pkg/datasources/sequences_acceptance_test.go
- pkg/datasources/shares_acceptance_test.go
- pkg/datasources/streamlits_acceptance_test.go
- pkg/datasources/streams_acceptance_test.go
- pkg/datasources/system_get_aws_sns_iam_policy_acceptance_test.go
- pkg/datasources/system_get_privatelink_config_acceptance_test.go
- pkg/datasources/system_get_snowflake_platform_info_acceptance_test.go
- pkg/datasources/tasks_acceptance_test.go
- pkg/datasources/users_acceptance_test.go
- pkg/datasources/warehouses_acceptance_test.go
- Add missing PreCheck to each data source test
> chore: Add pre check to each datasource

- pkg/resources/stream_on_view.go
Main started to fail because of using a struct that was renamed - see https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/11513272472
> fix: Fix main

- docs/resources/stream_on_directory_table.md
- docs/resources/stream_on_external_table.md
- docs/resources/stream_on_table.md
- docs/resources/stream_on_view.md
- pkg/acceptance/bettertestspoc/assert/resourceassert/stream_on_directory_table_resource_gen.go
- pkg/acceptance/bettertestspoc/assert/resourceassert/stream_on_external_table_resource_gen.go
- pkg/acceptance/bettertestspoc/assert/resourceassert/stream_on_table_resource_gen.go
- pkg/acceptance/bettertestspoc/assert/resourceassert/stream_on_view_resource_gen.go
- pkg/acceptance/helpers/stream_client.go
- pkg/resources/custom_diffs.go
- pkg/resources/stream_common.go
- pkg/resources/stream_on_directory_table.go
- pkg/resources/stream_on_directory_table_acceptance_test.go
- pkg/resources/stream_on_external_table.go
- pkg/resources/stream_on_external_table_acceptance_test.go
- pkg/resources/stream_on_table.go
- pkg/resources/stream_on_table_acceptance_test.go
- pkg/resources/stream_on_view.go
- pkg/resources/stream_on_view_acceptance_test.go
- pkg/sdk/streams_dto_gen.go
- handle external type changes in stream resources
> fix: Handle external type changes in stream resources

- pkg/resources/object_renaming_acceptance_test.go
Follow-up for https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3130#discussion_r1802982850.
Tests joined from standalone tests to parameterized ones. Two tests were left, because:
- First represents the non-deterministic behavior of Terraform and it would be good to have it separated
- Second, is also unique and tests the correlation of config order to execution order
Commented test cases are there intentionally because normally they were skipped due to errors that cannot be asserted with terraform testing framework.
**Question:** The "important" tests are still not separated from the regular object renaming tests because they're currently failing in a way they're not assertable by the terraform provider testing framework (they will always fail). In this case, should we …
> chore: join object renaming tests into parameterized ones

- docs/technical-documentation/object_renaming_research_summary.md
- Add object renaming research summary
- Write an announcement and link this document
> chore: Add object renaming research summary

- docs/technical-documentation/object_renaming_research_summary.md
- pkg/architest/architest_test.go
- pkg/architest/file.go
- pkg/architest/testdata/dir1/sample2.go
- Exclude methods from architest that checks testing functions (test functions cannot be methods)
- Fix spelling mistake
> chore: Exclude methods from test function checks in architest

- MIGRATION_GUIDE.md
- docs/resources/legacy_service_user.md
- docs/resources/user.md
- pkg/acceptance/bettertestspoc/assert/resourceassert/user_resource_ext.go
- pkg/resources/user.go
- pkg/resources/user_acceptance_test.go
- templates/resources/legacy_service_user.md.tmpl
- templates/resources/user.md.tmpl
Handle user import correctly.
Password is empty after the `snowflake_user` import; we can't read it from the config or from Snowflake.
During the next terraform plan+apply it's updated to the "same" value.
It results in an error on Snowflake side: `New password rejected by current password policy. Reason: 'PRIOR_USE'.`
The error will be ignored on the provider side (after all, it means that the password in state is the same as on Snowflake side). Still, plan+apply is needed after importing user.
> fix: Fix user resource import

- docs/resources/storage_integration.md
- pkg/acceptance/helpers/storage_integration_client.go
- pkg/resources/storage_integration.go
- pkg/sdk/storage_integration_def.go
- pkg/sdk/storage_integration_dto_builders_gen.go
- pkg/sdk/storage_integration_dto_gen.go
- pkg/sdk/storage_integration_gen.go
- pkg/sdk/storage_integration_gen_test.go
- pkg/sdk/storage_integration_impl_gen.go
- pkg/sdk/testint/storage_integration_gen_integration_test.go
Support all s3 protocols (ref: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3212)
> chore: Storage integration with custom protocol

- pkg/resources/task.go
- pkg/resources/task_acceptance_test.go
- pkg/sdk/parameters.go
- pkg/sdk/tasks_impl_gen.go
- pkg/sdk/testint/tasks_gen_integration_test.go
- Addressing 4 task-related issues
- Two of them await to be reported, created a ticket for that and will put the correct tickets when they'll be created.
- The `getPredecessors` function is still used, but the field it populates is not used in the resource; `TaskRelations` are used instead.
- Task parameters were already handled properly in the resource.
> chore: Adress small task-related todos

- pkg/acceptance/bettertestspoc/assert/objectassert/function_describe_snowflake_ext.go
- pkg/acceptance/bettertestspoc/assert/objectassert/procedure_describe_snowflake_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_java_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/procedure_java_model_ext.go
- pkg/resources/function_and_procedure_commons.go
- pkg/resources/function_commons.go
- pkg/resources/function_java.go
- pkg/resources/function_java_acceptance_test.go
- pkg/resources/procedure_commons.go
- pkg/resources/procedure_java.go
- pkg/resources/procedure_java_acceptance_test.go
- pkg/sdk/functions_and_procedures_commons.go
- pkg/sdk/functions_ext.go
- pkg/sdk/procedures_ext.go
- pkg/sdk/testint/functions_integration_test.go
- pkg/sdk/testint/procedures_integration_test.go
Handle secrets, external access integrations, comments, packages, and snowpark package.
> feat: Handle missing fields in function and procedure

- pkg/acceptance/bettertestspoc/assert/objectassert/function_snowflake_ext.go
- pkg/acceptance/bettertestspoc/assert/objectassert/procedure_snowflake_ext.go
- pkg/sdk/datatypes/data_types.go
- pkg/sdk/datatypes/data_types_test.go
- pkg/sdk/datatypes/legacy.go
- pkg/sdk/datatypes/table.go
- pkg/sdk/datatypes/vector.go
- pkg/sdk/testint/functions_integration_test.go
- pkg/sdk/testint/procedures_integration_test.go
- support table data types
- add unit tests on parsing and comparing
- add integration tests in function and procedure tests
> feat: support table data type

- pkg/resources/function_and_procedure_commons.go
- pkg/resources/function_commons.go
- pkg/resources/function_java.go
- pkg/resources/function_java_acceptance_test.go
- pkg/resources/function_javascript.go
- pkg/resources/function_python.go
- pkg/resources/function_scala.go
- pkg/resources/function_sql.go
- pkg/resources/procedure_commons.go
- pkg/resources/procedure_java.go
- pkg/resources/procedure_java_acceptance_test.go
- pkg/resources/procedure_javascript.go
- pkg/resources/procedure_python.go
- pkg/resources/procedure_scala.go
- pkg/resources/procedure_sql.go
Improve and test imports for functions and procedures
> feat: Test imports and small fixes

- pkg/acceptance/bettertestspoc/assert/resourceassert/function_javascript_resource_gen.go
- pkg/acceptance/bettertestspoc/assert/resourceassert/function_sql_resource_gen.go
- pkg/acceptance/bettertestspoc/config/model/function_javascript_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_python_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_scala_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_sql_model_ext.go
- pkg/acceptance/helpers/function_client.go
- pkg/resources/function_java_acceptance_test.go
- pkg/resources/function_javascript_acceptance_test.go
- pkg/resources/function_python_acceptance_test.go
- pkg/resources/function_scala.go
- pkg/resources/function_scala_acceptance_test.go
- pkg/resources/function_sql_acceptance_test.go
- pkg/sdk/testint/functions_integration_test.go
> chore: function tests

- pkg/resources/function_java_acceptance_test.go
- pkg/resources/function_javascript_acceptance_test.go
- pkg/resources/function_python_acceptance_test.go
- pkg/resources/function_scala_acceptance_test.go
- pkg/resources/function_sql_acceptance_test.go
- pkg/resources/procedure_java_acceptance_test.go
- pkg/resources/procedure_javascript_acceptance_test.go
- pkg/resources/procedure_python_acceptance_test.go
- pkg/resources/procedure_scala_acceptance_test.go
- pkg/resources/procedure_sql_acceptance_test.go
- Add external removal tests to functions and procedures (done during old issues closing)
- Fix the following tests:
- TestAcc_FunctionJava_InlineFull
- TestAcc_FunctionPython_InlineBasic
- TestAcc_FunctionPython_InlineFull
- TestAcc_FunctionScala_InlineFull
- TestAcc_FunctionSql_InlineBasic
> chore: Add external removal tests to functions and procedures

- CREATING_ISSUES.md
This is a documentation-only change, no code was changed.
Added FAQ entry for `Error: 260000: account is empty` people seem to be hitting after v1.0.0
> docs: SNOW-1865901 add faq for account is empty

- pkg/acceptance/bettertestspoc/config/model/function_java_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_java_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/function_javascript_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_javascript_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/function_python_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_python_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/function_scala_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_scala_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/function_sql_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/function_sql_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/gen/model.go
- pkg/acceptance/bettertestspoc/config/model/gen/multiline_attributes_overrides.go
- pkg/acceptance/bettertestspoc/config/model/gen/templates/builders.tmpl
- pkg/acceptance/bettertestspoc/config/model/legacy_service_user_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/procedure_java_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/procedure_java_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/procedure_javascript_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/procedure_javascript_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/procedure_python_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/procedure_python_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/procedure_scala_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/procedure_scala_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/procedure_sql_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/procedure_sql_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/service_user_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/user_model_gen.go
- pkg/datasources/users_acceptance_test.go
- pkg/resources/legacy_service_user_acceptance_test.go
- pkg/resources/service_user_acceptance_test.go
- pkg/resources/user_acceptance_test.go
Enable generating multiline config building:
- use overrides to decide what type of method should be generated
- add it to the known cases (all user types, all function types, and all procedure types)
- apply change only to resource models; it is still an extension method for the provider config model
- adjusted existing models and acceptance tests
> chore: Generate multiline by default

- MIGRATION_GUIDE.md
- docs/index.md
- docs/resources/schema.md
- docs/resources/tag.md
- pkg/resources/account_acceptance_test.go
- pkg/resources/account_state_upgraders.go
- pkg/resources/schema.go
- pkg/resources/tag.go
- pkg/sdk/tasks_gen_test.go
- pkg/sdk/testint/resource_monitors_integration_test.go
- templates/index.md.tmpl
- Fix handling optional account fields in the state upgrader. This error happened after importing accounts where the optional fields were not set—they are not populated in Import/Read. This resulted in empty values and panics.
- The change has been verified manually. The acceptance test can be added in a follow-up (linked ticket) because of the potential limitations of the plugin SDK.
- Fix failing tests.
- Fix a few issues in docs.
#3328 #3332
> fix: Handle optional account fields in the state upgrader correctly

- pkg/sdk/parameters.go
- pkg/sdk/parameters_test.go
`ENFORCE_NETWORK_RULES_FOR_INTERNAL_STAGES` requires boolean parameter so I change the setting from ddl:keyword to ddl:parameter.
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3344
> fix: change EnforceNetworkRulesForInternalStages ddl to parameter

- docs/technical-documentation/performance_benchmarks.md
- pkg/manual_tests/benchmarks/README.md
- Publish the performance benchmarks summary.
- Fix the title of tests' readme.
#3118 
#3169
> chore: Publish Performance tests summary

- docs/resources/account.md
- pkg/resources/account.go
- pkg/resources/task_acceptance_test.go
- pkg/sdk/testint/accounts_integration_test.go
- pkg/sdk/testint/tasks_gen_integration_test.go
- templates/resources/account.md.tmpl
- Adjust task test as part of SNOW-1843489 (it turned out the logic is correct, but the behavior was confusing; documented in code)
- Adjusted ticket numbers to corresponding issues for account/task
- Add a note in the account documentation about undetected changes for certain fields (SNOW-1299979)
- When account issues will be addressed change ticket numbers.
> chore: Resolve issues and document account resource

- docs/resources/grant_application_role.md
- docs/resources/grant_ownership.md
- docs/resources/grant_privileges_to_account_role.md
- docs/resources/grant_privileges_to_database_role.md
- examples/resources/snowflake_grant_application_role/resource.tf
- pkg/acceptance/helpers/hybrid_table_client.go
- pkg/acceptance/helpers/test_client.go
- pkg/resources/grant_ownership_acceptance_test.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantOwnership/OnObject_HybridTable_ToAccountRole/test.tf
- pkg/resources/testdata/TestAcc_GrantOwnership/OnObject_HybridTable_ToAccountRole/variables.tf
- pkg/resources/testdata/TestAcc_GrantOwnership/OnObject_Table_ToAccountRole/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/OnSchemaObject_OnObject_HybridTable/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/OnSchemaObject_OnObject_HybridTable/variables.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToDatabaseRole/OnSchemaObject_OnObject/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToDatabaseRole/OnSchemaObject_OnObject_HybridTable/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToDatabaseRole/OnSchemaObject_OnObject_HybridTable/variables.tf
- templates/resources/grant_ownership.md.tmpl
- templates/resources/grant_privileges_to_account_role.md.tmpl
- templates/resources/grant_privileges_to_database_role.md.tmpl
- Add a note about managing grants on hybrid tables. Currently, this fails in Snowflake and grants should be managed through TABLE.
- It has not been confirmed whether this is a bug in Snowflake or just in the docs (probably the former). See DOC-4953 for more info.
- Add a test proving this behavior.
- Add hybrid table client helper.
- This change does not fix the issue, but it will be done in SNOW-1022645.
#3300
> chore: Add notes about managing grants on hybrid table

- MIGRATION_GUIDE.md
- docs/guides/identifiers_rework_design_decisions.md
- docs/guides/object_renaming_guide.md
- pkg/internal/tracking/context.go
- pkg/resources/account_parameter_acceptance_test.go
- pkg/sdk/parameters.go
- pkg/sdk/parameters_test.go
- templates/guides/identifiers_rework_design_decisions.md.tmpl
- templates/guides/object_renaming_guide.md.tmpl
- Add missing support for metric level account parameter #3375
- Add object renaming guide
> chore: Metric level fix with object renaming guide

- docs/guides/authentication_methods.md
- docs/index.md
- docs/resources/account.md
- docs/resources/api_authentication_integration_with_authorization_code_grant.md
- docs/resources/api_authentication_integration_with_client_credentials.md
- docs/resources/api_authentication_integration_with_jwt_bearer.md
- docs/resources/legacy_service_user.md
- docs/resources/managed_account.md
- docs/resources/secret_with_authorization_code_grant.md
- docs/resources/secret_with_basic_authentication.md
- docs/resources/secret_with_generic_string.md
- docs/resources/service_user.md
- docs/resources/stage.md
- docs/resources/user.md
- examples/provider/provider.tf
- examples/resources/snowflake_account/resource.tf
- examples/resources/snowflake_api_authentication_integration_with_authorization_code_grant/resource.tf
- examples/resources/snowflake_api_authentication_integration_with_client_credentials/resource.tf
- examples/resources/snowflake_api_authentication_integration_with_jwt_bearer/resource.tf
- examples/resources/snowflake_legacy_service_user/resource.tf
- examples/resources/snowflake_managed_account/resource.tf
- examples/resources/snowflake_secret_with_authorization_code_grant/resource.tf
- examples/resources/snowflake_secret_with_basic_authentication/resource.tf
- examples/resources/snowflake_secret_with_generic_string/resource.tf
- examples/resources/snowflake_service_user/resource.tf
- examples/resources/snowflake_stage/resource.tf
- examples/resources/snowflake_user/resource.tf
- templates/guides/authentication_methods.md.tmpl
- templates/index.md.tmpl
- Discourage using hardcoded values by removing them from the examples in resources and the provider. Use TF variables instead.
> chore: Remove hardcoded values from documentation

- MIGRATION_GUIDE.md
- pkg/resources/external_function.go
- pkg/resources/external_function_acceptance_test.go
Fixes https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3392
> fix: external function varchar return type validation

- docs/resources/saml2_integration.md
- templates/resources/saml2_integration.md.tmpl
- Add a note that using `allowed_user_domains` and `allowed_email_patterns` fields requires enabled identifier-first logins
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3358
> chore: Adjust saml2_integration documentation

- pkg/internal/snowflakeroles/snowflake_predefined_roles.go
- pkg/sdk/sweepers.go
- pkg/sdk/sweepers_test.go
- Adjust sweepers to ignore users and roles used for testing.
> chore: Protect pentesting user and role from sweepers

- CREATING_ISSUES.md
- MIGRATION_GUIDE.md
Document issue #3421 and how the godebug environment variable can be used to turn off some of the Go features that may not always be compatible with third-party software (like firewalls).
> chore: Document godebug flag usage

- pkg/datasources/grants_acceptance_test.go
`TestAcc_Grants_To_AccountRole` was failing because of the incompatible data types on the current role: `SNOWFLAKE.CORE."AVG(ARG_T TABLE(FLOAT)):FLOAT"` and `SNOWFLAKE.ACCOUNT_USAGE."TAG_REFERENCES_WITH_LINEAGE(TAG_NAME_INPUT VARCHAR):TABLE:`.
Will be addressed soon.
> fix: Skip failing datasource test

- pkg/acceptance/bettertestspoc/assert/objectassert/task_snowflake_ext.go
- pkg/sdk/testint/tasks_gen_integration_test.go
Using the wrong assertion resulted in assertions not being applied at all. 6 tests needed to be fixed:
- change the expected value
- use fetching the object after changes and not reusing the same one
- setup for finalizer tasks reversed
> fix: Fix tasks tests

- .github/workflows/ok-to-test.yml
- .github/workflows/release.yml
- .github/workflows/team-jira-issues.yml
- .github/workflows/tests.yml
Introduce environmental secrets for GitHub Actions:
- Only set environment for `jira` and `test` environments
- `release` and `ok-to-test` require app id and app private key, which will be retrieved later
Check if all workflows are working properly
> chore: Use environmental secrets in GitHub Actions

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog-golanglint-ci.yml
- .github/workflows/workflow-rules.yml
- Add workflow that validates other workflows. For now, only one rule is applied.
- Fix codeql push event
> chore: Update GitHub actions

- .github/ISSUE_TEMPLATE/01-bug.yml
- .github/ISSUE_TEMPLATE/02-general-usage.yml
- MIGRATION_GUIDE.md
- docs/guides/authentication_methods.md
- docs/guides/grant_ownership_common_use_cases.md
- docs/guides/identifiers_rework_design_decisions.md
- docs/guides/resource_migration.md
- docs/resources/account.md
- docs/resources/masking_policy.md
- pkg/resources/masking_policy.go
- templates/guides/authentication_methods.md.tmpl
- templates/guides/grant_ownership_common_use_cases.md.tmpl
- templates/guides/identifiers_rework_design_decisions.md.tmpl
- templates/guides/resource_migration.md.tmpl
- templates/resources/account.md.tmpl
- Add the note about aggressive upgrades and adjust the resource migration guide.
- Use title case in the guides.
- Add a note about recreating accounts and grace period.
- Add a note about pasting logs.
- Fix typos.
#3390
> fix: Adjust docs

- ROADMAP.md
Add snowflakedb migration announcement
> docs: Add roadmap entry about snowflakedb migration

- .github/workflows/reviewdog-golanglint-ci.yml
- Makefile
- Set a fixed golangci-lint version in GH actions. The action uses the latest release by default. This broke our pipelines because [v2 version](https://github.com/golangci/golangci-lint/releases/tag/v2.0.0) has been released. We can fix this for now by setting the version to `v1.63.4` in the GH actions (we already use this version in `make dev-setup`.
- Link the tickets for upgrading golangci-lint to the newest version.
> chore: Set a fixed golangci-lint version in GH actions

- pkg/acceptance/helpers/database_client.go
- pkg/datasources/schemas_acceptance_test.go
- pkg/resources/grant_database_role_acceptance_test.go
- pkg/resources/grant_ownership_acceptance_test.go
- pkg/resources/grant_ownership_identifier_test.go
- pkg/resources/grant_ownership_test.go
- pkg/resources/grant_privileges_to_account_role_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_acceptance_test.go
- pkg/resources/grant_privileges_to_share_acceptance_test.go
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/ImportedPrivileges/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/ImportedPrivileges/variables.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToAccountRole/OnSchemaObject_OnObject_OwnershipPrivilege/test.tf
- pkg/resources/testdata/TestAcc_GrantPrivilegesToDatabaseRole/OnSchemaObject_OnObject_OwnershipPrivilege/test.tf
Continuation of https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3443, https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3445, https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3448, https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3449, and https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3450.
Use the pre-created database or create a database with the parameters set (resource - part2):
- the pre-created database not changed yet (it still does not have the parameters)
- going alphabetically through resources, last one was grant privileges to database role
- remove database from setups where not needed
- add missing testenvs.EnableAcceptance and acc.TestAccPreCheck(t)
- renamed database client …
> fix: Fix resource acceptance tests setup part2

- .github/workflows/codeql-analysis.yml
- .github/workflows/ok-to-test.yml
- Changed permission from `maintainer` (invalid value) to `maintain` (a valid value for a field)
> fix: ok-to-test permission

- MIGRATION_GUIDE.md
- docs/index.md
- pkg/provider/provider.go
- pkg/provider/provider_acceptance_test.go
- templates/index.md.tmpl
- This is a breaking change.
- Set `skip_toml_file_permission_verification` to `false` by default to verify file permissions in the TOML configuration file.
- Improve a documentation page hierarchy.
> feat: Verify file permissions by default

- .github/workflows/release.yml
- Adjust tag event regex for release workflow (now, it's only triggered when the tag follows semantic versioning with possible postfixes; prefixes were skipped as we only thought of using postfixes in our versioning strategy).
> chore: Release workflow adjustments

- .github/workflows/tests.yml
Allow only one concurrent tests job for the given PR.
Cancel the in progress one if new commits exist.
> chore: Allow only one concurrent job for tests on the given branch

- .github/repo_meta.yaml
The repo meta file is updated to add audit_in_scope as true so that we can do monitoring on these audit impacting repo's for branch protection rule changes. 
Please approve as this tagging help us to ensure we are not missing it out from monitoring controls.
*
> chore: Update repo_meta.yaml

- MIGRATION_GUIDE.md
- pkg/resources/custom_diffs.go
- pkg/resources/user_acceptance_test.go
The issue could arise in almost any object using show_output when the following steps happen:
1. Object is created.
2. Object's attribute is updated to computed value of other object added in this run.
Reason: `diff.HasChange(changedKey)` used in `ComputedIfAnyAttributeChanged` does not trigger, so the whole `show_output` is not marked as a new attribute.
References: #3522
> fix: Fix handling references to computed fields in context of `show_output`

- framework/provider/provider.go
- pkg/acceptance/testing.go
- pkg/provider/provider.go
- pkg/sdk/client.go
- pkg/sdk/client_integration_test.go
- pkg/sdk/config.go
- pkg/sdk/helper_test.go
- pkg/sdk/legacy_config_test.go
- pkg/sdk/testint/basic_object_tracking_integration_test.go
- pkg/sdk/testint/client_integration_test.go
- pkg/sdk/testint/setup_test.go
- Use opts pattern in for building provider config.
- Add some more integration tests.
- In general, the setup of the tests is the same for now, they can be simplified in v2, just to be more sure.
- Remove unnecessary opts when permission verification is enabled by default in v2.
> chore: Use opts for reading TOML config

- pkg/acceptance/bettertestspoc/README.md
- pkg/acceptance/bettertestspoc/assert/objectparametersassert/gen/object_parameters_def.go
- pkg/acceptance/bettertestspoc/assert/objectparametersassert/user_parameters_snowflake_gen.go
- pkg/acceptance/bettertestspoc/assert/resourceparametersassert/user_resource_parameters_ext.go
- pkg/acceptance/check_destroy.go
- pkg/acceptance/testenvidentifiers/test_identifiers.go
- pkg/resources/user_password_policy_attachment_acceptance_test.go
- pkg/sdk/testint/policy_references_integration_test.go
- Adjust tests to account for new network policy
- Change default value for user network policy parameter to RESTRICTED_ACCESS and change it's default level to ACCOUNT
- Adjust CheckUserPasswordPolicyAttachmentDestroy logic to only check for password policies (not all policies as it was previously doing)
- Remove TestAcc_UserPasswordPolicyAttachment_gh3005 as it was referring to the old provider code (v0.87.0), which had a bug and was mapping POLICY_STATUS as a non-null field. It was fixed later on and it will be always failing because of the network policy on the account that has always null status (I'm guessing status for this policy doesn't matter).
- Adjust parameter asserts, particularly HasAllDefaults function to check for default values on the level by checking with locally defined …
> fix: Network policy test fixes

- pkg/acceptance/helpers/account_client.go
- pkg/acceptance/helpers/ids_generator.go
- pkg/acceptance/helpers/random/random_helpers.go
- pkg/resources/account_acceptance_test.go
- pkg/resources/legacy_service_user_acceptance_test.go
- pkg/resources/managed_account_acceptance_test.go
- pkg/resources/service_user_acceptance_test.go
- pkg/resources/user_acceptance_test.go
- pkg/sdk/testint/accounts_integration_test.go
- pkg/sdk/testint/users_integration_test.go
- Updated other random helpers to include masking string
- Used masking string in login names and passwords
- Replaced the use of AdminName in places where it wasn't admin name, but rather an identifier or other value that should be masked.
> chore: Masking random values

- pkg/resources/account_parameter_acceptance_test.go
- pkg/sdk/parameters.go
This pull request fixes a SQL syntax error that occurs when setting the CSV_TIMESTAMP_FORMAT parameter using the `snowflake_account_parameter` resource. In the current implementation, parameter values are generated without single quotes in the SQL statement, causing syntax errors when values contain format specifiers like "YYYY-MM-DDTHH24:MI:SS.FF3TZH:TZM".
The fix adds the `single_quotes` tag to the CsvTimestampFormat field in the SessionParameters struct, ensuring values are properly quoted in the generated SQL, similar to other date and time-related parameters. With this change, the provider will correctly generate SQL statements like "ALTER ACCOUNT SET CSV_TIMESTAMP_FORMAT = 'YYYY-MM-DDTHH24:MI:SS.FF3TZH:TZM'" instead of the unquoted version that produces errors.
This eliminates the …
> fix: Add single quotes to CSV_TIMESTAMP_FORMAT parameter value

- pkg/acceptance/bettertestspoc/config/model/external_oauth_security_integration_model_ext.go
- pkg/acceptance/bettertestspoc/config/model/external_oauth_security_integration_model_gen.go
- pkg/acceptance/bettertestspoc/config/model/gen/model.go
- pkg/acceptance/bettertestspoc/config/model/gen/overrides.go
- pkg/acceptance/bettertestspoc/config/model/gen/templates.go
- pkg/acceptance/bettertestspoc/config/model/gen/templates/builders.tmpl
- pkg/acceptance/bettertestspoc/config/model/gen/templates/preamble.tmpl
- pkg/datasources/security_integrations_acceptance_test.go
- pkg/internal/genhelpers/resource_schema_details_extractor.go
- pkg/internal/genhelpers/template_commons.go
- pkg/internal/genhelpers/util.go
Handle list and set required attributes, but ONLY in model builder constructors (`With` methods are still marked as non-generable).
> chore: Handle slices in resource model builder generation

- internal/tracking/version.go
- pkg/acceptance/helpers/information_schema_client.go
- pkg/datasources/usage_tracking_acceptance_test.go
- pkg/resources/usage_tracking_acceptance_test.go
- pkg/sdk/testint/authentication_policies_gen_integration_test.go
- Set default tracking version to "dev", so that
- a) We can track queries run by CI or us (dev team) locally.
- b) We can keep the existing tracking logic (the tests were failing because of the internal validation that expects non-empty provider version and returns empty Metadata)
- Increase the limit to 100 (as sometimes we could observe tests failing because of other CI test jobs running simultaneously)
> fix: object tracking

- MIGRATION_GUIDE.md
- pkg/resources/tag_association.go
- pkg/resources/tag_association_acceptance_test.go
- Fixes the #3622 issue where tag association would fail for objects that use `sdk.SchemaObjectidentifier`, which is not a `comparable` type.
- The same error is expected to happen for `sdk.SchemaObjectIdentifierWithArguments`, but only functions and procedures use it, which don't support tagging (even if they would, we would wait for them to be implemented in the resource directly).
> fix: 3622 issue

- Makefile
- go.mod
- go.sum
- pkg/resources/usage_tracking_acceptance_test.go
- Upgrade gosnowflake driver version to 1.13.3
- Added `make release-local-all` command and built all os/arch targets with the new version, and now it's building for FreeBSD
> chore: Upgrade GoSnowflake driver

- pkg/resources/usage_tracking_acceptance_test.go
Removed a duplicated import that was causing `make pre-push` to fail.
> refactor: Remove unused import in usage tracking acceptance test

- Makefile
- pkg/acceptance/bettertestspoc/config/datasourcemodel/database_model_gen.go
- pkg/acceptance/bettertestspoc/config/datasourcemodel/database_role_model_gen.go
- pkg/acceptance/bettertestspoc/config/providermodel/gen/templates/preamble.tmpl
- pkg/resources/usage_tracking_acceptance_test.go
Ensure no changes to generated model builders in pre push:
- add entries to the Makefile only for model builders for now (assertions will be covered later)
- regenerate data sources (they were affected by the recent changes in generator)
- remove additional standard imports from the provider model template (as they are not needed and hardcoded for two other use cases)
> chore: Ensure no changes to generated model builders in pre push

- pkg/sdk/poc/generator/field_transformers.go
- pkg/sdk/secrets_gen.go
This PR fixes an issue in the field transformers where certain fields were not being correctly assigned when set ddl options.  
The bug specifically affected cases where both `equals` and `parentheses` were set on a field.
The only affected case found was in `secrets_def.go`, so the DDL was regenerated for that file using the SDK.
> fix: Set value into correct field for field transformers

- pkg/resources/execute_acceptance_test.go
- pkg/resources/usage_tracking_acceptance_test.go
- pkg/sdk/testint/client_unsafe_extensions_integration_test.go
- Fix tests that failed in https://github.com/snowflakedb/terraform-provider-snowflake/actions/runs/14756294570/job/41630195278 (the tests were run with BCR enabled)
> chore: Fix tests that will fail once 02_2025 is enabled

- MIGRATION_GUIDE.md
Update `snowflake_user` resource in the v0.95.0 migration guide (how to avoid diff recognition for `user_type`). This should simplify the migration for customers.
> docs: Update v095 migration guide

- pkg/resources/grant_account_role_acceptance_test.go
- pkg/resources/grant_database_role_account_level_acceptance_test.go
- pkg/resources/grant_privileges_to_account_role_account_level_acceptance_test.go
- pkg/resources/grant_privileges_to_database_role_account_level_acceptance_test.go
- pkg/sdk/testint/grants_account_level_integration_test.go
- Some of the tests were passing during the local development, but failed on CI. This was because `ConfigureClientOnce` setting was set for them. This pr unsets it for those tests to fix them on CI.
> chore: Fix tests that run on secondary account profile

- pkg/acceptance/bettertestspoc/config/commons.go
- pkg/acceptance/bettertestspoc/config/config.go
- pkg/acceptance/bettertestspoc/config/config_test.go
- pkg/acceptance/bettertestspoc/config/hcl_config_provider.go
- pkg/acceptance/bettertestspoc/config/json_config_provider.go
- pkg/acceptance/bettertestspoc/config/json_config_provider_test.go
- pkg/acceptance/bettertestspoc/config/model/database_model_ext.go
- pkg/acceptance/bettertestspoc/config/variable_model.go
- pkg/datasources/masking_policies_acceptance_test.go
- pkg/datasources/security_integrations_acceptance_test.go
- pkg/resources/masking_policy_acceptance_test.go
- pkg/resources/row_access_policy_acceptance_test.go
- pkg/resources/saml2_integration_acceptance_test.go
Extract a common builder for variable model:
- Support new model type in `FromModels`
- Use in all inline places where the vars were used (not touching the setups using `ConfigFile`)
- Add TODOs for later
> chore: Add variable model builder

- MIGRATION_GUIDE.md
- pkg/sdk/grants_impl.go
- pkg/sdk/testint/grants_account_level_integration_test.go
Recently, we introduced a fix in handling users' grants, which addressed changes in the `2025_02` bundle. The username was parsed incorrectly if it had a prefix formed of `U`, `S`, `E`, and `R` characters. The username returned from `SHOW GRANTS` was incorrect in this case. Now, such names should be handled correctly.
Additionally, fix the parameter order in `assert.Equal` in a related test.
> fix: Fix parsing username in handling grants

- pkg/resources/external_volume.go
This PR fixes a variable name inconsistency in the external volume creation error handling logic. 
The code was using err in the condition check while storing the error in createErr, which would always result in the condition being false, preventing proper error reporting.
> fix: Correct error handling in CreateContextExternalVolume function

- docs/resources/function_python.md
- docs/resources/procedure_python.md
- examples/resources/snowflake_function_python/resource.tf
- examples/resources/snowflake_procedure_python/resource.tf
- pkg/acceptance/bettertestspoc/config/model/procedure_python_model_ext.go
- pkg/acceptance/helpers/function_setup_helpers.go
- pkg/acceptance/testvars/functions_and_procedures.go
- pkg/sdk/functions_gen_test.go
- pkg/sdk/procedures_gen_test.go
- pkg/sdk/testint/functions_integration_test.go
- pkg/sdk/testint/procedures_integration_test.go
- pkg/testacc/function_python_acceptance_test.go
- pkg/testacc/procedure_python_acceptance_test.go
Use 3.9 and 3.10 Python runtime instead of the decommissioned 3.8, as our integration and acceptance tests started to fail yesterday. Extracted common const for Python runtime for easier refactoring later.
> fix: Adjust function and procedure tests

- pkg/resources/network_policy_attachment.go
- pkg/sdk/accounts.go
- pkg/sdk/accounts_test.go
- pkg/sdk/parameters.go
- pkg/sdk/parameters_test.go
- pkg/sdk/testint/accounts_integration_test.go
- pkg/sdk/testint/conversion_functions_integration_test.go
- Rename `Parameters` to `LegacyParameters` inside `AccountSet` struct
- A new `Parameters` field will be added that will contain all parameters that account will be able to set instead of parameters split among different objects depending on the parameter hierarchy.
> chore: Rename account parameters field name

- pkg/acceptance/bettertestspoc/assert/objectassert/gen/model.go
- pkg/internal/genhelpers/struct_details_extractor.go
- pkg/testacc/provider_acceptance_test.go
- pkg/testacc/snowflake_behavior_object_renaming_acceptance_test.go
Continuation of https://github.com/snowflakedb/terraform-provider-snowflake/pull/367,  https://github.com/snowflakedb/terraform-provider-snowflake/pull/3691, and https://github.com/snowflakedb/terraform-provider-snowflake/pull/3692.
- Move provider acceptance tests to use the `testacc` package setup
- Move one more resource-level tests (renaming hierarchies in Snowflake)
- Apply some fixes after review in https://github.com/snowflakedb/terraform-provider-snowflake/pull/3722
Next PRs:
- Removal of old acceptance tests setup
- Update contribution guidelines
- TODOs from https://github.com/snowflakedb/terraform-provider-snowflake/pull/3679
- architests
- test resources setup
> chore: Use common setup and cleanup for acceptance tests - provider

- docs/resources/shared_database.md
- examples/resources/snowflake_shared_database/resource.tf
The snowflake_shared_database example includes the "is_transient" attribute in the resource definition even though this resource does not expose that attribute. This PR updates the example & doc to fix that.
Update: The previous PR (https://github.com/snowflakedb/terraform-provider-snowflake/pull/3743) was based on the main branch rather than dev; this PR uses the dev branch for the PR instead. 
* https://github.com/snowflakedb/terraform-provider-snowflake/issues/3731
> docs: remove false attribute from snowflake_shared_database example

- pkg/testacc/resource_external_oauth_integration_acceptance_test.go
To tackle the error:
```
=== RUN   TestAcc_ExternalOauthIntegration_migrateFromV0941_ensureSmoothUpgradeWithNewResourceId
resource_external_oauth_integration_acceptance_test.go:788: running check destroy for resource snowflake_external_oauth_integration
resource_external_oauth_integration_acceptance_test.go:783: Step 1/2 error: Error running apply: exit status 1
Error: 003524 (22023): SQL execution error: An integration with the given issuer already exists for this account.
with snowflake_external_oauth_integration.test,
on terraform_plugin_test.tf line 14, in resource "snowflake_external_oauth_integration" "test":
14: resource "snowflake_external_oauth_integration" "test" {
--- FAIL: TestAcc_ExternalOauthIntegration_migrateFromV0941_ensureSmoothUpgradeWithNewResourceId (4.71s)
```
All …
> fix: Fix external oauth integration issuer tests

- docs/resources/tag.md
- templates/resources/tag.md.tmpl
Add tag propagation limitation to the tag resource documentation
> chore: Add tag propagation limitation to the tag resource documentation

- pkg/sdk/testint/conversion_functions_integration_test.go
- pkg/sdk/testint/grants_account_level_integration_test.go
- pkg/testacc/resource_account_parameter_acceptance_test.go
- pkg/testacc/resource_grant_database_role_account_level_acceptance_test.go
- pkg/testacc/resource_grant_privileges_to_account_role_account_level_acceptance_test.go
- pkg/testacc/resource_grant_privileges_to_database_role_account_level_acceptance_test.go
- Change build tag for tests that alter current account as it was making user tests fail with parameter errors
- Skip tests that enable 2025_02 BCR bundle as it's now enabled by default in Snowflake. Added TODO with ticket number to later address those tests.
> chore: Adjust failing tests

- .github/workflows/tests-account-level.yml
- .github/workflows/tests.yml
Remove CHANGELOG.md from run tests filter
> chore: Do not build the whole project after the changelog entry

- MIGRATION_GUIDE.md
- SNOWFLAKE_BCR_MIGRATION_GUIDE.md
Describe the migration guide and the BCR migration guide for the updated `SHOW FUNCTIONS/PROCEDURES` behavior after 2025_03 Bundle activation.
> docs: Fill out the migration guide and the BCR guide for functions and procedures changes

- pkg/sdk/config_test.go
- pkg/sdk/legacy_config_test.go
- Disable linter for deprecated InsecureMode assertions
> chore: Address pre-push errors

- docs/resources/pipe.md
- examples/resources/snowflake_pipe/resource.tf
This expands on the example for the `snowflake_pipe` resource:
- Shows setting up a pipe with a corresponding stage
- Forces the recreation of the pipe based on the stage changing
n/a
none
> chore: Add an example of recreating the pipe on changing stage attributes

- .github/workflows/tests-account-level.yml
- .github/workflows/tests.yml
When running the repository_dispatch, checkout to the commit SHA from the slash command.
> chore: Checkout to the commit SHA from the slash command

- pkg/resources/grant_privileges_to_share.go
- pkg/resources/grant_privileges_to_share_identifier_test.go
- pkg/testacc/resource_grant_privileges_to_share_acceptance_test.go
- pkg/testacc/testdata/TestAcc_GrantPrivilegesToShare/OnDynamicTable/test.tf
- pkg/testacc/testdata/TestAcc_GrantPrivilegesToShare/OnDynamicTable/variables.tf
Solves #3167 
Fix permadiff when granting privileges to shares on external, dynamic, hybrid, and iceberg tables
*
> fix: permadiff when granting privileges to shares on non-standard tables

- SNOWFLAKE_BCR_MIGRATION_GUIDE.md
Add Snowflake BCR 2025_04 migration guide:
- Add an entry for altered privileges check in Snowflake.
- Add an entry for changes in authentication methods.
* [Snowflake BCR Bundle 2025_04](https://docs.snowflake.com/en/release-notes/bcr-bundles/2025_04_bundle)
> chore: Add 2025_04 BCR migration guide

- pkg/sdk/database_role.go
- pkg/sdk/external_tables.go
- pkg/sdk/grants.go
- pkg/sdk/helpers_proposal.go
- pkg/sdk/pipes.go
- pkg/sdk/policy_references.go
- pkg/sdk/replication_functions.go
- pkg/sdk/roles_impl.go
- pkg/sdk/tables.go
- pkg/sdk/warehouses.go
- pkg/sdk/warehouses_test.go
It's the first PR of a few aiming to improve SDK's stability and reliability by including an error in the return from conversion attempt. Till now, the errors there were only logged which caused unexpected behavior in some cases (like improper id parsing for functions and , because of that, not finding the function with an empty id).
The change contains:
- Rename `convertibleRow` to `convertibleRowDeprecated`
- Introduce `conversionErrorWrapped` method (it's needed as `convert` is either used from `convertRows` or directly)
- Alter the conversion for warehouse
- Add unit tests for warehouse conversion
Next PRs:
- Migrate all other objects that are not generated from defs
- Alter generation
- Migrate all other objects that are generated
- Rename `convertRowsErr` to `convertRows` when all …
> fix: Change convert signature for a single object

- .github/workflows/tests.yml
- Makefile
To avoid TF installation errors (e.g. https://github.com/snowflakedb/terraform-provider-snowflake/actions/runs/17153568002/job/48665189694)
> chore: Run functional tests after setting up Terraform

- pkg/acceptance/helpers/0_tests_setup_helpers.go
- pkg/acceptance/helpers/stage_client.go
- pkg/acceptance/helpers/tmp_toml_setup_helpers.go
- pkg/acceptance/testfiles/helpers.go
- pkg/datasources/accounts.go
- pkg/internal/oswrapper/os_test.go
- pkg/manual_tests/windows/files_test.go
- pkg/manual_tests/windows/provider_test.go
- pkg/resources/account_parameter.go
- pkg/schemas/account_parameters.go
- pkg/sdk/config_test.go
- pkg/sdk/legacy_config_test.go
- pkg/sdk/listings_def.go
- pkg/sdk/testint/masking_policy_integration_test.go
- pkg/sdk/testint/row_access_policies_gen_integration_test.go
- pkg/sdk/testint/tables_integration_test.go
- pkg/testacc/0_setup_helper_funcs_test.go
- pkg/testacc/0_setup_test.go
- pkg/testacc/1_setup_provider_test.go
- pkg/testacc/2_check_destroy_test.go
- pkg/testacc/2_provider_helpers_test.go
- pkg/testacc/provider_acceptance_test.go
- pkg/testacc/resource_masking_policy_acceptance_test.go
- pkg/testacc/resource_view_acceptance_test.go
Add issue numbers for each TODO left with "next PR" annotation. Removed some. Solved the one with the package move (file helpers).
> chore: Clean up TODO comments left with "next PR" without issue number

- pkg/testacc/resource_network_policy_attachment_acceptance_test.go
- pkg/testacc/resource_object_parameter_acceptance_test.go
- Postpone unskip of `TestAcc_ObjectParameterAccount` until `snowflake_object_parameter` rework (due to broken removal logic)
- Run `TestAcc_NetworkPolicyAttachmentAccount` conditionally using `EnsureValidNonProdAccountIsUsed` check
> chore: Address skipped tests (SNOW-2010844)

- pkg/sdk/testint/security_integrations_gen_integration_test.go
It seems that types for OAUTH_ACCESS_TOKEN_VALIDITY and OAUTH_REFRESH_TOKEN_VALIDITY were changed from Integer to Long.
> chore: Adjust security integration tests

- pkg/sdk/testint/warehouses_integration_test.go
The assertion was awaiting, but the value was not refreshed from Snowflake.
> chore: Fix warehouse long-running query test

- MIGRATION_GUIDE.md
- pkg/resources/warehouse.go
- pkg/sdk/testint/warehouses_integration_test.go
- Use UNSET instead of SET with a default value in the warehouse resource.
- Update the integration tests.
> chore: Adjust warehouses after the changes in Snowflake

- pkg/internal/genhelpers/README.md
- pkg/internal/genhelpers/flags.go
- pkg/internal/genhelpers/generation_part_filters.go
- pkg/internal/genhelpers/generator.go
- pkg/internal/genhelpers/imports_test.go
- pkg/internal/genhelpers/object_filters.go
- pkg/schemas/gen/README.md
- pkg/schemas/gen/main/main.go
- pkg/sdk/poc/generator/main/main.go
- pkg/sdk/poc/internal/rework/README.md
Continuation for: https://github.com/snowflakedb/terraform-provider-snowflake/pull/4049
Add common filtering flags to each generator:
- Add new custom flag for filters handling
- Replace the previous filters using environment variables to the ones using command line flag input
- Add description and makefile part to generator common
- Allow printing help for generator
- List all possible values for filters as part of the usage (example below)
- Update generator commons README
- Explain the args preprocessing
- Add missing TODO
- Update show schema generator readme
Example usage for the reworked SDK generator:
```
Generate SDK objects based on the SQL definitions provided.
usage: make [clean-sdk] generate-sdk SF_TF_GENERATOR_ARGS='<args>'
-dry-run
generate to std out instead of saving …
```
> chore: Add common filtering flags to each generator

- .github/dependabot.yml
Set dependabot target branch to dev instead of the default one.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#target-branch-
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependabot-prs#targeting-pull-requests-against-a-non-default-branch
> chore: Set dependabot target branch to dev
