pkg/resources/database.go
pkg/snowflake/escaping.go

This controls how long snowflake keeps data around for their Time Machine feature.

database data_retention_time_in_days

---

pkg/provider/provider_test.go
pkg/resources/database_acceptance_test.go
pkg/resources/database_test.go
pkg/resources/role_acceptance_test.go
pkg/resources/role_grants_acceptance_test.go
pkg/resources/role_grants_internal_test.go
pkg/resources/role_grants_test.go
pkg/resources/role_test.go
pkg/resources/user_acceptance_test.go
pkg/resources/user_test.go
pkg/resources/warehouse_acceptance_test.go
pkg/resources/warehouse_test.go
pkg/snowflake/escaping_test.go
pkg/snowflake/role_grant_test.go

Speeds up acceptance test by ~ 2x.

parallel tests

---

pkg/resources/resource_monitor_acceptance_test.go
pkg/resources/resource_monitor_internal_test.go
pkg/resources/view_internal_test.go
pkg/validation/validation_test.go

migrate tests to testify

---

pkg/resources/database_grant.go
pkg/resources/grant_helpers.go
pkg/resources/schema_grant.go
pkg/resources/table_grant.go
pkg/resources/table_grant_test.go
pkg/resources/view_grant.go
pkg/resources/view_grant_acceptance_test.go
pkg/resources/view_grant_test.go
pkg/resources/warehouse_grant.go
pkg/snowflake/future_grant.go
pkg/snowflake/future_grant_test.go
pkg/snowflake/grant.go

Fixes https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/76

[feature] future object grants and add the table_grant resource

---

README.md
pkg/provider/provider.go

Recognize the new snowflake_table_grant resource

---

Makefile

This is blocking our merges, after a quick exploration I can't find any managed accounts in our test snowflake account. Maybe this is not something our account is authorized to create.

Skip SKIP_MANAGED_ACCOUNT_TEST temporarily

---

Makefile
pkg/resources/database_grant.go
pkg/resources/schema_grant.go
pkg/resources/view_grant.go
pkg/resources/warehouse_grant.go

Need to validate privileges in terraformer so needed these vars to be public in order to reduce duplication

Make Valid Privileges Public

---

README.md

Added a bit about how to set up travis-ci for forked pull requests.

updated README for CI auth

---

pkg/resources/privileges.go
pkg/resources/schema_grant.go

Add schema grant CREATE TEMPORARY TABLE

[feature] Add schema grant CREATE TEMPORARY TABLE

---

.github/pull_request_template.md

Turns out you need '* [ ]' to format a checklist.
* https://help.github.com/en/github/managing-your-work-on-github/about-task-lists

[fix] formatting for pr template checklist

---

go.mod
go.sum

Upgrade lib. Dependabot does not seem to work.
*

update go-sql-mock to v1.4.1

---

go.mod
go.sum
pkg/snowflake/database.go
pkg/snowflake/database_test.go

ListDatabases

---

.github/workflows/ok-to-test.yml

Referencing this for syntax: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-versioned-actions

Add versioning for forked repo

---

.github/workflows/codeql-analysis.yml

Enables GitHub Action for CodeQL scanning. This is free for public repos so might as well start running it. 
*

[feature] CI: Enable CodeQL scanning

---

.github/workflows/integration.yml
.github/workflows/unit.yml
Makefile
go.mod
go.sum
pkg/resources/account_grant.go
pkg/resources/account_grant_acceptance_test.go
pkg/resources/resource_monitor_grant_acceptance_test.go
pkg/resources/stage_grant_acceptance_test.go
pkg/resources/table_grant_acceptance_test.go
pkg/resources/warehouse_grant_acceptance_test.go
tools/tools.go

Working towards having acceptance tests for all resources, this adds for table_grant, stage_grant, resource_monitor, account_grant and warehouse_grant.
*

[testing] acceptance test for several resources

---

Makefile
docs/index.md
go.mod
go.sum

See upstream [bug report](https://github.com/hashicorp/terraform-plugin-docs/issues/12).
* https://github.com/hashicorp/terraform-plugin-docs/issues/12

[fix] check-docs hacky fix for bug in terraform-plugin-docs

---

.github/workflows/ok-to-test.yml
docs/index.md

Successfully released: https://github.com/chanzuckerberg/github-app-token/actions/runs/411524860

Upgrade version for github-app-token package to 1.1.4

---

pkg/resources/storage_integration.go
pkg/resources/storage_integration_acceptance_test.go
pkg/resources/task.go
pkg/snowflake/storage_integration.go

Fix bug in handling storage_integration type field.
*  Fixes #204

[fix] storage_integration bugs

---

pkg/resources/grant_helpers.go
pkg/resources/table_grant.go

~Resolve: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/312~
I only added an ownership privilege in this PR.
See also: #318

Add choices of privilege for table

---

pkg/resources/account_grant_acceptance_test.go
pkg/resources/database_acceptance_test.go
pkg/resources/database_grant_acceptance_test.go
pkg/resources/managed_account_acceptance_test.go
pkg/resources/network_policy_acceptance_test.go
pkg/resources/network_policy_attachment_acceptance_test.go
pkg/resources/resource_monitor_acceptance_test.go
pkg/resources/resource_monitor_grant_acceptance_test.go
pkg/resources/role_acceptance_test.go
pkg/resources/role_grants_acceptance_test.go
pkg/resources/schema_acceptance_test.go
pkg/resources/schema_grant_acceptance_test.go
pkg/resources/share_acceptance_test.go
pkg/resources/stage_acceptance_test.go
pkg/resources/stage_grant_acceptance_test.go
pkg/resources/stream_acceptance_test.go
pkg/resources/table_acceptance_test.go
pkg/resources/table_grant_acceptance_test.go
pkg/resources/task_acceptance_test.go
pkg/resources/user_acceptance_test.go
pkg/resources/view_acceptance_test.go
pkg/resources/view_grant_acceptance_test.go
pkg/resources/warehouse_acceptance_test.go
pkg/resources/warehouse_grant_acceptance_test.go

running acceptance tests locally...
Before:
```
real	3m18.942s
user	0m48.747s
sys	0m31.052s
```
After:
```
real	0m57.765s
user	0m59.877s
sys	0m43.979s
```
*

[testing] switch to parallel test

---

docs/index.md
go.mod
go.sum
templates/index.md.tmpl

Add warning about gosnowflake quirks. Fixes #240 (for now).
none
* https://godoc.org/github.com/snowflakedb/gosnowflake#hdr-Connection_Parameters

[docs] add warning about regions

---

.github/workflows/integration.yml

Tried multiple ways of using the `if` statement in different locations to run different steps, but had to include it in each step. Ran this through a YAML linter. Also referenced: https://github.community/t/substring-function/18401 to get the substring of the input SHA and the head SHA.

Update github workflow to allow mergebot to work

---

.github/workflows/integration.yml

Fix sha substring command for GHA

---

pkg/resources/external_table_grant.go
pkg/resources/file_format_grant.go
pkg/resources/function_grant.go
pkg/resources/grant_helpers.go
pkg/resources/materialized_view_grant.go
pkg/resources/procedure_grant.go
pkg/resources/sequence_grant.go
pkg/resources/stream_grant.go

Fix a handful of deprecations.

[fix] sdk deprecations

---

.github/workflows/integration.yml

The echo was including a new line and giving the wrong length. Tested in my terminal locally. Also should be less than and equal to and not greater than.

Redo if statement for checking sha

---

.github/workflows/unit.yml

Currently causing more pain that it is worth...

disable check-mod in ci

---

go.mod
go.sum
pkg/resources/account_grant.go
pkg/resources/database_grant.go
pkg/resources/external_table_grant.go
pkg/resources/file_format_grant.go
pkg/resources/function_grant.go
pkg/resources/integration_grant.go
pkg/resources/managed_account.go
pkg/resources/materialized_view_grant.go
pkg/resources/procedure_grant.go
pkg/resources/resource_monitor.go
pkg/resources/resource_monitor_grant.go
pkg/resources/schema_grant.go
pkg/resources/sequence_grant.go
pkg/resources/stage_grant.go
pkg/resources/stream_grant.go
pkg/resources/table_grant.go
pkg/resources/view_grant.go
pkg/resources/warehouse_grant.go
pkg/validation/validation.go
pkg/validation/validation_test.go

Adds an error msg when trying an ALL grant
*

Add an informative error message for ALL grants

---

.github/workflows/integration.yml

Trying inline tests instead of matrix to see how github actions responds to forked PRs.

Remove matrix for tests

---

.github/workflows/integration.yml

Adding comment to PR with run logs bc the status in Github Actions doesn't link the run.

Add comment to PR with run link

---

pkg/resources/grant_helpers.go

Fixes https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/436
*

[fix] Checking Error number for grant with invalid object

---

examples/resources/snowflake_schema/import.sh

* `/docs/resources/schema.md` was directly changed without changing `import.sh`.
* So `make doc` generate diff in `docs/resources/schema.md`. This issue should be fixed on main branch.
*

[doc] Fix schema.md

---

docs/resources/schema.md
examples/resources/snowflake_schema/import.sh

* This PR fix the example for `snowflake_schema` resource in the document.
* Fix #434
* https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/schema

[doc] fix doc for snowflake_schema

---

go.sum
pkg/resources/storage_integration.go
pkg/resources/storage_integration_test.go

* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/483

[feature] export STORAGE_GCP_SERVICE_ACCOUNT for GCS StorageIntegration

---

pkg/resources/schema_grant.go

schema_grant: refactor schema grant Update function

---

pkg/resources/database_grant.go

database_grant: update database grants in-place instead of recreating

---

pkg/resources/table_grant.go

table_grant: update table grants in-place instead of recreating

---

docs/resources/materialized_view_grant.md
examples/resources/snowflake_materialized_view_grant/resource.tf

This fix a typo in materialized_view_grant doc.
*

[fix] fix typo in materialized_view_grant doc

---

go.sum

Ran another pre-release but failed because one more dependency was updated.
*

Another dependency needing updates

---

go.mod
go.sum

Update go files

---

.github/titleLint.yml

feat: Add title lint

---

pkg/resources/integration_grant.go

Addressing this feature request: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/551
*

feat: Add importer to integration grant

---

pkg/resources/account_grant.go

Addresses https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/536
*

fix: Add importer to account grant

---

pkg/resources/external_table_acceptance_test.go
pkg/snowflake/external_table.go

Addresses: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/542
*

fix: Escape String for AS in external table

---

pkg/resources/masking_policy.go

Addresses: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/571
*

fix: Remove force_new from masking_expression

---

go.mod
go.sum

fix: Update go

---

go.mod
go.sum

fix: Update go files

---

examples/resources/snowflake_pipe_grant/import.sh
examples/resources/snowflake_pipe_grant/resource.tf
examples/resources/snowflake_task_grant/import.sh
examples/resources/snowflake_task_grant/resource.tf
pkg/provider/provider.go
pkg/resources/helpers_test.go
pkg/resources/pipe_grant.go
pkg/resources/pipe_grant_acceptance_test.go
pkg/resources/pipe_grant_test.go
pkg/resources/task_grant.go
pkg/resources/task_grant_acceptance_test.go
pkg/resources/task_grant_test.go
pkg/snowflake/future_grant.go
pkg/snowflake/grant.go

Implemented Task and Pipe Grant Resources
https://docs.snowflake.com/en/sql-reference/sql/grant-privilege.html
*

feat: Pipe and Task Grant resources

---

pkg/resources/privileges.go
pkg/resources/table_grant.go

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
* #637

feat: Add REBUILD table grant

---

docs/resources/share.md
examples/resources/snowflake_share/resource.tf

Addresses https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/671

fix: Share example

---

pkg/resources/account_grant.go
pkg/resources/account_grant_acceptance_test.go
pkg/resources/privileges.go

Enable  account grants for EXECUTE MANAGED TASK
* https://docs.snowflake.com/en/sql-reference/sql/create-task.html#usage-notes
*

feat: handle-account-grant-managed-task

---

docs/resources/integration_grant.md
examples/resources/snowflake_integration_grant/import.sh

*  Addresses: https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/764

docs: Fix import example for integration grant

---

docs/resources/function.md
pkg/resources/function.go
pkg/resources/function_acceptance_test.go
pkg/snowflake/function.go
pkg/snowflake/function_test.go

I implemented `snowflake_function` for Java UDF.
* https://docs.snowflake.com/en/sql-reference/sql/create-function.html

feat: Support create function with Java language

---

docs/resources/task.md
pkg/resources/task.go
pkg/resources/task_test.go
pkg/snowflake/external_table.go
pkg/snowflake/external_table_test.go
pkg/snowflake/task.go

Support for private preview task error integration feature. Identical to #595 with pipes, except for tasks.
* https://docs.snowflake.com/en/LIMITEDACCESS/task-notifications.html

feat: Task error integration

---

go.mod
go.sum

TODO: Add step to update go in release

chore: Update go files

---

.github/titleLint.yml

@edulop91 using your title lint logic here!

feat: TitleLinter customized

---

.github/workflows/release.yml

Fixing release process with updated tag information

fix: Release tag

---

.github/workflows/release.yml
.goreleaser.yml

Following these instructions: https://www.terraform.io/registry/providers/publishing#github-actions-preferred and adding step 2 to goreleaser.

fix: Add gpg signing to goreleaser

---

CHANGELOG.md

fix: remove unused release

---

.goreleaser.yml

add missing block to goreleaser to publish artifacts
*

fix: update go-releaser

---

pkg/datasources/warehouses_acceptance_test.go
pkg/resources/function_acceptance_test.go
pkg/resources/warehouse_acceptance_test.go

fix: Temporarily disabling acceptance tests for release

---

README.md

Adding table of roadmap items to the readme to prevent duplicate work
*

feat: Adding roadplan to README

---

.github/workflows/team-slack-bot.yml

feat: Adding slack bot for PRs and Issues

---

CHANGELOG.md

Reverts Snowflake-Labs/terraform-provider-snowflake#1103

Revert "chore(main): release 0.38.0"

---

.github/workflows/release.yml

feat: deleting gpg agent before importing key
*

feat: deleting gpg agent before importing key

---

.github/workflows/release.yml
CHANGELOG.md

Delete gpg 3

---

.github/workflows/release.yml
CHANGELOG.md

fix: Delete gpg change

---

.github/workflows/team-slack-bot.yml

fix: update team slack bot configurations
*

fix: update team slack bot configurations

---

.github/workflows/team-slack-bot.yml

Adding in link for slackbot to publish issue, was only doing on github pull requests previously
*

fix: adding in issue link to slackbot

---

pkg/resources/role.go
pkg/resources/role_grants.go
pkg/resources/role_ownership_grant.go

This change expands the allowed special characters for role names to more align with what is allowed by Snowflake.
*

fix: expand allowed special characters in role names

---

download.sh

Fixes [#1137](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1137)

fix: update download.sh to enable installation on arm/64 platform

---

docs/resources/pipe.md
examples/resources/snowflake_pipe/resource.tf

fix: doc pipe

---

docs/resources/resource_monitor_grant.md
examples/resources/snowflake_resource_monitor_grant/resource.tf

FIx resource names of resource_monitor_grant.
N/A
* #455

fix: doc of resource_monitor_grant

---

LICENSE
go.mod
go.sum

update license and revert change for go mod causing last release to fail
*

chore: update-license

---

pkg/datasources/current_account.go
pkg/datasources/database.go
pkg/datasources/databases.go
pkg/datasources/system_get_privatelink_config.go
pkg/datasources/system_get_snowflake_platform_info.go
pkg/resources/managed_account.go
pkg/resources/resource.go
pkg/resources/tag_association.go
pkg/snowflake/database.go
pkg/snowflake/external_function.go
pkg/snowflake/external_table.go
pkg/snowflake/file_format.go
pkg/snowflake/function.go
pkg/snowflake/masking_policy.go
pkg/snowflake/materialized_view.go
pkg/snowflake/pipe.go
pkg/snowflake/procedure.go
pkg/snowflake/resource_monitor.go
pkg/snowflake/row_access_policy.go
pkg/snowflake/schema.go
pkg/snowflake/sequence.go
pkg/snowflake/stage.go
pkg/snowflake/storage_integration.go
pkg/snowflake/stream.go
pkg/snowflake/table.go
pkg/snowflake/tag.go
pkg/snowflake/task.go
pkg/snowflake/user.go
pkg/snowflake/view.go
pkg/snowflake/warehouse.go

fix: log fmt

---

pkg/provider/provider.go
pkg/provider/provider_test.go

Adding in a "Application" connection param which can be used to determine where requests are coming from.
*

feat: add connection param for snowhouse

---

docs/index.md
pkg/provider/provider.go
pkg/provider/provider_test.go

adds port and protocol to provider config. closes PR #962.

feat: add port and protocol to provider config

---

.github/workflows/go-fmt.yml
pkg/datasources/users.go
pkg/datasources/warehouses_acceptance_test.go
pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/resources/account_grant_test.go
pkg/resources/database_grant.go
pkg/resources/function.go
pkg/resources/masking_policy.go
pkg/resources/materialized_view.go
pkg/resources/pipe.go
pkg/resources/procedure.go
pkg/resources/resource_monitor.go
pkg/resources/role_grants.go
pkg/resources/role_ownership_grant_acceptance_test.go
pkg/resources/row_access_policy.go
pkg/resources/sequence.go
pkg/resources/share.go
pkg/resources/snowflake_sweeper_test.go
pkg/resources/stream.go
pkg/resources/table.go
pkg/resources/tag.go
pkg/resources/tag_association_acceptance_test.go
pkg/resources/task.go
pkg/resources/user_public_keys.go
pkg/snowflake/grant.go
pkg/snowflake/network_policy.go
pkg/snowflake/stream.go
pkg/snowflake/task.go
pkg/validation/validation.go

This adds in a github workflow that checks if **go fmt** has been run on the code before being merged in.
I also went ahead and **go fmt** everything in the repo.
*

style: Go fmt check workflow plus formatting.

---

pkg/resources/table_acceptance_test.go

Fixed Table Tags Acceptance Test. @sfc-gh-swinkler  Some reason this test was failing, this is  the fix for that test
* #1228 
* #1242 
* #1244

fix: Table Tags Acceptance Test

---

pkg/snowflake/database.go

* Fixed addressing the tag with a fully qualified identifier
* fixed UNSET by removing value in statement
* https://docs.snowflake.com/en/sql-reference/sql/alter-database.html#syntax

fix: Database tags UNSET (fixes #1256)

---

.github/workflows/team-jira-issues.yml

New workflow that will add a jira issue when ever an issue is opened in this repo.

feat: Adding in new jira workflow

---

.github/workflows/team-jira-issues.yml

Update to the github action to pin the version instead of using master.

fix: Pin Jira actions versions

---

docs/resources/oauth_integration.md
pkg/resources/oauth_integration.go
pkg/resources/oauth_integration_acceptance_test.go
pkg/resources/snowflake_sweeper_test.go
pkg/snowflake/oauth_integration.go

feat: add custom oauth int

---

go.mod

fix: ie-proxy for go build

---

go.mod
go.sum

fix: rollback sdk version

---

pkg/resources/task.go
pkg/snowflake/validation.go
pkg/snowflake/validation_test.go

fix: validate identifier

---

README.md

fix: remove outdated roadmap

---

README.md

feat: new release

---

README.md

feat: update doc

---

sdk/database.go
sdk/database_test.go
sdk/role.go
sdk/role_test.go
sdk/snowflake.go
sdk/user.go
sdk/user_test.go
sdk/warehouse.go
sdk/warehouse_test.go

V2 warehouses

---

pkg/datasources/roles.go
pkg/datasources/roles_acceptance_test.go

fix: format for go ci

---

docs/resources/role_ownership_grant.md
docs/resources/user_ownership_grant.md
pkg/resources/role_ownership_grant.go
pkg/resources/user_ownership_grant.go

feat: Delete ownership grant updates

---

docs/resources/stage_grant.md
examples/resources/snowflake_stage_grant/resource.tf

Fixed documentation https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1285 .

fix: remove shares from snowflake_stage_grant #1285

---

sdk/database.go
sdk/database_test.go
sdk/network_policy.go
sdk/network_policy_test.go
sdk/role.go
sdk/role_test.go
sdk/schema.go
sdk/schema_test.go
sdk/snowflake.go
sdk/table.go
sdk/table_test.go
sdk/types.go
sdk/user.go
sdk/user_test.go
sdk/warehouse.go
sdk/warehouse_test.go

add schema, database, table, network policy and warehouse interfaces 

---

docs/resources/database.md
pkg/resources/database.go

*  This is not a computed attribute. copy and pasted description from https://docs.snowflake.com/en/sql-reference/sql/create-database.html#optional-parameters

docs: Add description for data_retention_time_in_days

---

docs/resources/api_integration.md
pkg/resources/api_integration.go

Fixed Integration Tests for API Integration implementation of API_KEY introduced with #1386 
*  #1386 
* #1401

fix: Removed Read for API_KEY

---

docs/index.md
pkg/resources/file_format.go
pkg/resources/file_format_test.go
pkg/snowflake/table_constraint.go
pkg/snowflake/tag_association.go

Fixed missing stmt for #1384 which is blocking the release. Ran also Fmt and Docs
* #1384 
*  #1401

fix: Go Expression Fix #1384

---

pkg/datasources/functions.go
pkg/datasources/functions_acceptance_test.go
pkg/datasources/warehouses_acceptance_test.go
pkg/resources/warehouse.go
pkg/snowflake/function.go

fix: warehouses update issue

---

go.mod
go.sum

fix: remove ieproxy-0.0.9

---

README.md

fix: 0.54 

---

docs/resources/failover_group.md
examples/resources/snowflake_failover_group/resource.tf
pkg/resources/failover_group.go
pkg/resources/failover_group_acceptance_test.go
pkg/snowflake/failover_group.go

fix: interval for failover groups

---

docs/resources/stage_grant.md
pkg/resources/stage_grant.go

Closes #1100 
Closes #1477 
```
make test
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/datasources  2.843s  coverage: 3.6% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider     4.256s  coverage: 25.5% of statements
ok      github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources    13.904s coverage: 46.9% of statements
ok …
```

fix: schema name is optional for future snowflake_stage_grant

---

pkg/resources/user.go

This PR does a refactor related to handling error and simplifies some lines.

fix: expression handling err for user

---

pkg/resources/grant_helpers.go

fix: backwards compatability for grant helpers id used by procedure and functions

---

pkg/snowflake/tag_association.go

fix: misc linting changes for 0.56.2

---

CHANGELOG.md
pkg/resources/grant_helpers.go
pkg/resources/role_grants.go

fix: future read on grants

---

README.md

Update README.md guidance around enterprise support
N/A

chore: Update ReadMe to better guide enterprise customers

---

pkg/resources/function_grant.go
pkg/resources/procedure_grant.go

fix: proc id parsing for legacy id

---

pkg/snowflake/parameters.go

Add missing option as per https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1542

fix: snowflake_account_parameter add missing option

---

pkg/helpers/list_to_string_helpers.go
pkg/resources/function_grant.go
pkg/resources/function_grant_test.go
pkg/resources/procedure_grant.go
pkg/resources/procedure_grant_test.go

add test cases for procedure / functions. trim whitespace from argument ids

fix: procedure-id-fix

---

pkg/resources/schema.go
pkg/resources/schema_test.go

Fixes the problem when a schema refresh is performed, when the schema and the corresponding database had been deleted in snowflake.
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1529
PS: I have the impression that similar problems might exist with other resources. I might have a look on this as the next step.

fix: schema read now checks first if the corresponding database exists

---

pkg/resources/role_grants.go
pkg/resources/role_grants_test.go

fix: update read role grants to use new builder

---

pkg/helpers/list_to_string_helpers.go
pkg/resources/tag.go

fix: tag unncessary update if allowed list is empty

---

pkg/resources/account_parameter_acceptance_test.go
pkg/snowflake/parameters.go

added missing account property: PREVENT_LOAD_FROM_INLINE_URL
* [x ] acceptance tests
*

feat: add PREVENT_LOAD_FROM_INLINE_URL

---

docs/resources/view.md
pkg/resources/view.go
pkg/resources/view_acceptance_test.go
pkg/snowflake/parser.go
pkg/snowflake/parser_test.go
pkg/snowflake/view.go
pkg/snowflake/view_test.go

feat: Add COPY GRANTS arg to views resources.

---

docs/resources/account.md
docs/resources/user.md
pkg/resources/account.go
pkg/resources/user.go

feat: mark PII as sensitive in account and user resources.

---

docs/resources/procedure_grant.md
examples/resources/snowflake_procedure_grant/resource.tf

* Stored procedures only accept usage and ownership grants 
* https://docs.snowflake.com/en/sql-reference/sql/grant-privilege
* https://docs.snowflake.com/en/sql-reference/sql/grant-ownership

fix: change incorrect select privilege to usage for stored procedure grant

---

LEGAL.md

chore: LEGAL.md

---

docs/resources/alert.md
examples/resources/snowflake_alert/resource.tf

fixes alert docs
N/A
fix for #1745 
*

fix: alert docs

---

docs/resources/external_function.md
pkg/resources/external_function.go
pkg/resources/external_function_acceptance_test.go
pkg/snowflake/external_function.go
pkg/snowflake/external_function_test.go

This PR fixes #1251.
* [ *] acceptance tests
https://docs.snowflake.com/en/sql-reference/external-functions-translators
*

feat: Add external function translators

---

pkg/resources/account.go
pkg/sdk/accounts.go
pkg/sdk/accounts_test.go
pkg/sdk/client.go
pkg/sdk/comments.go
pkg/sdk/comments_integration_test.go
pkg/sdk/comments_test.go
pkg/sdk/context_functions.go
pkg/sdk/context_functions_integration_test.go
pkg/sdk/object_types.go

Implements Accounts API in new SDK and use it in account resource.

chore: Account SDK

---

pkg/resources/database_grant.go

Setting the privilege to usage when we see IMPORTED PRIVILEGES for a database grant when checking the current permissions on the database. The provider just needs to check to see if the role in the resource has an existing usage grant on the database, if not it will issue the IMPORTED PRIVILEGES database grant again. 
1. Define a snowflake_database_grant resource in Terraform to grant IMPORTED PRIVILEGES to a Snowflake role on a database that is created from a Data Share.
1. Apply the Terraform configuration to create the grant in Snowflake.
1. Remove the IMPORTED PRIVILEGES grant from the database outside of Terraform.
1. Run terraform plan.
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1780

fix: the issue reported in 1780.

---

docs/resources/database_grant.md
docs/resources/external_table_grant.md
docs/resources/failover_group_grant.md
docs/resources/file_format_grant.md
docs/resources/function_grant.md
docs/resources/integration_grant.md
docs/resources/masking_policy_grant.md
docs/resources/materialized_view_grant.md
docs/resources/pipe_grant.md
docs/resources/role_grants.md
docs/resources/row_access_policy_grant.md
docs/resources/schema_grant.md
docs/resources/sequence_grant.md
docs/resources/stage_grant.md
docs/resources/stream_grant.md
docs/resources/table_grant.md
docs/resources/tag_grant.md
docs/resources/task_grant.md
docs/resources/view_grant.md
docs/resources/warehouse_grant.md
pkg/provider/provider.go
pkg/resources/failover_group_grant.go
pkg/resources/grant_helpers.go
pkg/sdk/client.go
pkg/sdk/data_types.go
pkg/sdk/roles.go
pkg/sdk/sweepers.go
pkg/snowflake/all_grant.go

fixes to get main into a working state for 0.65 release

fix: 0.65 integration tests and minor linting fixes

---

README.md

Update readme to properly steer customers.

chore: Updating README to better align Snowflake resources.

---

docs/resources/role_grants.md

chore: update docs

---

pkg/sdk/sweepers.go

detach network and password policies from account
```
--- PASS: TestSweepAll (6.36s)
--- PASS: TestSweepAll/all_sweepers_in_secondary_account (2.17s)
--- PASS: TestSweepAll/all_sweepers_in_primary_account (4.19s)
PASS
ok  	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk	6.981s
```

fix: sweepers

---

.github/workflows/integration.yml
.github/workflows/unit.yml
pkg/sdk/alerts_integration_test.go
pkg/sdk/client.go
pkg/sdk/errors.go
pkg/sdk/helper_test.go
pkg/sdk/schemas.go
pkg/sdk/schemas_integration_test.go
pkg/sdk/schemas_test.go

First pr for the schemas sdk migration (in the next one It'll be used in the resources/data sources)
[Snowflake schema documentation](https://docs.snowflake.com/en/sql-reference/sql/create-schema)

feat: Schemas sdk v2

---

pkg/sdk/accounts.go
pkg/sdk/alerts.go
pkg/sdk/alerts_integration_test.go
pkg/sdk/databases.go
pkg/sdk/failover_groups.go
pkg/sdk/file_format.go
pkg/sdk/file_format_integration_test.go
pkg/sdk/grants_integration_test.go
pkg/sdk/helper_test.go
pkg/sdk/masking_policy.go
pkg/sdk/masking_policy_integration_test.go
pkg/sdk/password_policy.go
pkg/sdk/password_policy_integration_test.go
pkg/sdk/resource_monitors.go
pkg/sdk/resource_monitors_integration_test.go
pkg/sdk/session_policies.go
pkg/sdk/shares.go
pkg/sdk/shares_integration_test.go
pkg/sdk/users.go
pkg/sdk/users_integration_test.go
pkg/sdk/warehouses.go

Remove unnecessary pointers from Show methods return type + minor changes

chore: Change return type of show

---

docs/index.md
pkg/provider/provider.go

#2131, #2133
fix bug in provider configuration for profile

fix: provider config

---

MIGRATION_GUIDE.md

add migration guide / notes for future api changes

chore: Add migration guide

---

pkg/provider/provider.go
pkg/provider/provider_helpers.go

fix: private key auth

---

docs/resources/grant_privileges_to_role.md
examples/resources/snowflake_grant_privileges_to_role/resource.tf

A fix for issue #2044 - add required field in the doc

fix: grants example in the documentation

---

docs/resources/role_ownership_grant.md
examples/resources/snowflake_role_ownership_grant/import.sh

Fix documentation: fixes #2198

fix: documentation for role ownership grant

---

docs/resources/grant_privileges_to_role.md
pkg/resources/grant_privileges_to_role.go
pkg/resources/grant_privileges_to_role_acceptance_test.go
pkg/sdk/grants.go
pkg/sdk/grants_test.go
pkg/sdk/grants_validations.go
pkg/sdk/object_types.go
pkg/sdk/privileges.go

fix: Add missing parameters

---

pkg/sdk/testint/resource_monitors_integration_test.go

Fix the test that was using hardcoded date (that is now in the past).

fix: Fix test because of the date

---

pkg/resources/dynamic_table_acceptance_test.go
pkg/resources/email_notification_integration_acceptance_test.go
pkg/resources/task.go
pkg/sdk/tables.go
pkg/sdk/testint/tables_integration_test.go

Add missing and update existing TODOs while cleaning up the backlog.

chore: Add missing issues to existing TODOs and add missing ones

---

.goreleaser.yml

fixes issue with 
> template: main:1:27: executing "main" at <or>: wrong number of args for or: want at least 1 got 0
tested on https://gotemplate.io/ and run goreleaser build locally

fix: mfa token caching

---

README.md
pkg/provider/provider.go
pkg/sdk/poc/main.go

minor updates in preparation for release.

chore: update readme and fmt

---

README.md
ROADMAP.md
docs/index.md
templates/index.md.tmpl

- Add experimental project status disclaimer
- Add roadmap overview
- Update the SDK migration table

docs: Add disclaimer and roadmap

---

.github/workflows/team-jira-issues.yml
docs/index.md
templates/index.md.tmpl

- better jira integration
- migration guide added to the official docs

chore: Add migration notes to the docs and change jira integration

---

.github/workflows/team-jira-issues.yml

fix: Remove title and body temporarily from jira integration

---

pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnAllTablesInSchema/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnAllTablesInSchema_NoGrant/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnDatabase/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnDatabase_NoGrant/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnDatabase_NoPrivileges/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnSchema/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnSchema_NoGrant/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnTable/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnTable_NoGrant/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnTag/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnTag_NoGrant/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnView/test.tf
pkg/resources/testdata/TestAcc_GrantPrivilegesToShare/OnView_NoGrant/test.tf

fix: correct test dependencies

---

pkg/resources/database.go
pkg/resources/database_acceptance_test.go
pkg/sdk/databases_test.go
pkg/sdk/failover_groups_test.go
pkg/sdk/identifier_helpers.go
pkg/sdk/random.go
pkg/sdk/replication_functions.go
pkg/sdk/replication_functions_test.go
pkg/sdk/shares_test.go
pkg/sdk/testint/helpers_test.go
pkg/sdk/testint/replication_functions_integration_test.go

- Move replication config in create to the right place
- Add show replication databases to the SDK
- Add `FullyQualifiedName` to `ExternalIdentifier`
References: #2021

fix: Fix replication for database resource

---

docs/resources/database.md
examples/resources/snowflake_database/resource.tf

Fix quote escaping in database resource docs
References: #2078

docs: Fix escape quotes in database docs

---

README.md

Remove SDK migration from README.

docs: Remove SDK migration from README

---

pkg/resources/account_parameter.go
pkg/resources/account_parameter_acceptance_test.go

Set key during read (fixes import).
References: #2573

fix: Fix import for account parameter

---

docs/index.md
examples/additional/deprecated_datasources.MD
examples/additional/deprecated_resources.MD
pkg/internal/tools/doc-gen-helper/main.go

fix: Add missing path

---

.github/workflows/release.yml
pkg/resources/database.go

Revert conditionality in release jobs

fix: Fix release workflow

---

docs/resources/dynamic_table.md

fix: Generate docs for dynamic table

---

pkg/resources/grant_ownership.go
pkg/resources/grant_ownership_acceptance_test.go
pkg/resources/testdata/TestAcc_GrantOwnership/OnObject_DatabaseRole_ToAccountRole/test.tf
pkg/resources/testdata/TestAcc_GrantOwnership/OnObject_DatabaseRole_ToAccountRole/variables.tf

A fix for #2700. Changed expected granted_on when it's equal to the database role. Acceptance test added.

fix: granting ownership on database roles

---

pkg/acceptance/helpers/application_client.go
pkg/acceptance/helpers/application_package_client.go
pkg/acceptance/helpers/dynamic_table_client.go
pkg/acceptance/helpers/session_policy_client.go
pkg/acceptance/helpers/stage_client.go
pkg/acceptance/helpers/test_client.go
pkg/resources/dynamic_table_acceptance_test.go
pkg/resources/testdata/TestAcc_DynamicTable_issue2173/1/test.tf
pkg/resources/testdata/TestAcc_DynamicTable_issue2173/2/test.tf
pkg/sdk/application_packages_gen.go
pkg/sdk/dynamic_table.go
pkg/sdk/dynamic_table_dto.go
pkg/sdk/dynamic_table_dto_builders.go
pkg/sdk/dynamic_table_impl.go
pkg/sdk/dynamic_table_test.go
pkg/sdk/stages_dto_gen.go
pkg/sdk/stages_impl_gen.go
pkg/sdk/testint/accounts_integration_test.go
pkg/sdk/testint/application_roles_gen_integration_test.go
pkg/sdk/testint/applications_integration_test.go
pkg/sdk/testint/dynamic_table_integration_test.go
pkg/sdk/testint/external_tables_integration_test.go
pkg/sdk/testint/grants_integration_test.go
pkg/sdk/testint/helpers_test.go
pkg/sdk/testint/pipes_integration_test.go
pkg/sdk/testint/streamlits_integration_test.go
pkg/sdk/testint/streams_gen_integration_test.go
pkg/sdk/testint/system_functions_integration_test.go
pkg/sdk/testint/tables_integration_test.go

Next part of helpers cleanup:
- dynamic helper
- stage
- application
- application package
- session policy
Helpers were simplified and aligned with other helpers.

chore: Cleanup helpers part4

---

CREATING_ISSUES.md
README.md

Add a guide on creating issues with FAQ and commonly known issues with solutions

chore: Add a guide on creating issues

---

.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-general-usage.yml
.github/ISSUE_TEMPLATE/03-documentation.yml
.github/ISSUE_TEMPLATE/04-feature-request.yml

fix: Fix issue templates

---

pkg/resources/alert.go

Now, after failing alert alter operation, terraform keeps the created alert in state. A warning is shown to a user when alter fails. Alert can be now enabled by using terraform apply.
Also, CRUD functions are changed to functions with context due to deprecations in terraform sdk.
This change was tested on a real Snowflake environment. 
*

fix: Invoke SetId immediately after alert creation

---

docs/resources/table_constraint.md
examples/resources/snowflake_table_constraint/import.sh

clarifying import expression structure for table constraint resource

docs: clarifying import expression structure for table constraint resource

---

pkg/resources/user.go

Fix issue with default secondary roles option import

fix: Fix default secondary roles option import

---

pkg/sdk/sweepers_test.go

chore: Add Filip to protected users

---

pkg/sdk/sweepers_test.go

chore: Add Filip legacy to protected users

---

.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-general-usage.yml
.github/ISSUE_TEMPLATE/03-documentation.yml
.github/ISSUE_TEMPLATE/04-feature-request.yml
docs/resources/shared_database.md

Fixes https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3075

docs: Fix example for shared_database & updated issue template

---

pkg/resources/custom_diffs_test.go

- fix duplicated package import

fix: Fix main

---

.github/workflows/tests.yml

Based on the:
- experiments here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3232
- docs here: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#masking-a-value-in-a-log

chore: Apply masking

---

.github/workflows/tests.yml

Revert to previous env after merge

chore: Revert to proper env

---

docs/technical-documentation/resource_migration.md

- Add information about the `removed` block for state removal.
- Improve the style.
#2468

docs: Adjust Resource migration guide

---

docs/guides/authentication_methods.md
templates/guides/authentication_methods.md.tmpl

- Create a guide for authentication flows

chore: Prepare authentication methods guide

---

ROADMAP.md

chore: Add GA scope to the roadmap

---

go.mod

chore: Bump Go version

---

pkg/internal/tracking/context.go

Include Bump provider version (#3419) into 1.0.4 release

chore: merge dev into main

---

pkg/resources/oauth_integration_for_partner_applications_acceptance_test.go

fix: Quick fix assertions

---

pkg/internal/tracking/context.go

Bump provider version in the tracking package.

chore: Bump tracking version to v1.0.5

---

MIGRATION_GUIDE.md

Fix the migration guide after resolving conflicts incorrectly.

chore: Fix migration guide

---

README.md

Remove the outdated ToC in README

fix: Remove the outdated section from README's ToC

---

CHANGELOG.md

- Remove duplicate entries from the changelog.

chore: Fix changelog after v1.0.5

---

.github/workflows/ok-to-test.yml

- Change required privileges for ok-to-test command

chore: Change privileges in ok-to-test

---

pkg/acceptance/testing.go
pkg/provider/provider.go

Move env conditional logic from the production provider setup to acceptance tests setup

fix: Fix acceptance tests setup

---

README.md
SNOWFLAKEDB_MIGRATION.md

- Add information about migrating to snowflakedb namespace.
- Adjust namespaces in README (links and example).
- Adjust an example in README to promote safer configurations.

chore: Add information about migrating to snowflakedb namespace

---

pkg/sdk/sweepers_test.go

Increase nuke timeout for databases and warehouses

fix: Increase stale objects timeout

---

ROADMAP.md

Add new roadmap entry w GA announcement

chore: New roadmap entry GA announcement

---

.github/workflows/tests.yml
pkg/internal/tracking/context.go
pkg/internal/tracking/version.go

Skip tests workflow for docs and tracking version

chore: Skip tests workflow for docs only

---

pkg/internal/tracking/version.go

chore: Bump provider version

---

.github/workflows/tests.yml

Fix ignore paths for tests workflow

chore: Fix paths ignore

---

.github/workflows/tests.yml

chore: merge dev to main

---

pkg/acceptance/helpers/ids_generator.go
pkg/sdk/testint/identifier_integration_test.go

Add test object suffix to 1- and 2-part identifier tests

fix: Fix identifier tests

---

.github/workflows/codeql-analysis.yml

- Adjusted Go setup for CodeQL (it looked good on the pr-s, but in the security tab it says that the build step is required, so added that worked previously).
- Renamed the job name, which should get rid of strange errors on the prs.

chore: Adjust codeql analysis

---

MIGRATION_GUIDE.md

Add data types new handling to the migration guide

chore: Add missing migration guide

---

ROADMAP.md

chore: Add new roadmap entry

---

MIGRATION_GUIDE.md
docs/index.md
templates/index.md.tmpl

- Added info on supported architectures in the registry documentation
- Adjusted migration guide

chore: Documentation adjustments

---

MIGRATION_GUIDE.md

chore: Prepare 2.0.0 release

---

MIGRATION_GUIDE.md

chore: release 2.0.0
Release-As: 2.0.0

chore: release 2.0.0

---

docs/resources/grant_privileges_to_account_role.md
docs/resources/grant_privileges_to_database_role.md
templates/resources/grant_privileges_to_account_role.md.tmpl
templates/resources/grant_privileges_to_database_role.md.tmpl

* Remove note regarding future Streamlits in the `grant_privileges_to_database_role`
* #3423
* #3569

chore: remove note regarding future Streamlits

---

README.md

chore: Remove the holiday note

---

ROADMAP.md

* Fixes #3620
Ctrl+Shift+F'ed in VS Code and found a similar DD.MM.YYYY date format in `pkg/scripts/issues/README.md` - I scoped this change just to ROADMAP.md, so not changing that one (wasn't sure if that would disrupt any automation)
https://github.com/snowflakedb/terraform-provider-snowflake/blob/8186354fbb65e4c88aa408156838bc5d90b57a24/pkg/scripts/issues/README.md?plain=1#L25

chore: Change date format DD.MM.YYYY to YYYY-MM-DD

---

MIGRATION_GUIDE.md

Update migration guide to correct version

chore: Update migration guide

---

pkg/testacc/2_check_destroy_test.go

Add missing entry after moving

fix: Fix image repositories cleanup

---

pkg/testacc/tables_acceptance_test.go

fix: Table test

---

docs/resources/grant_privileges_to_account_role.md
docs/resources/grant_privileges_to_database_role.md
docs/resources/grant_privileges_to_share.md
templates/resources/grant_privileges_to_account_role.md.tmpl
templates/resources/grant_privileges_to_database_role.md.tmpl
templates/resources/grant_privileges_to_share.md.tmpl

- Put additional documentation for privilege-granting resources regarding best practices and all available privileges in Snowflake.

chore: enhance privilege-granting resource documentation

---

pkg/resources/network_policy_attachment.go
pkg/sdk/accounts.go
pkg/sdk/accounts_test.go
pkg/sdk/parameters.go
pkg/sdk/parameters_test.go
pkg/sdk/testint/accounts_integration_test.go
pkg/sdk/testint/conversion_functions_integration_test.go

- Rename account unset parameters
- Introduce new parameters structure

chore: Rename account unset parameters

---

FAQ.md
pkg/acceptance/helpers/information_schema_client.go
pkg/acceptance/helpers/random/random_helpers.go
pkg/sdk/testint/git_repositories_integration_test.go
pkg/sdk/testint/tags_integration_test.go
pkg/testacc/snowflake_behavior_object_renaming_acceptance_test.go
pkg/testacc/testdata/TestAcc_DynamicTable_timeouts/test.tf

- Fix the test that was failing due to NPE because of the missing query tag from the Snowflake response
- Fix the dynamic table test by increasing the timeout value
- Fix the tests that are using `random.Email()` by adjusting the length of the email and its structure
- Add note on OpenTofu support to the FAQ
- Address in-code TODO
- Run pre-push (changes caused by previous prs)

chore: Small improvements

---

pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/compute_pool_show_output_ext.go
pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/task_show_output_ext.go
pkg/testacc/resource_compute_pool_acceptance_test.go
pkg/testacc/resource_task_acceptance_test.go

- Fix 6 tests that had incorrect show_output assertions (the part added to _ext is planned to be generated).

chore: Test fixes

---

MIGRATION_GUIDE.md
pkg/sdk/grants_impl.go
pkg/testacc/resource_grant_ownership_acceptance_test.go
pkg/testacc/testdata/TestAcc_GrantOwnership/OnTask/test.tf
pkg/testacc/testdata/TestAcc_GrantOwnership/OnTask/variables.tf

- Adjust the grant on task implementation to be able to grant ownership of serverless tasks
* Ref: #3750

fix: Grant ownership on serverless tasks

---

MIGRATION_GUIDE.md

- Add missing migration guide entry for snowflake_external_volume resource creation fix
- Fix migration guide formatting

chore: Add missing migration guide and fix formatting

---

MIGRATION_GUIDE.md
pkg/sdk/parameters.go

Fix ENABLE_INTERNAL_STAGES_PRIVATELINK mapping in snowflake_account_parameter resource

fix: Fix account parameter mapping

---

MIGRATION_GUIDE.md

Clarify the snowflake_schema migration entry (v0.94.0)

docs: Clarify the snowflake_schema migration entry

---

pkg/sdk/functions_and_procedures_parsers.go
pkg/sdk/functions_and_procedures_parsers_test.go

Introduce a new function and procedure parsing function with tests
It's not used yet in any production code

fix: Introduce a new function and procedure parsing function

---

docs/guides/organization_account_migration.md
templates/guides/organization_account_migration.md.tmpl

- Add organization account migration guide

docs: Add organization account migration guide

---

.github/workflows/tests-account-level.yml
.github/workflows/tests.yml
pkg/sdk/sweepers.go

- Add network policy sweeper
- Skip file filtering for repository_dispatch events in test workflows

chore: Adjust sweepers and test workflows

---

pkg/testacc/resource_grant_privileges_to_share_acceptance_test.go

- Adjust grant privileges to share test to make it consistent with other tests

chore: Adjust grant privileges to share test

---

pkg/sdk/testint/listings_integration_test.go

- Fix listing integration tests

fix: Listing tests fix

---

docs/resources/failover_group.md
templates/resources/failover_group.md.tmpl

chore: Update failover group docs

---

MIGRATION_GUIDE.md
pkg/acceptance/bettertestspoc/assert/objectassert/database_snowflake_gen.go
pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/database_show_output_gen.go
pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/gen/model.go
pkg/sdk/databases.go
pkg/sdk/masking_policy.go
pkg/sdk/tasks_impl_gen.go

- Adjust Origin from ExternalObjectIdentifier to ObjectIdentifier (because the SNOWFLAKE database has 2-part origin)
- Fix tasks and masking policy JSON parsing
- Add migration guide entry

chore: Convert function adjustments follow-up

---

pkg/resources/manual_tests/using_consumption_billing_entity_in_account/step_1.tf
pkg/resources/manual_tests/using_consumption_billing_entity_in_account/using_consumption_billing_entity_in_account.md

- Add manual test that describes how to test consumption billing entity functionality

chore: Add manual test for consumption billing entity

---

pkg/sdk/poc/main.go
pkg/sdk/semantic_view_gen.go
pkg/sdk/semantic_view_gen_test.go
pkg/testacc/10_plugin_framework_poc_provider_configure_test.go
pkg/testacc/10_plugin_framework_poc_provider_test.go
pkg/testacc/11_plugin_framework_poc_resource.go
pkg/testacc/19_plugin_framework_poc_commons_test.go
pkg/testacc/20_plugin_framework_poc_warehouse_test.go
pkg/testacc/30_rest_api_poc_client_test.go
pkg/testacc/plugin_framework_poc_acceptance_test.go
pkg/testacc/plugin_framework_poc_warehouse_acceptance_test.go
pkg/testacc/plugin_framework_poc_warehouse_sdkv2_copy_acceptance_test.go
pkg/testacc/poc/gen/main/main.go
pkg/testacc/poc/gen/mapper.go
pkg/testfunctional/10_plugin_framework_poc_helpers_enums.go
pkg/testfunctional/10_plugin_framework_poc_helpers_zero_values.go
pkg/testfunctional/common/dynamic_handler.go
pkg/testfunctional/common/http_server_embeddable.go
pkg/testfunctional/computednestedlist/test_resource_plugin_framework_computed_nested_list.go
pkg/testfunctional/customplanmodifiers/replace_when_removed_from_config.go
pkg/testfunctional/customtypes/enum_generic_value.go
pkg/testfunctional/test_resource_plugin_framework_parameter_handling_private_acceptance_test.go
pkg/testfunctional/test_resource_plugin_framework_zero_values_handling.go
pkg/testfunctional/test_resource_plugin_framework_zero_values_handling_acceptance_test.go

Fill out issue numbers for all TODOs created during Terraform Plugin Framework and RestAPI research
Changes after `make pre-push`

chore: Clean up all TODOs created during Terraform Plugin Framework and RestAPI research

---

pkg/acceptance/helpers/0_tests_setup_helpers.go

Solve a small TODO regarding using DropSafely in int and acc test setup helpers

chore: Use DropSafely in test setup helpers

---

SNOWFLAKE_BCR_MIGRATION_GUIDE.md
docs/resources/authentication_policy.md
docs/resources/external_oauth_integration.md
pkg/acceptance/bettertestspoc/assert/objectassert/semantic_view_describe_snowflake_ext.go
pkg/sdk/testint/semantic_view_integration_test.go
pkg/testacc/resource_service_acceptance_test.go
templates/resources/authentication_policy.md.tmpl
templates/resources/external_oauth_integration.md.tmpl

- Update the BCR Migration guide with an 2025_06 entry.
- Add notes about missing features in resource documentation.
- Fix pre-push.
- Adjust service test assertions.
- Adjust the authentication policy resource to this BCR (SNOW-2332934)
SNOW-2301041

chore: Handle BCR 2025-06

---

pkg/sdk/authentication_policies_def.go
pkg/sdk/testint/authentication_policies_gen_integration_test.go

Adjust the auth policy integration tests after recent changes in account setup.

chore: Adjust integration tests
